-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_stat_c_mensili_1;
-- DROP INDEX INDEX_STAT_MONTH;
-- DROP INDEX INDEX_STAT_MONTH_FULL;
-- DROP INDEX INDEX_STAT_MONTH_ENTRY;
-- DROP INDEX idx_stat_c_settimanali_1;
-- DROP INDEX INDEX_STAT_WEEK;
-- DROP INDEX INDEX_STAT_WEEK_FULL;
-- DROP INDEX INDEX_STAT_WEEK_ENTRY;
-- DROP INDEX idx_stat_c_giornaliere_1;
-- DROP INDEX INDEX_STAT_DAY;
-- DROP INDEX INDEX_STAT_DAY_FULL;
-- DROP INDEX INDEX_STAT_DAY_ENTRY;
-- DROP INDEX idx_stat_c_orarie_1;
-- DROP INDEX INDEX_STAT_HOUR;
-- DROP INDEX INDEX_STAT_HOUR_FULL;
-- DROP INDEX INDEX_STAT_HOUR_ENTRY;
DROP TABLE stat_mensili_contenuti;
DROP TABLE statistiche_mensili;
DROP TABLE stat_settimane_contenuti;
DROP TABLE statistiche_settimanali;
DROP TABLE stat_giorni_contenuti;
DROP TABLE statistiche_giornaliere;
DROP TABLE stat_orarie_contenuti;
DROP TABLE statistiche_orarie;
DROP TABLE statistiche;
DROP SEQUENCE seq_stat_mensili_contenuti;
DROP SEQUENCE seq_statistiche_mensili;
DROP SEQUENCE seq_stat_settimane_contenuti;
DROP SEQUENCE seq_statistiche_settimanali;
DROP SEQUENCE seq_stat_giorni_contenuti;
DROP SEQUENCE seq_statistiche_giornaliere;
DROP SEQUENCE seq_stat_orarie_contenuti;
DROP SEQUENCE seq_statistiche_orarie;
