<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
				  xmlns:tns="http://www.openspcoop2.org/core/diagnostica/management" 
				  xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/"
				  name="MessaggioDiagnosticoService"
				  targetNamespace="http://www.openspcoop2.org/core/diagnostica/management">

	<wsdl:import namespace="http://www.openspcoop2.org/core/diagnostica/management" 
				 location="MessaggioDiagnosticoSearch.wsdl"/>
	
	<!-- BINDING (SOAP11) --> 
	
	<wsdl:binding name="MessaggioDiagnosticoServiceSoap11Binding" type="tns:MessaggioDiagnostico">
		<soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsdl:operation name="findAll">
			<soap11:operation soapAction="findAll" style="document"/>
			<wsdl:input name="findAll">
				<soap11:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="findAllResponse">
				<soap11:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="diagnostica-service-exception">
				<soap11:fault name="diagnostica-service-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="diagnostica-not-implemented-exception">
				<soap11:fault name="diagnostica-not-implemented-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="diagnostica-not-authorized-exception">
				<soap11:fault name="diagnostica-not-authorized-exception" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>


		<wsdl:operation name="count">
			<soap11:operation soapAction="count" style="document"/>
			<wsdl:input name="count">
				<soap11:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="countResponse">
				<soap11:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="diagnostica-service-exception">
				<soap11:fault name="diagnostica-service-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="diagnostica-not-implemented-exception">
				<soap11:fault name="diagnostica-not-implemented-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="diagnostica-not-authorized-exception">
				<soap11:fault name="diagnostica-not-authorized-exception" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>


	</wsdl:binding>

	<!-- SERVICE -->	
	<wsdl:service name="MessaggioDiagnosticoSoap11Service">	

		<wsdl:port binding="tns:MessaggioDiagnosticoServiceSoap11Binding" name="MessaggioDiagnosticoPortSoap11">
			<soap11:address location="http://localhost:8080/diagnostica/MessaggioDiagnostico/Soap11"/>
		</wsdl:port>	
			
	</wsdl:service>
	
</wsdl:definitions>
