
package org.openspcoop2.core.tracciamento.ws.client.traccia.search;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-03-26T15:02:32.958+02:00
 * Generated source version: 3.1.7
 * 
 */
public final class Traccia_TracciaPortSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.openspcoop2.org/core/tracciamento/management", "TracciaSoap11Service");

    private Traccia_TracciaPortSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TracciaSoap11Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TracciaSoap11Service ss = new TracciaSoap11Service(wsdlURL, Traccia_TracciaPortSoap11_Client.SERVICE_NAME);
        Traccia port = ss.getTracciaPortSoap11();
	
		new org.openspcoop2.core.tracciamento.ws.client.utils.RequestContextUtils("traccia.soap11").addRequestContextParameters((javax.xml.ws.BindingProvider)port);  
        
        {
        System.out.println("Invoking findAll...");
        org.openspcoop2.core.tracciamento.ws.client.traccia.search.SearchFilterTraccia _findAll_filter = null;
        try {
            java.util.List<org.openspcoop2.core.tracciamento.Traccia> _findAll__return = port.findAll(_findAll_filter);
            System.out.println("findAll.result=" + _findAll__return);

        } catch (TracciamentoServiceException_Exception e) { 
            System.out.println("Expected exception: tracciamento-service-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotImplementedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-implemented-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotAuthorizedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-authorized-exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking count...");
        org.openspcoop2.core.tracciamento.ws.client.traccia.search.SearchFilterTraccia _count_filter = null;
        try {
            long _count__return = port.count(_count_filter);
            System.out.println("count.result=" + _count__return);

        } catch (TracciamentoServiceException_Exception e) { 
            System.out.println("Expected exception: tracciamento-service-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotImplementedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-implemented-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotAuthorizedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-authorized-exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking exists...");
        org.openspcoop2.core.tracciamento.IdTraccia _exists_idTraccia = new org.openspcoop2.core.tracciamento.IdTraccia();
        try {
            boolean _exists__return = port.exists(_exists_idTraccia);
            System.out.println("exists.result=" + _exists__return);

        } catch (TracciamentoServiceException_Exception e) { 
            System.out.println("Expected exception: tracciamento-service-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotImplementedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-implemented-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoMultipleResultException_Exception e) { 
            System.out.println("Expected exception: tracciamento-multiple-result-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotAuthorizedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-authorized-exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findAllIds...");
        org.openspcoop2.core.tracciamento.ws.client.traccia.search.SearchFilterTraccia _findAllIds_filter = null;
        try {
            java.util.List<org.openspcoop2.core.tracciamento.IdTraccia> _findAllIds__return = port.findAllIds(_findAllIds_filter);
            System.out.println("findAllIds.result=" + _findAllIds__return);

        } catch (TracciamentoServiceException_Exception e) { 
            System.out.println("Expected exception: tracciamento-service-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotImplementedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-implemented-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotAuthorizedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-authorized-exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking find...");
        org.openspcoop2.core.tracciamento.ws.client.traccia.search.SearchFilterTraccia _find_filter = null;
        try {
            org.openspcoop2.core.tracciamento.Traccia _find__return = port.find(_find_filter);
            System.out.println("find.result=" + _find__return);

        } catch (TracciamentoServiceException_Exception e) { 
            System.out.println("Expected exception: tracciamento-service-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotImplementedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-implemented-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoMultipleResultException_Exception e) { 
            System.out.println("Expected exception: tracciamento-multiple-result-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotFoundException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-found-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotAuthorizedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-authorized-exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking get...");
        org.openspcoop2.core.tracciamento.IdTraccia _get_idTraccia = new org.openspcoop2.core.tracciamento.IdTraccia();
        try {
            org.openspcoop2.core.tracciamento.Traccia _get__return = port.get(_get_idTraccia);
            System.out.println("get.result=" + _get__return);

        } catch (TracciamentoServiceException_Exception e) { 
            System.out.println("Expected exception: tracciamento-service-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotImplementedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-implemented-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoMultipleResultException_Exception e) { 
            System.out.println("Expected exception: tracciamento-multiple-result-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotFoundException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-found-exception has occurred.");
            System.out.println(e.toString());
        } catch (TracciamentoNotAuthorizedException_Exception e) { 
            System.out.println("Expected exception: tracciamento-not-authorized-exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
