/*
 * GovWay - A customizable API Gateway 
 * https://govway.org
 * 
 * Copyright (c) 2005-2020 Link.it srl (https://link.it). 
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.openspcoop2.web.ctrlstat.servlet.pd;

import java.util.Vector;

import org.openspcoop2.core.commons.ModalitaIdentificazione;
import org.openspcoop2.core.config.constants.CostantiConfigurazione;
import org.openspcoop2.core.config.constants.PortaDelegataAzioneIdentificazione;
import org.openspcoop2.core.config.constants.TipoAutenticazione;
import org.openspcoop2.core.config.constants.TipoAutorizzazione;
import org.openspcoop2.web.ctrlstat.costanti.CostantiControlStation;
import org.openspcoop2.web.ctrlstat.servlet.config.ConfigurazioneCostanti;
import org.openspcoop2.web.ctrlstat.servlet.connettori.ConnettoriCostanti;
import org.openspcoop2.web.lib.mvc.ForwardParams;

/**
 * PorteDelegateCostanti
 *
 * @author Poli Andrea (apoli@link.it)
 * @author $Author$
 * @version $Rev$, $Date$
 */
public class PorteDelegateCostanti {

	/* OBJECT NAME */

	public final static String OBJECT_NAME_PORTE_DELEGATE = "porteDelegate";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY = "porteDelegateWS";
	public final static ForwardParams TIPO_OPERAZIONE_MESSAGE_SECURITY = ForwardParams.OTHER("");
	public final static String OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST = "porteDelegateWSRequest";
	public final static String OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE = "porteDelegateWSResponse";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO = "porteDelegateServizioApplicativo";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_RUOLI = "porteDelegateRuoli";
	public final static String OBJECT_NAME_PORTE_DELEGATE_SCOPE = "porteDelegateScope";
	public final static String OBJECT_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES = "porteDelegateAutheCustomProperties";
	public final static String OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES = "porteDelegateAuthCustomProperties";
	public final static String OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES = "porteDelegateAuthContenutiCustomProperties";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA = "porteDelegateCorrelazioneApplicativa";
	public final static ForwardParams TIPO_OPERAZIONE_CORRELAZIONE_APPLICATIVA = ForwardParams.OTHER("");
	public final static String OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST = "porteDelegateCorrelazioneApplicativaRequest";
	public final static String OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE = "porteDelegateCorrelazioneApplicativaResponse";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO = "porteDelegateProprietaProtocollo";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_MTOM = "porteDelegateMTOM";
	public final static ForwardParams TIPO_OPERAZIONE_MTOM = ForwardParams.OTHER("");
	public final static String OBJECT_NAME_PORTE_DELEGATE_MTOM_REQUEST = "porteDelegateMTOMRequest";
	public final static String OBJECT_NAME_PORTE_DELEGATE_MTOM_RESPONSE = "porteDelegateMTOMResponse";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_EXTENDED = "porteDelegateExtended";

	public final static String OBJECT_NAME_PORTE_DELEGATE_CONTROLLO_ACCESSI = "porteDelegateControlloAccessi";
	public final static ForwardParams TIPO_OPERAZIONE_CONTROLLO_ACCESSI = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_AZIONE = "porteDelegateAzione";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_VALIDAZIONE_CONTENUTI = "porteDelegateValidazioneContenuti";
	public final static ForwardParams TIPO_OPERAZIONE_VALIDAZIONE_CONTENUTI = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_ABILITAZIONE = "porteDelegateAbilitazione";
	public final static ForwardParams TIPO_OPERAZIONE_ABILITAZIONE = ForwardParams.OTHER("");
	public final static ForwardParams TIPO_OPERAZIONE_CONFIGURAZIONE = ForwardParams.OTHER("Configurazione");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_CONNETTORE_DEFAULT = "porteDelegateConnettoreDefault";
	public final static ForwardParams TIPO_OPERAZIONE_CONNETTORE_DEFAULT = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_CONNETTORE_RIDEFINITO = "porteDelegateConnettoreRidefinito";
	public final static ForwardParams TIPO_OPERAZIONE_CONNETTORE_RIDEFINITO = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_DUMP_CONFIGURAZIONE = "porteDelegateDumpConfigurazione";
	public final static ForwardParams TIPO_OPERAZIONE_DUMP_CONFIGURAZIONE = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_PROPERTIES_CONFIG = "porteDelegateWSRequestPropertiesConfig";
	public final static ForwardParams TIPO_OPERAZIONE_MESSAGE_SECURITY_REQUEST_PROPERTIES_CONFIG = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_PROPERTIES_CONFIG = "porteDelegateWSResponsePropertiesConfig";
	public final static ForwardParams TIPO_OPERAZIONE_MESSAGE_SECURITY_RESPONSE_PROPERTIES_CONFIG = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_CONFIGURAZIONE_CHANGE = "porteDelegateConfigurazioneChange";
	public final static ForwardParams TIPO_OPERAZIONEGRUPPO_CAMBIA_NOME = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_GESTIONE_CORS = "porteDelegateGestioneCors";
	public final static ForwardParams TIPO_OPERAZIONE_GESTIONE_CORS = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_GESTIONE_CANALE = "porteDelegateGestioneCanale";
	public final static ForwardParams TIPO_OPERAZIONE_GESTIONE_CANALE = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_VERIFICA_CONNETTORE = "porteDelegateVerificaConnettore";
	public final static ForwardParams TIPO_OPERAZIONE_VERIFICA_CONNETTORE = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_RESPONSE_CACHING = "porteDelegateResponseCaching";
	public final static ForwardParams TIPO_OPERAZIONE_RESPONSE_CACHING = ForwardParams.OTHER("");
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA = "porteDelegateResponseCachingConfigurazioneRegola";
	
	public final static String OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI = "porteDelegateTrasformazioni";
	public final static String OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA = "porteDelegateTrasformazioniRichiesta";
	public final static String OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER = "porteDelegateTrasformazioniRichiestaHeader";
	public final static String OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO = "porteDelegateTrasformazioniRichiestaUrlParameter";
	public final static ForwardParams TIPO_OPERAZIONE_TRASFORMAZIONI_RICHIESTA = ForwardParams.OTHER("");
	public final static String OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA = "porteDelegateTrasformazioniRisposta";
	public final static String OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER = "porteDelegateTrasformazioniRispostaHeader";
	public final static String OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO = "porteDelegateTrasformazioniServizioApplicativo";

	/* SERVLET NAME */

	public final static String SERVLET_NAME_PORTE_DELEGATE_ADD = OBJECT_NAME_PORTE_DELEGATE+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CHANGE = OBJECT_NAME_PORTE_DELEGATE+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_DELETE = OBJECT_NAME_PORTE_DELEGATE+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_LIST = OBJECT_NAME_PORTE_DELEGATE+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_LIST);
	}


	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY+".do";

	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_ADD = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_CHANGE = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_DELETE = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_LIST = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_LIST);
	}

	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_ADD = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_CHANGE = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_DELETE = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_LIST = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_LIST);
	}

	public final static String SERVLET_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_ADD = OBJECT_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_DELETE = OBJECT_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_LIST = OBJECT_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_SERVIZIO_APPLICATIVO = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE_SERVIZIO_APPLICATIVO.add(SERVLET_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_ADD);
		SERVLET_PORTE_DELEGATE_SERVIZIO_APPLICATIVO.add(SERVLET_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_DELETE);
		SERVLET_PORTE_DELEGATE_SERVIZIO_APPLICATIVO.add(SERVLET_NAME_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_RUOLI_ADD = OBJECT_NAME_PORTE_DELEGATE_RUOLI+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_RUOLI_DELETE = OBJECT_NAME_PORTE_DELEGATE_RUOLI+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_RUOLI_LIST = OBJECT_NAME_PORTE_DELEGATE_RUOLI+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_RUOLI = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE_RUOLI.add(SERVLET_NAME_PORTE_DELEGATE_RUOLI_ADD);
		SERVLET_PORTE_DELEGATE_RUOLI.add(SERVLET_NAME_PORTE_DELEGATE_RUOLI_DELETE);
		SERVLET_PORTE_DELEGATE_RUOLI.add(SERVLET_NAME_PORTE_DELEGATE_RUOLI_LIST);
	}

	public final static String SERVLET_NAME_PORTE_DELEGATE_SCOPE_ADD = OBJECT_NAME_PORTE_DELEGATE_SCOPE+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_SCOPE_DELETE = OBJECT_NAME_PORTE_DELEGATE_SCOPE+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_SCOPE_LIST = OBJECT_NAME_PORTE_DELEGATE_SCOPE+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_SCOPE = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE_SCOPE.add(SERVLET_NAME_PORTE_DELEGATE_SCOPE_ADD);
		SERVLET_PORTE_DELEGATE_SCOPE.add(SERVLET_NAME_PORTE_DELEGATE_SCOPE_DELETE);
		SERVLET_PORTE_DELEGATE_SCOPE.add(SERVLET_NAME_PORTE_DELEGATE_SCOPE_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES_ADD = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES_DELETE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES_LIST = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES = new Vector<String>();
	static{
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES_ADD);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES_DELETE);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTENTICAZIONE_CUSTOM_PROPERTIES_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES_ADD = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES_DELETE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES_LIST = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES = new Vector<String>();
	static{
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES_ADD);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES_DELETE);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CUSTOM_PROPERTIES_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES_ADD = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES_DELETE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES_LIST = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES = new Vector<String>();
	static{
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES_ADD);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES_DELETE);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_CUSTOM_PROPERTIES_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA+".do";
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_ADD = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_CHANGE = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_DELETE = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_LIST = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_REQUEST_LIST);
	}

	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_ADD = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_CHANGE = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_DELETE = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_LIST = OBJECT_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RESPONSE_LIST);
	}


	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM = OBJECT_NAME_PORTE_DELEGATE_MTOM+".do";

	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_ADD = OBJECT_NAME_PORTE_DELEGATE_MTOM_REQUEST+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_CHANGE = OBJECT_NAME_PORTE_DELEGATE_MTOM_REQUEST+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_DELETE = OBJECT_NAME_PORTE_DELEGATE_MTOM_REQUEST+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_LIST = OBJECT_NAME_PORTE_DELEGATE_MTOM_REQUEST+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_MTOM_REQUEST = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_REQUEST_LIST);
	}

	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_ADD = OBJECT_NAME_PORTE_DELEGATE_MTOM_RESPONSE+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_CHANGE = OBJECT_NAME_PORTE_DELEGATE_MTOM_RESPONSE+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_DELETE = OBJECT_NAME_PORTE_DELEGATE_MTOM_RESPONSE+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_LIST = OBJECT_NAME_PORTE_DELEGATE_MTOM_RESPONSE+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_MTOM_RESPONSE = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_MTOM_RESPONSE_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_EXTENDED_ADD = OBJECT_NAME_PORTE_DELEGATE_EXTENDED+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_EXTENDED_CHANGE = OBJECT_NAME_PORTE_DELEGATE_EXTENDED+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_EXTENDED_DELETE = OBJECT_NAME_PORTE_DELEGATE_EXTENDED+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_EXTENDED_LIST = OBJECT_NAME_PORTE_DELEGATE_EXTENDED+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_EXTENDED = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_EXTENDED_ADD);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_EXTENDED_CHANGE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_EXTENDED_DELETE);
		SERVLET_PORTE_DELEGATE.add(SERVLET_NAME_PORTE_DELEGATE_EXTENDED_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_CONTROLLO_ACCESSI = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_CONTROLLO_ACCESSI+".do";
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_AZIONE_ADD = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AZIONE+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AZIONE_DELETE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AZIONE+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_AZIONE_LIST = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_AZIONE+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_AZIONE = new Vector<String>();
	
	static{
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AZIONE.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AZIONE_ADD);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AZIONE.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AZIONE_DELETE);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_AZIONE.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_AZIONE_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_VALIDAZIONE_CONTENUTI = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_VALIDAZIONE_CONTENUTI+".do";
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_ABILITAZIONE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_ABILITAZIONE+".do";
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_ADD = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_CHANGE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_DELETE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_LIST = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO = new Vector<String>();
	static{
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_ADD);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_CHANGE);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_DELETE);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_PROPRIETA_PROTOCOLLO_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_CONNETTORE_DEFAULT = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_CONNETTORE_DEFAULT +".do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_CONNETTORE_RIDEFINITO = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_CONNETTORE_RIDEFINITO +".do";
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_DUMP_CONFIGURAZIONE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_DUMP_CONFIGURAZIONE+".do"; 
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_PROPERTIES_CONFIG = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_PROPERTIES_CONFIG+".do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_PROPERTIES_CONFIG = OBJECT_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_PROPERTIES_CONFIG+".do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_MESSAGE_SECURITY_PROPERTIES_CONFIG = new Vector<String>();
	static{
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_MESSAGE_SECURITY_PROPERTIES_CONFIG.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_PROPERTIES_CONFIG);
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_MESSAGE_SECURITY_PROPERTIES_CONFIG.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_PROPERTIES_CONFIG);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_CONFIGURAZIONE_CHANGE = OBJECT_NAME_PORTE_DELEGATE_CONFIGURAZIONE_CHANGE+".do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_CONFIGURAZIONE_CHANGE = new Vector<String>();
	static{
		PorteDelegateCostanti.SERVLET_PORTE_DELEGATE_CONFIGURAZIONE_CHANGE.add(PorteDelegateCostanti.SERVLET_NAME_PORTE_DELEGATE_CONFIGURAZIONE_CHANGE);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_GESTIONE_CORS = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_GESTIONE_CORS +".do";
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_GESTIONE_CANALE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_GESTIONE_CANALE +".do"; 
		
	public final static String SERVLET_NAME_PORTE_DELEGATE_VERIFICA_CONNETTORE = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_VERIFICA_CONNETTORE+".do"; 
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_RESPONSE_CACHING = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_RESPONSE_CACHING +".do"; 
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_ADD = OBJECT_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_DELETE = OBJECT_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_LIST = OBJECT_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA+"List.do";
	public final static Vector<String> SERVLET_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA.add(SERVLET_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_ADD);
		SERVLET_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA.add(SERVLET_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_DELETE);
		SERVLET_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA.add(SERVLET_NAME_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_LIST);
	}
	
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_ADD = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_CHANGE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_DELETE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_LIST = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI+"List.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA = PorteDelegateCostanti.OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA +".do"; 
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_ADD = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CHANGE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_DELETE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_LIST = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA+"List.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_ADD = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_CHANGE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_DELETE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_LIST = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER+"List.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_ADD = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_CHANGE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_DELETE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_LIST = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER+"List.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_ADD = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_CHANGE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO+"Change.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_DELETE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_LIST = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO+"List.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_ADD = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO+"Add.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_DELETE = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO+"Del.do";
	public final static String SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_LIST = OBJECT_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO+"List.do";
	
	public final static Vector<String> SERVLET_PORTE_DELEGATE_TRASFORMAZIONI = new Vector<String>();
	static{
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_ADD);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_CHANGE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_DELETE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_LIST);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_ADD);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CHANGE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_DELETE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_LIST);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_ADD);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_CHANGE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_DELETE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_LIST);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_ADD);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_CHANGE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_DELETE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_LIST);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_ADD);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_CHANGE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_DELETE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_LIST);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_ADD);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_DELETE);
		SERVLET_PORTE_DELEGATE_TRASFORMAZIONI.add(SERVLET_NAME_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_LIST);
	}
	
	/* LABEL GENERALI */

	public final static String LABEL_PORTE_DELEGATE = "Porte Delegate";

	public final static String LABEL_PD_MENU_VISUALE_AGGREGATA = "Porte Delegate";
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SOGGETTO = "Soggetto";
	
	public final static String LABEL_PARAMETRO_TITOLO_PORTE_DELEGATE_DATI_INVOCAZIONE = "URL Invocazione";
	public final static String LABEL_PARAMETRO_TITOLO_PORTE_DELEGATE_DATI_GENERALI = "Dati Generali";
	public final static String LABEL_PARAMETRO_TITOLO_PORTE_DELEGATE_DATI_SERVIZIO = "Dati Servizio";
	public final static String LABEL_COLUMN_PORTE_DELEGATE_STATO_PORTA = "Abilitato";
	

	/* PARAMETRI */

	public final static String PARAMETRO_PORTE_DELEGATE_ID = CostantiControlStation.PARAMETRO_ID;
	public final static String PARAMETRO_PORTE_DELEGATE_STATO_PORTA = "statoPorta";
	public final static String PARAMETRO_PORTE_DELEGATE_NOME_PORTA = "nomePorta";
	public final static String PARAMETRO_PORTE_DELEGATE_ID_SOGGETTO = CostantiControlStation.PARAMETRO_ID_SOGGETTO;
	public final static String PARAMETRO_PORTE_DELEGATE_ID_ASPS = CostantiControlStation.PARAMETRO_ID_ASPS;
	public final static String PARAMETRO_PORTE_DELEGATE_ID_FRUIZIONE = CostantiControlStation.PARAMETRO_ID_FRUIZIONE;
	public final static String PARAMETRO_PORTE_DELEGATE_PROVIDER = "provider";
	public final static String PARAMETRO_PORTE_DELEGATE_ID_CORRELAZIONE = "idcorr";
	public final static String PARAMETRO_PORTE_DELEGATE_TIPO_SOGGETTO = "tipoprov";
	public final static String PARAMETRO_PORTE_DELEGATE_NOME_SOGGETTO = "nomeprov";
	public final static String PARAMETRO_PORTE_DELEGATE_DESCRIZIONE = "descr";
	public final static String PARAMETRO_PORTE_DELEGATE_TIPO_SERVIZIO = "tiposervizio";
	public final static String PARAMETRO_PORTE_DELEGATE_SERVIZIO = "servizio";
	public final static String PARAMETRO_PORTE_DELEGATE_VERSIONE_SERVIZIO = "versioneservizio";
	public final static String PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI = CostantiControlStation.PARAMETRO_AUTORIZZAZIONE_CONTENUTI;
	public final static String PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_STATO = CostantiControlStation.PARAMETRO_AUTORIZZAZIONE_CONTENUTI_STATO;
	public final static String PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTI_PROPERTIES = CostantiControlStation.PARAMETRO_AUTORIZZAZIONE_CONTENUTI_PROPERTIES;
	public final static String PARAMETRO_PORTE_DELEGATE_TIPO_VALIDAZIONE = CostantiControlStation.PARAMETRO_PORTE_TIPO_VALIDAZIONE;
	public final static String PARAMETRO_PORTE_DELEGATE_XSD = CostantiControlStation.PARAMETRO_PORTE_XSD;
	public final static String PARAMETRO_PORTE_DELEGATE_GESTIONE_MANIFEST = "gestManifest";
	public final static String PARAMETRO_PORTE_DELEGATE_GESTIONE_BODY = "gestBody";
	public final static String PARAMETRO_PORTE_DELEGATE_LOCAL_FORWARD = "localForward";
	public final static String PARAMETRO_PORTE_DELEGATE_LOCAL_FORWARD_PA = "localForwardPA";
	public final static String PARAMETRO_PORTE_DELEGATE_STATELESS = "stateless";
	public final static String PARAMETRO_PORTE_DELEGATE_AZIONE = CostantiControlStation.PARAMETRO_AZIONE;
	public final static String PARAMETRO_PORTE_DELEGATE_AZIONI = CostantiControlStation.PARAMETRO_AZIONI;
	public final static String PARAMETRO_PORTE_DELEGATE_NOME_GRUPPO = CostantiControlStation.PARAMETRO_NOME_GRUPPO;
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_AZIONE = "modeaz";
	public final static String PARAMETRO_PORTE_DELEGATE_AZIONE_ID = "azid";
	public final static String PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_SIMMETRICA = "ricsim";
	public final static String PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_ASIMMETRICA = "ricasim";
	public final static String PARAMETRO_PORTE_DELEGATE_SOGGETTO_ID = "soggid";
	public final static String PARAMETRO_PORTE_DELEGATE_SERVIZIO_ID = "servid";
	public final static String PARAMETRO_PORTE_DELEGATE_SP = "sp";
	public final static String PARAMETRO_PORTE_DELEGATE_TIPO_SP = "tiposp";
	public final static String PARAMETRO_PORTE_DELEGATE_SCADENZA_CORRELAZIONE_APPLICATIVA = CostantiControlStation.PARAMETRO_SCADENZA_CORRELAZIONE_APPLICATIVA;
	public final static String PARAMETRO_PORTE_DELEGATE_INTEGRAZIONE = "integrazione";
	public final static String PARAMETRO_PORTE_DELEGATE_NOME = "nome";
	public final static String PARAMETRO_PORTE_DELEGATE_OLD_NOME_PD = "oldNomePD";
	public final static String PARAMETRO_PORTE_DELEGATE_SERVIZIO_APPLICATIVO = "servizioApplicativo";
	public final static String PARAMETRO_PORTE_DELEGATE_MODE = CostantiControlStation.PARAMETRO_MODE_CORRELAZIONE_APPLICATIVA;
	public final static String PARAMETRO_PORTE_DELEGATE_ELEMENTO_XML = CostantiControlStation.PARAMETRO_ELEMENTO_XML;
	public final static String PARAMETRO_PORTE_DELEGATE_GESTIONE_IDENTIFICAZIONE_FALLITA = "gif";
	public final static String PARAMETRO_PORTE_DELEGATE_PATTERN = CostantiControlStation.PARAMETRO_PATTERN;
	public final static String PARAMETRO_PORTE_DELEGATE_RIUSO_ID_MESSAGGIO = "riusoIdMessaggio";
	public final static String PARAMETRO_PORTE_DELEGATE_VALORE = "valore";
	public final static String PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY = "messageSecurity";
	public final static String PARAMETRO_PORTE_DELEGATE_FORCE_INTERFACE_BASED = "forceInterfaceBased";
	public final static String PARAMETRO_PORTE_DELEGATE_LIST_AZIONI_READ_ONLY = "listAzioniReadOnly";
    
	public final static String PARAMETRO_PORTE_DELEGATE_GESTIONE_MESSAGE_ENGINE = "gestMessageEngine";
    
	public final static String PARAMETRO_PORTE_DELEGATE_IDENTIFICAZIONE = "identificazione";
	public final static String PARAMETRO_PORTE_DELEGATE_NOME_PORTA_DELEGANTE = "nomePortaDelegante";
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_CREAZIONE = "modeCreazione";
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_CREAZIONE_CONNETTORE = "modeCreazioneConnettore";
	public final static String PARAMETRO_PORTE_DELEGATE_MAPPING = "mapping";
	public final static String PARAMETRO_PORTE_DELEGATE_SERVICE_BINDING = CostantiControlStation.PARAMETRO_SERVICE_BINDING;
	
	public final static String PARAMETRO_PORTE_DELEGATE_CONFIGURAZIONE_DATI_INVOCAZIONE = "configurazioneDatiInvocazione";
	public final static String PARAMETRO_PORTE_DELEGATE_CONFIGURAZIONE_ALTRO_PORTA = "configurazioneAltroPorta";
	public final static String PARAMETRO_PORTE_DELEGATE_CONFIGURAZIONE_ALTRO_API = "configurazioneAltroApi";
	public final static String PARAMETRO_PORTE_DELEGATE_CONNETTORE_DA_LISTA_APS = "connettoreDaListaAps";
	
	public final static String PARAMETRO_PORTE_DELEGATE_MTOM_RICHIESTA = CostantiControlStation.PARAMETRO_MTOM_RICHIESTA;
	public final static String PARAMETRO_PORTE_DELEGATE_MTOM_RISPOSTA = CostantiControlStation.PARAMETRO_MTOM_RISPOSTA;
	
	public final static String PARAMETRO_PORTE_DELEGATE_OBBLIGATORIO = CostantiControlStation.PARAMETRO_OBBLIGATORIO;
	public final static String PARAMETRO_PORTE_DELEGATE_CONTENT_TYPE = CostantiControlStation.PARAMETRO_CONTENT_TYPE;
	
	public final static String PARAMETRO_PORTE_DELEGATE_APPLICA_MTOM_RICHIESTA = CostantiControlStation.PARAMETRO_APPLICA_MTOM_RICHIESTA;
	public final static String PARAMETRO_PORTE_DELEGATE_APPLICA_MTOM_RISPOSTA = CostantiControlStation.PARAMETRO_APPLICA_MTOM_RISPOSTA;
	public final static String PARAMETRO_PORTE_DELEGATE_APPLICA_MTOM = CostantiControlStation.PARAMETRO_PORTE_APPLICA_MTOM;

	public final static String PARAMETRO_PORTE_DELEGATE_APPLICA_MODIFICA = CostantiControlStation.PARAMETRO_APPLICA_MODIFICA;
	public final static String PARAMETRO_PORTE_DELEGATE_ABILITA = CostantiControlStation.PARAMETRO_ABILITA;
	
	public final static String ATTRIBUTO_PORTE_DELEGATE_PARENT = CostantiControlStation.ATTRIBUTO_CONFIGURAZIONE_PARENT;
	public final static int ATTRIBUTO_PORTE_DELEGATE_PARENT_NONE = CostantiControlStation.ATTRIBUTO_CONFIGURAZIONE_PARENT_NONE;
	public final static int ATTRIBUTO_PORTE_DELEGATE_PARENT_SOGGETTO = CostantiControlStation.ATTRIBUTO_CONFIGURAZIONE_PARENT_SOGGETTO;
	public final static int ATTRIBUTO_PORTE_DELEGATE_PARENT_CONFIGURAZIONE = CostantiControlStation.ATTRIBUTO_CONFIGURAZIONE_PARENT_CONFIGURAZIONE;
	
	public final static String PARAMETRO_PORTE_DELEGATE_MODALITA_CONNETTORE = ConnettoriCostanti.PARAMETRO_CONNETTORE_MODALITA;
	public final static String PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_PROPERTIES_CONFIG_NAME = CostantiControlStation.PARAMETRO_REQUEST_FLOW_PROPERTIES_CONFIG_NAME;
	public final static String PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_PROPERTIES_CONFIG_NAME = CostantiControlStation.PARAMETRO_RESPONSE_FLOW_PROPERTIES_CONFIG_NAME;
	public final static String PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_PROPERTIES_CONFIG_NAME = CostantiControlStation.PARAMETRO_PROPERTIES_CONFIG_NAME;
	
	public final static String PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MIN = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MIN;
	public final static String PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MAX = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MAX;
	public final static String PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE;
	public final static String PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_FAULT = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_FAULT;
	public final static String PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_CACHE_TIMEOUT_SECONDS = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_CACHE_TIMEOUT_SECONDS;

	public final static String PARAMETRO_PORTE_DELEGATE_ID_TRASFORMAZIONE = CostantiControlStation.PARAMETRO_ID_CONFIGURAZIONE_TRASFORMAZIONE;
	public final static String PARAMETRO_PORTE_DELEGATE_ID_TRASFORMAZIONE_RISPOSTA = CostantiControlStation.PARAMETRO_ID_CONFIGURAZIONE_TRASFORMAZIONE_RISPOSTA;
	public final static String PARAMETRO_PORTE_DELEGATE_ID_TRASFORMAZIONE_RICHIESTA_HEADER = CostantiControlStation.PARAMETRO_ID_CONFIGURAZIONE_TRASFORMAZIONE_RICHIESTA_HEADER;
	public final static String PARAMETRO_PORTE_DELEGATE_ID_TRASFORMAZIONE_RICHIESTA_PARAMETRO = CostantiControlStation.PARAMETRO_ID_CONFIGURAZIONE_TRASFORMAZIONE_RICHIESTA_PARAMETRO;
	public final static String PARAMETRO_PORTE_DELEGATE_ID_TRASFORMAZIONE_RISPOSTA_HEADER = CostantiControlStation.PARAMETRO_ID_CONFIGURAZIONE_TRASFORMAZIONE_RISPOSTA_HEADER;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_FIRST = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_FIRST;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_NOME = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_NOME;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_STATO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_STATO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_AZIONI_ALL = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_AZIONI_ALL;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_AZIONI = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_AZIONI;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_CT = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_CT;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_PATTERN = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_PATTERN;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_LIST = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_LIST;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONVERSIONE_ENABLED = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONVERSIONE_ENABLED;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONVERSIONE_TIPO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONVERSIONE_TIPO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONVERSIONE_TEMPLATE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONVERSIONE_TEMPLATE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONTENT_TYPE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONTENT_TYPE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REST_TRANSFORMATION = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REST_TRANSFORMATION;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REST_METHOD = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REST_METHOD;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REST_PATH = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REST_PATH;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_TRANSFORMATION = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_TRANSFORMATION;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_VERSION = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_VERSION;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ACTION = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ACTION;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE;
//	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE_AS_ATTACH = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE_AS_ATTACH;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE_TIPO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE_TIPO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE_TEMPLATE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE_TEMPLATE;
	
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_NOME = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_NOME;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MIN = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MIN;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MAX = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MAX;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_CT = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_CT;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_PATTERN = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_PATTERN;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_ENABLED = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_ENABLED;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TIPO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TIPO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TEMPLATE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TEMPLATE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONTENT_TYPE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONTENT_TYPE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_RETURN_CODE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_RETURN_CODE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_TRANSFORMATION = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_TRANSFORMATION;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_AS_ATTACH = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_AS_ATTACH;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TIPO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TIPO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TEMPLATE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TEMPLATE;
	
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_VALORE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADER_VALORE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_NOME = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADER_NOME;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_TIPO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADER_TIPO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_IDENTIFICAZIONE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADER_IDENTIFICAZIONE;
	
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_VALORE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER_VALORE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_NOME = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER_NOME;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_TIPO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER_TIPO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_IDENTIFICAZIONE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER_IDENTIFICAZIONE;
	
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_VALORE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_VALORE;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_NOME = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_NOME;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_TIPO = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_TIPO;
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_IDENTIFICAZIONE = CostantiControlStation.PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_IDENTIFICAZIONE;
	
	public final static String PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO = "servizioApplicativo";
	/* LABEL PARAMETRI */
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ID = "Id";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_STATO_PORTA = "Stato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ID_SOGGETTO = "IdSogg";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SOGGETTI = "Soggetti";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SOGGETTO_EROGATORE = "Soggetto Erogatore";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_PORTE_DELEGATE_DI = "Porte Delegate di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_APPLICATIVO_CONFIG_DI = "Applicativi di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_APPLICATIVO_CONFIG = "Applicativi";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_CONFIG_DI = "Servizi Applicativi di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SERVIZIO_APPLICATIVO_CONFIG = "Servizi Applicativi";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RUOLI_CONFIG_DI = "Ruoli di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RUOLI_CONFIG = "Ruoli";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SCOPE_CONFIG_DI = "Scope di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SCOPE_CONFIG = "Scope";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_AUTENTICAZIONE_PROPRIETA = "Propriet&agrave; Autenticazione";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_AUTENTICAZIONE_PROPRIETA_DI = "Propriet&agrave; Autenticazione di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE_PROPRIETA = "Propriet&agrave; Autorizzazione";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE_PROPRIETA_DI = "Propriet&agrave; Autorizzazione di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTO_PROPRIETA = "Propriet&agrave; Autorizzazione Contenuti";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE_CONTENUTO_PROPRIETA_DI = "Propriet&agrave; Autorizzazione Contenuti di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_CONFIG_DI = "Sicurezza Messaggio di ";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_DI = "Sicurezza Messaggio request-flow di ";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_DI = "Sicurezza Messaggio response-flow di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_DI = "Parametri della Richiesta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_DI = "Parametri della Risposta";	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_PROPERTIES_CONFIG = "Richiesta - Schema Sicurezza";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_PROPERTIES_CONFIG = "Risposta - Schema Sicurezza";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_CONFIG_DI = "Configurazione MTOM di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_CONFIG = "Configurazione MTOM";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_REQUEST_FLOW_DI = "MTOM request-flow di ";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_RESPONSE_FLOW_DI = "MTOM response-flow di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_REQUEST_FLOW_DI = "Parametri della Richiesta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_RESPONSE_FLOW_DI = "Parametri della Risposta";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_CONFIG_DI = "Correlazione Applicativa di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_CONFIG_DI = "Tracciamento di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRACCIAMENTO_CONFIG_DI = "Tracciamento di ";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_RICHIESTA_DI = "Correlazioni Applicative per la richiesta di ";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_RISPOSTA_DI = "Correlazioni Applicative per la risposta di ";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_RICHIESTA_DI = "Regole della Richiesta";
//	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_RISPOSTA_DI = "Regole della Risposta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_RICHIESTA_DI = "Correlazione Applicativa Richiesta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONI_APPLICATIVE_RISPOSTA_DI = "Correlazione Applicativa Risposta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONNETTORE_DEFAULT = "Connettore Default";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONNETTORE_DEFAULT_DI = "Connettore Default di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONNETTORE_RIDEFINITO = "Connettore Ridefinito";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONNETTORE_RIDEFINITO_DI = "Connettore Ridefinito di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_NOME = "Nome";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VALORE = "Valore";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TIPO = CostantiControlStation.LABEL_PARAMETRO_PORTE_TIPO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_URL_INVOCAZIONE = "URL";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_BASE_URL_INVOCAZIONE = "Base URL";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_DESCRIZIONE = "Descrizione";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VALIDAZIONE_CONTENUTI = CostantiControlStation.LABEL_PARAMETRO_PORTE_VALIDAZIONE_CONTENUTI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VALIDAZIONE_CONTENUTI_CONFIG_DI = CostantiControlStation.LABEL_PARAMETRO_PORTE_VALIDAZIONE_CONTENUTI_CONFIG_DI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TIPO_VALIDAZIONE = CostantiControlStation.LABEL_PARAMETRO_PORTE_TIPO_VALIDAZIONE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_INTEGRAZIONE = CostantiControlStation.LABEL_INTEGRAZIONE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_METADATI = CostantiControlStation.LABEL_METADATI;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_STATELESS = CostantiControlStation.LABEL_STATELESS;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_LOCAL_FORWARD = CostantiControlStation.LABEL_LOCAL_FORWARD;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_LOCAL_FORWARD_STATO = "Stato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_LOCAL_FORWARD_PA = CostantiControlStation.LABEL_LOCAL_FORWARD_PA;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SOAP_WITH_ATTACHMENTS = "SOAP With Attachments";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_GESTIONE_BODY = "Gestione Body";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_GESTIONE_MANIFEST = CostantiControlStation.LABEL_GESTIONE_MANIFEST;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_GESTIONE_ASINCRONA = "Gestione Asincrona";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_SIMMETRICA = CostantiControlStation.LABEL_RICEVUTA_ASINCRONA_SIMMETRICA;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_ASIMMETRICA = CostantiControlStation.LABEL_RICEVUTA_ASINCRONA_ASIMMETRICA;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ESPRESSIONE_REGOLARE = ModalitaIdentificazione.URL_BASED.getLabelParametro();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONTENT_PATTERN = ModalitaIdentificazione.CONTENT_BASED.getLabelParametro();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SERVIZIO = "Servizio";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TIPO_SERVIZIO = "Tipo";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_NOME_SERVIZIO = "Nome Servizio";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VERSIONE_SERVIZIO = "Versione Servizio";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONNETTORE = "Connettore";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VERIFICA_CONNETTORE = CostantiControlStation.LABEL_CONFIGURAZIONE_VERIFICA_CONNETTORE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONNETTORE_DI = "Connettore di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODALITA = "Modalit&agrave;";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONFIGURAZIONE = "Configurazione";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_OPZIONI_AVANZATE = "Opzioni Avanzate";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_OPZIONI_AVANZATE_DI = "Opzioni Avanzate di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODALITA_IDENTIFICAZIONE = "Modalit&agrave; identificazione";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ELEMENTO_XML = CostantiControlStation.LABEL_PARAMETRO_PORTE_ELEMENTO_XML;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ELEMENTO_XML_BR = CostantiControlStation.LABEL_PARAMETRO_PORTE_ELEMENTO_XML+"<BR/>(Il campo vuoto indica qualsiasi elemento)";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ELEMENTO_XML_NOTE = "Il campo vuoto indica qualsiasi elemento";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RISULTATI_RICERCA = "Risultati Ricerca";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY = "Sicurezza Messaggio";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_GESTIONE_MESSAGGIO = "Trattamento Messaggio";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM = "MTOM";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_BR_RICHIESTA = "Correlazione applicativa<BR/>Richiesta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_BR_RISPOSTA = "Correlazione applicativa<BR/>Risposta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RICHIESTA = "Identificazione Richiesta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_RISPOSTA = "Identificazione Risposta";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA = "Correlazione Applicativa";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRACCIAMENTO = ConfigurazioneCostanti.LABEL_CONFIGURAZIONE_TRACCIAMENTO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_ABILITATA = "abilitato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORRELAZIONE_APPLICATIVA_DISABILITATA = "disabilitato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_APPLICATIVI = "Applicativi";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SERVIZI_APPLICATIVI = "Servizi Applicativi";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RUOLI = "Ruoli";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SCOPE = "Scope";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_APPLICATIVO = "Applicativo";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_SERVIZIO_APPLICATIVO = "Servizio Applicativo";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_GESTIONE_IDENTIFICAZIONE_FALLITA = "Identificazione fallita";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RIUSO_ID_MESSAGGIO = "Riuso ID";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_STATO = CostantiControlStation.LABEL_PARAMETRO_PORTE_STATO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_FORCE_INTERFACE_BASED_LEFT = CostantiControlStation.LABEL_PARAMETRO_FORCE_INTERFACE_BASED_LEFT;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_FORCE_INTERFACE_BASED_RIGHT = CostantiControlStation.LABEL_PARAMETRO_FORCE_INTERFACE_BASED_RIGHT;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_PORTA_DELEGANTE = "Porta Delegante";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RICERCA_PORTA_AZIONE_DELEGATA = "Ricerca Azione Delegata";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODO_CREAZIONE_CONNETTORE = "Ridefinisci Connettore";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_ABILITATO = "abilitato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MTOM_DISABILITATO = "disabilitato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_APPLICA_MTOM = CostantiControlStation.LABEL_PARAMETRO_APPLICA_MTOM;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ACCETTA_MTOM = CostantiControlStation.LABEL_PARAMETRO_PORTE_ACCETTA_MTOM;

	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONTROLLO_ACCESSI = "Controllo Accessi";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CONTROLLO_ACCESSI_CONFIG_DI = "Controllo Accessi di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ABILITATO = "Abilitato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_DISABILITATO = "Disabilitato";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MAPPING_FRUIZIONE_PD_NOME_DEFAULT = "Default";
	//public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MAPPING_FRUIZIONE_PD_AZIONE_DEFAULT = "*";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MAPPING_FRUIZIONE_PD_AZIONE_DEFAULT = "default";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MAPPING_FRUIZIONE_PD_AZIONE_SPECIFIC_PREFIX = "Specific";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODO_CREAZIONE = "Modalità";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODO_CREAZIONE_EREDITA = "Eredita Da";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODO_CREAZIONE_NUOVA = "Nuova";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MAPPING_GRUPPO = "Gruppo";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_NOME_GRUPPO = CostantiControlStation.LABEL_PARAMETRO_PORTE_NOME_GRUPPO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_ELENCO_AZIONI_GRUPPI_PREFIX = "Elenco ";
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MESSAGE_ENGINE = "Message Engine";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_GESTIONE_MESSAGE_ENGINE = CostantiControlStation.LABEL_GESTIONE_MESSAGE_ENGINE;

	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODE_REGISTER_INPUT = ModalitaIdentificazione.REGISTER_BASED.getLabel();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODE_HEADER_BASED = ModalitaIdentificazione.HEADER_BASED.getLabel();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODE_URL_BASED = ModalitaIdentificazione.URL_BASED.getLabel();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODE_CONTENT_BASED = ModalitaIdentificazione.CONTENT_BASED.getLabel();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODE_INPUT_BASED = ModalitaIdentificazione.INPUT_BASED.getLabel();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODE_SOAP_ACTION_BASED = ModalitaIdentificazione.SOAP_ACTION_BASED.getLabel();
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODE_WSDL_BASED = ModalitaIdentificazione.INTERFACE_BASED.getLabel();

	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_PROTOCOL_PROPERTIES = "Propriet&agrave;";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_PROTOCOL_PROPERTIES_CONFIG_DI = "Propriet&agrave; di ";
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODALITA_CONNETTORE_RIDEFINITO = ConnettoriCostanti.LABEL_PARAMETRO_MODALITA_CONNETTORE_RIDEFINITO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_MODALITA_CONNETTORE_DEFAULT = ConnettoriCostanti.LABEL_PARAMETRO_MODALITA_CONNETTORE_DEFAULT;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_DUMP_CONFIGURAZIONE = CostantiControlStation.LABEL_REGISTRAZIONE_MESSAGGI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_DUMP_CONFIGURAZIONE_CONFIG_DI =  CostantiControlStation.LABEL_REGISTRAZIONE_MESSAGGI_CONFIG_DI;
	
	public final static String LABEL_PORTE_DELEGATE_ARCHIVIO_MESSAGGI_CON_SUCCESSO = CostantiControlStation.LABEL_REGISTRAZIONE_MESSAGGI_MODIFICATA_CON_SUCCESSO;
	
	public final static String LABEL_DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_PROPERTIES_CONFIG_NAME = CostantiControlStation.LABEL_CONFIGURAZIONE_PROPERTIES_CONFIGURAZIONE_MANUALE;
	public final static String LABEL_DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_PROPERTIES_CONFIG_NAME = CostantiControlStation.LABEL_CONFIGURAZIONE_PROPERTIES_CONFIGURAZIONE_MANUALE;
	
	public final static String LABEL_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_PROPERTIES_CONFIG_NAME_NESSUNO = CostantiControlStation.LABEL_NESSUNO;
	public final static String LABEL_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_PROPERTIES_CONFIG_NAME_NESSUNO = CostantiControlStation.LABEL_NESSUNO;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORS_CONFIGURAZIONE = CostantiControlStation.LABEL_CONFIGURAZIONE_CORS;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CORS_CONFIGURAZIONE_CONFIG_DI = CostantiControlStation.LABEL_CONFIGURAZIONE_CORS_DI;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CANALE = CostantiControlStation.LABEL_CONFIGURAZIONE_CANALE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_CANALE_CONFIG_DI = CostantiControlStation.LABEL_CONFIGURAZIONE_CANALE_DI;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VERIFICA_CONNETTORE_TITLE = CostantiControlStation.LABEL_CONFIGURAZIONE_VERIFICA_CONNETTORE_TITLE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VERIFICA_CONNETTORE_CONFIGURAZIONE = CostantiControlStation.LABEL_CONFIGURAZIONE_VERIFICA_CONNETTORE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_VERIFICA_CONNETTORE_CONFIGURAZIONE_CONFIG_DI = CostantiControlStation.LABEL_CONFIGURAZIONE_VERIFICA_CONNETTORE_DI;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE = CostantiControlStation.LABEL_CONFIGURAZIONE_RESPONSE_CACHING;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_CONFIG_DI = CostantiControlStation.LABEL_CONFIGURAZIONE_RESPONSE_CACHING_DI;
	
	public final static String LABEL_PORTE_DELEGATE_CORS_CON_SUCCESSO = CostantiControlStation.LABEL_GESTIONE_CORS_MODIFICATA_CON_SUCCESSO;
	public final static String LABEL_PORTE_DELEGATE_RESPONSE_CACHING_CON_SUCCESSO = CostantiControlStation.LABEL_GESTIONE_RESPONSE_CACHING_MODIFICATA_CON_SUCCESSO;
	public final static String LABEL_PORTE_DELEGATE_CANALE_CON_SUCCESSO = CostantiControlStation.LABEL_GESTIONE_CANALE_MODIFICATA_CON_SUCCESSO;
	
	public final static String LABEL_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLE = CostantiControlStation.LABEL_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLE;
	public final static String LABEL_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLE_DI = CostantiControlStation.LABEL_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLE_DI;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MIN = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MIN;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MAX = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE_MAX;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_RETURN_CODE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_FAULT = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_FAULT;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_CACHE_TIMEOUT_SECONDS = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_RESPONSE_CACHING_CONFIGURAZIONE_REGOLA_CACHE_TIMEOUT_SECONDS;

	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI = CostantiControlStation.LABEL_CONFIGURAZIONE_TRASFORMAZIONI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_DI = CostantiControlStation.LABEL_CONFIGURAZIONE_TRASFORMAZIONI_DI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA = CostantiControlStation.LABEL_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_TRASFORMAZIONE = CostantiControlStation.LABEL_CONFIGURAZIONE_TRASFORMAZIONI_TRASFORMAZIONE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER ;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADERS = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADERS ;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADERS_DI = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADERS_DI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO ;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRI = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRI ;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRI_DI = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRI_DI;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTE_DI = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTE_DI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADERS = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADERS ;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADERS_DI = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADERS_DI;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_POSIZIONE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_POSIZIONE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_NOME = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_NOME;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_STATO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_STATO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_AZIONI = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_AZIONI;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_CT = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_CT;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICABILITA_PATTERN = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_APPLICABILITA_PATTERN;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONVERSIONE_ENABLED = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONVERSIONE_ENABLED;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONVERSIONE_TIPO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONVERSIONE_TIPO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONVERSIONE_TEMPLATE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONVERSIONE_TEMPLATE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REQ_CONTENT_TYPE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REQ_CONTENT_TYPE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REST_TRANSFORMATION = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REST_TRANSFORMATION;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REST_METHOD = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REST_METHOD;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_REST_PATH = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_REST_PATH;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_TRANSFORMATION = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_TRANSFORMATION;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_VERSION = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_VERSION;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ACTION = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ACTION;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE_AS_ATTACH = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE_AS_ATTACH;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE_TIPO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE_TIPO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SOAP_ENVELOPE_TEMPLATE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_SOAP_ENVELOPE_TEMPLATE;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MIN = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MIN;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MAX = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_STATUS_MAX;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_CT = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_CT;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_PATTERN = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_APPLICABILITA_PATTERN;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_ENABLED = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_ENABLED;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TIPO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TIPO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TEMPLATE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONVERSIONE_TEMPLATE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_CONTENT_TYPE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_CONTENT_TYPE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_AS_ATTACH = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_AS_ATTACH;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TIPO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TIPO;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TEMPLATE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_SOAP_ENVELOPE_TEMPLATE;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_VALORE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADER_VALORE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_NOME = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADER_NOME;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RISPOSTA_HEADER_TIPO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RISPOSTA_HEADER_TIPO;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_VALORE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER_VALORE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_NOME = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER_NOME;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_HEADER_TIPO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_HEADER_TIPO;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_VALORE = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_VALORE;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_NOME = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_NOME;
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_TIPO = CostantiControlStation.LABEL_PARAMETRO_CONFIGURAZIONE_TRASFORMAZIONI_RICHIESTA_PARAMETRO_TIPO;
	
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICATIVO_CONFIG_DI = "Applicativi di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_APPLICATIVO_CONFIG = "Applicativi";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_CONFIG_DI = "Servizi Applicativi di ";
	public final static String LABEL_PARAMETRO_PORTE_DELEGATE_TRASFORMAZIONI_SERVIZIO_APPLICATIVO_CONFIG = "Servizi Applicativi";
	
	/* DEFAULT VALUE PARAMETRI */
	
	
	
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_NEW_ID = "0";
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_AUTENTICAZIONE =  TipoAutenticazione.SSL.getValue();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_AUTORIZZAZIONE = TipoAutorizzazione.AUTHENTICATED.getValue();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_STATELESS_DEFAULT = "default";
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_STATELESS_ABILITATO = CostantiConfigurazione.ABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_STATELESS_DISABILITATO = CostantiConfigurazione.DISABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_LOCAL_FORWARD_DISABILITATO = CostantiConfigurazione.DISABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_LOCAL_FORWARD_ABILITATO = CostantiConfigurazione.ABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_GEST_BODY_NONE = "none";
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_GEST_BODY_ALLEGA = "allega";  
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_GEST_BODY_SCARTA = "scarta";
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_GEST_MANIFEST_ABILITATO = CostantiConfigurazione.ABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_GEST_MANIFEST_DISABILITATO = CostantiConfigurazione.DISABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_GEST_MANIFEST_DEFAULT = "default";
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_SIMMETRICA_ABILITATO = CostantiConfigurazione.ABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_SIMMETRICA_DISABILITATO = CostantiConfigurazione.DISABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_ASIMMETRICA_ABILITATO = CostantiConfigurazione.ABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_RICEVUTA_ASINCRONA_ASIMMETRICA_DISABILITATO = CostantiConfigurazione.DISABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_VALIDAZIONE_XSD =  CostantiControlStation.DEFAULT_VALUE_PARAMETRO_PORTE_TIPO_VALIDAZIONE_XSD;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_VALIDAZIONE_INTERFACE = CostantiControlStation.DEFAULT_VALUE_PARAMETRO_PORTE_TIPO_VALIDAZIONE_INTERFACE;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_VALIDAZIONE_OPENSPCOOP = CostantiControlStation.DEFAULT_VALUE_PARAMETRO_PORTE_TIPO_VALIDAZIONE_OPENSPCOOP;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_VALIDAZIONE_DISABILITATO = CostantiControlStation.DEFAULT_VALUE_PARAMETRO_PORTE_VALIDAZIONE_DISABILITATO;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_VALIDAZIONE_ABILITATO = CostantiControlStation.DEFAULT_VALUE_PARAMETRO_PORTE_VALIDAZIONE_ABILITATO;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_VALIDAZIONE_WARNING_ONLY = CostantiControlStation.DEFAULT_VALUE_PARAMETRO_PORTE_VALIDAZIONE_WARNING_ONLY;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_DISABILITATO = CostantiConfigurazione.DISABILITATO.toString();
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_ABILITATO = CostantiConfigurazione.ABILITATO.toString();
//	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MODE_AZ_INPUT_BASED = "input-based";
//	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MODE_AZ_SOAP_ACTION_BASED = "soap-action-based";
//	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MODE_AZ_STATIC = "static";
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_ESTERNO = "esterno";
	public final static String VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_MODE_CORRELAZIONE_INPUT_BASED = CostantiControlStation.VALUE_PARAMETRO_MODE_CORRELAZIONE_INPUT_BASED;
	public final static String VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_MODE_CORRELAZIONE_URL_BASED = CostantiControlStation.VALUE_PARAMETRO_MODE_CORRELAZIONE_URL_BASED;
	public final static String VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_MODE_CORRELAZIONE_HEADER_BASED = CostantiControlStation.VALUE_PARAMETRO_MODE_CORRELAZIONE_HEADER_BASED;
	public final static String VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_MODE_CORRELAZIONE_CONTENT_BASED = CostantiControlStation.VALUE_PARAMETRO_MODE_CORRELAZIONE_CONTENT_BASED;
	public final static String VALUE_PARAMETRO_PORTE_DELEGATE_TIPO_MODE_CORRELAZIONE_DISABILITATO = CostantiControlStation.VALUE_PARAMETRO_MODE_CORRELAZIONE_DISABILITATO;
	
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_REGISTER_INPUT = PortaDelegataAzioneIdentificazione.STATIC.toString();
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_HEADER_BASED = PortaDelegataAzioneIdentificazione.HEADER_BASED.toString();
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_URL_BASED = PortaDelegataAzioneIdentificazione.URL_BASED.toString();
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_CONTENT_BASED = PortaDelegataAzioneIdentificazione.CONTENT_BASED.toString();
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_INPUT_BASED = PortaDelegataAzioneIdentificazione.INPUT_BASED.toString();
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_SOAP_ACTION_BASED = PortaDelegataAzioneIdentificazione.SOAP_ACTION_BASED.toString();
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_INTERFACE_BASED = PortaDelegataAzioneIdentificazione.INTERFACE_BASED.toString();
	public final static String PARAMETRO_PORTE_DELEGATE_MODE_DELEGATED_BY = PortaDelegataAzioneIdentificazione.DELEGATED_BY.toString();

	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MODO_CREAZIONE_EREDITA = "eredita";
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MODO_CREAZIONE_NUOVA = "nuova";
	
	public final static String VALUE_PARAMETRO_PORTE_DELEGATE_MODALITA_CONNETTORE_DEFAULT = ConnettoriCostanti.VALUE_PARAMETRO_MODALITA_CONNETTORE_DEFAULT;
	public final static String VALUE_PARAMETRO_PORTE_DELEGATE_MODALITA_CONNETTORE_RIDEFINITO = ConnettoriCostanti.VALUE_PARAMETRO_MODALITA_CONNETTORE_RIDEFINITO;
	
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_PROPERTIES_CONFIG_NAME = CostantiControlStation.VALUE_PARAMETRO_PROPERTIES_MODE_DEFAULT;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_PROPERTIES_CONFIG_NAME = CostantiControlStation.VALUE_PARAMETRO_PROPERTIES_MODE_DEFAULT;
	
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST_FLOW_PROPERTIES_CONFIG_NAME_NESSUNO = CostantiControlStation.DEFAULT_VALUE_NON_SELEZIONATO;
	public final static String DEFAULT_VALUE_PARAMETRO_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE_FLOW_PROPERTIES_CONFIG_NAME_NESSUNO = CostantiControlStation.DEFAULT_VALUE_NON_SELEZIONATO;
	
	public static final String TAG_PORTE_DELEGATE_MESSAGE_SECURITY_RESPONSE = "RESPONSE";
	public static final String TAG_PORTE_DELEGATE_MESSAGE_SECURITY_REQUEST = "REQUEST";
	public static final String TAG_PORTE_DELEGATE_MESSAGE_SECURITY_PD = "OUT";
		
	// Messaggi Errora
	public static final String MESSAGGIO_ERRORE_NON_E_POSSIBILE_MODIFICARE_IL_TIPO_DI_AUTENTICAZIONE_DA_XX_A_YY_POICHÈ_RISULTANO_ASSOCIATI_ALLA_PORTA_DELEGATA_DEI_SERVIZI_APPLICATIVI_NON_COMPATIBILI_NELLA_MODALITA_DI_ACCESSO_CON_IL_NUOVO_TIPO_DI_AUTENTICAZIONE = "Non &egrave; possibile modificare il tipo di autenticazione da [{0}] a [{1}], poichè risultano associati alla porta delegata dei servizi applicativi non compatibili, nella modalit&agrave; di accesso, con il nuovo tipo di autenticazione";
	public static final String MESSAGGIO_ERRORE_ESISTE_GIA_UNA_PORTA_DELEGATA_CON_NOME_XX_ASSOCIATA_AL_SOGGETTO_YY = "Esiste gi&agrave; una Porta Delegata con nome [{0}] associata al Soggetto [{1}]";
	public static final String MESSAGGIO_ERRORE_VALIDAZIONE_XSD_DEV_ESSERE_ABILITATO_DISABILITATO_O_WARNING_ONLY = "Validazione XSD dev'essere abilitato, disabilitato o warningOnly";
	public static final String MESSAGGIO_ERRORE_DATI_INCOMPLETI_EGRAVE_NECESSARIO_INDICARE_IL_NOME = "Dati incompleti. &Egrave; necessario indicare il Nome";
	public static final String MESSAGGIO_ERRORE_DATI_INCOMPLETI_NON_E_STATO_TROVATO_NESSUN_SOGGETTO_EROGATORE_SCEGLIERE_UNA_DELLE_ALTRE_MODALITA = "Dati incompleti. Non &egrave; stato trovato nessun soggetto erogatore. Scegliere una delle altre modalit&agrave;";
	public static final String MESSAGGIO_ERRORE_DATI_INCOMPLETI_NON_E_STATO_TROVATO_NESSUN_SERVIZIO_ASSOCIATO_AL_SOGGETTO_EROGATORE_SCEGLIERE_UNA_DELLE_ALTRE_MODALITA = "Dati incompleti. Non &egrave; stato trovato nessun servizio associato al soggetto erogatore. Scegliere una delle altre modalit&agrave;";
	public static final String MESSAGGIO_ERRORE_DATI_INCOMPLETI_E_NECESSARIO_INDICARE_XX = "Dati incompleti. &Egrave; necessario indicare: {0}";
	public static final String MESSAGGIO_ERRORE_LA_PROPRIETA_DI_MESSAGE_SECURITY_XX_E_GIA_STATO_ASSOCIATA_ALLA_PORTA_DELEGATA_YY = "La propriet&agrave; di message-security {0} &egrave; gi&agrave; stata associata alla porta delegata {1}";
	public static final String MESSAGGIO_ERRORE_NON_INSERIRE_SPAZI_NEI_NOMI = "Non inserire spazi nei nomi";
	public static final String MESSAGGIO_ERRORE_NON_INSERIRE_SPAZI_ALL_INIZIO_O_ALLA_FINE_DEI_VALORI = "Non inserire spazi all'inizio o alla fine dei valori";
	public static final String MESSAGGIO_ERRORE_NON_INSERIRE_SPAZI_NEI_CAMPI_DI_TESTO = "Non inserire spazi nei campi di testo";
	public static final String MESSAGGIO_ERRORE_DATI_INCOMPLETI_E_NECESSARIO_INDICARE_PATTERN_AZIONE = "Dati incompleti. &Egrave; necessario indicare: Pattern azione";
	public static final String MESSAGGIO_ERRORE_DATI_INCOMPLETI_NON_E_STATA_TROVATA_NESSUNA_AZIONE_ASSOCIATA_AL_SERVIZIO_SCEGLIERE_UNA_DELLE_ALTRE_MODALITA = "Dati incompleti. Non &egrave; stata trovata nessuna azione associata al servizio. Scegliere una delle altre modalit&agrave;";
	public static final String MESSAGGIO_ERRORE_DATI_INCOMPLETI_NON_E_STATA_TROVATA_NESSUNA_MODALITA_AZIONE = "Dati incompleti. Non &egrave; stata trovata nessuna Modalit&agrave; Azione";
	public static final String MESSAGGIO_ERRORE_ESISTE_GIA_UNA_PORTA_DELEGATA_CON_NOME_XX = "Esiste gi&agrave; una Porta Delegata con nome [{0}]";
	public static final String MESSAGGIO_ERRORE_INDICARE_UN_NOME_PER_L_AUTORIZZAZIONE_XX = "Indicare un nome per l'autorizzazione ''{0}''";
	public static final String MESSAGGIO_ERRORE_INDICARE_UN_NOME_PER_L_AUTENTICAZIONE_XX = "Indicare un nome per l'autenticazione ''{0}''";
	public static final String MESSAGGIO_ERRORE_NON_E_POSSIBILE_ELIMINARE_TUTTE_LE_AZIONI_ASSOCIATE_ALLA_CONFIGURAZIONE = "Non &egrave; possibile eliminare tutte le azioni associate alla configurazione";
	public static final String MESSAGGIO_ERRORE_LA_PROPERTY_XX_E_GIA_STATA_ASSOCIATA_ALLA_PORTA_DELEGATA_YY = "La property {0} &egrave; gi&agrave; stata associata alla porta delegata {1}";
	public static final String MESSAGGIO_ERRORE_LA_PROPERTY_XX_E_GIA_STATA_ASSOCIATA_ALLA_CONFIGURAZIONE_YY = "La property {0} &egrave; gi&agrave; stata associata alla configurazione {1}";
}

