package org.openspcoop2.web.ctrlstat.costanti;

public enum ConnettoreServletType {

	SOGGETTO, 
	SERVIZIO_APPLICATIVO_ADD,
	SERVIZIO_APPLICATIVO_CHANGE,
	SERVIZIO_APPLICATIVO_INVOCAZIONE_SERVIZIO, 
	SERVIZIO_APPLICATIVO_RISPOSTA_ASINCRONA,
	ACCORDO_SERVIZIO_PARTE_SPECIFICA_ADD, 
	ACCORDO_SERVIZIO_PARTE_SPECIFICA_CHANGE, 
	FRUIZIONE_ACCORDO_SERVIZIO_PARTE_SPECIFICA_ADD,
	FRUIZIONE_ACCORDO_SERVIZIO_PARTE_SPECIFICA_CHANGE,
	WIZARD_CONFIG,
	WIZARD_REGISTRY,
	
}
