-- **** Interazioni Asincrone PDND ****

CREATE SEQUENCE seq_PDND_INTERAZIONI_ASYNC start 1 increment 1 maxvalue 9223372036854775807 minvalue 1 cache 1 CYCLE;

CREATE TABLE PDND_INTERAZIONI_ASYNC
(
	INTERACTION_ID VARCHAR(255) NOT NULL,
	RUOLO VARCHAR(255) NOT NULL,
	FASE VARCHAR(255) NOT NULL,
	TIPO_FRUITORE VARCHAR(255),
	FRUITORE VARCHAR(255),
	TIPO_EROGATORE VARCHAR(255) NOT NULL,
	EROGATORE VARCHAR(255) NOT NULL,
	TIPO_SERVIZIO VARCHAR(255) NOT NULL,
	SERVIZIO VARCHAR(255) NOT NULL,
	VERSIONE_SERVIZIO INT NOT NULL,
	TIPO_SERVIZIO_CALLBACK VARCHAR(255),
	SERVIZIO_CALLBACK VARCHAR(255),
	VERSIONE_SERVIZIO_CALLBACK INT,
	PURPOSE_ID VARCHAR(255),
	CONSUMER_ID VARCHAR(255),
	CLIENT_ID VARCHAR(255),
	URL_CALLBACK VARCHAR(4000),
	ENTITY_NUMBER INT,
	TEMPO_MAX_CALLBACK BIGINT,
	TEMPO_DISPONIBILITA BIGINT,
	CONFERMA_RICHIESTA INT NOT NULL DEFAULT 0,
	LIMITE_ENTITA INT,
	NUMERO_GET_RESOURCE INT NOT NULL DEFAULT 0,
	ID_TRANSAZIONE_START VARCHAR(255),
	DATA_START TIMESTAMP NOT NULL,
	DATA_CALLBACK TIMESTAMP,
	DATA_GET_RESOURCE TIMESTAMP,
	DATA_CONFIRMATION TIMESTAMP,
	DATA_SCADENZA TIMESTAMP,
	DATA_AGGIORNAMENTO TIMESTAMP NOT NULL,
	-- fk/pk columns
	id BIGINT DEFAULT nextval('seq_PDND_INTERAZIONI_ASYNC') NOT NULL,
	-- unique constraints
	CONSTRAINT uniq_pdnd_async_1 UNIQUE (INTERACTION_ID,RUOLO),
	-- fk/pk keys constraints
	CONSTRAINT pk_PDND_INTERAZIONI_ASYNC PRIMARY KEY (id)
);

-- index
CREATE INDEX PDND_ASYNC_SCADENZA ON PDND_INTERAZIONI_ASYNC (DATA_SCADENZA);
CREATE INDEX PDND_ASYNC_AGGIORNAMENTO ON PDND_INTERAZIONI_ASYNC (DATA_AGGIORNAMENTO);
CREATE INDEX PDND_ASYNC_SEARCH ON PDND_INTERAZIONI_ASYNC (DATA_START,RUOLO);
