-- **** Serial for ID ****

CREATE TABLE ID_MESSAGGIO
(
	COUNTER NUMBER NOT NULL,
	PROTOCOLLO VARCHAR2(255) NOT NULL,
	ora_registrazione TIMESTAMP,
	-- fk/pk columns
	-- fk/pk keys constraints
	CONSTRAINT pk_ID_MESSAGGIO PRIMARY KEY (PROTOCOLLO)
);


ALTER TABLE ID_MESSAGGIO MODIFY ora_registrazione DEFAULT CURRENT_TIMESTAMP;


CREATE TABLE ID_MESSAGGIO_RELATIVO
(
	COUNTER NUMBER NOT NULL,
	PROTOCOLLO VARCHAR2(255) NOT NULL,
	INFO_ASSOCIATA VARCHAR2(255) NOT NULL,
	ora_registrazione TIMESTAMP,
	-- fk/pk columns
	-- fk/pk keys constraints
	CONSTRAINT pk_ID_MESSAGGIO_RELATIVO PRIMARY KEY (PROTOCOLLO,INFO_ASSOCIATA)
);


ALTER TABLE ID_MESSAGGIO_RELATIVO MODIFY ora_registrazione DEFAULT CURRENT_TIMESTAMP;


CREATE TABLE ID_MESSAGGIO_PRG
(
	PROGRESSIVO VARCHAR2(255) NOT NULL,
	PROTOCOLLO VARCHAR2(255) NOT NULL,
	ora_registrazione TIMESTAMP,
	-- fk/pk columns
	-- fk/pk keys constraints
	CONSTRAINT pk_ID_MESSAGGIO_PRG PRIMARY KEY (PROTOCOLLO)
);


ALTER TABLE ID_MESSAGGIO_PRG MODIFY ora_registrazione DEFAULT CURRENT_TIMESTAMP;


CREATE TABLE ID_MESSAGGIO_RELATIVO_PRG
(
	PROGRESSIVO VARCHAR2(255) NOT NULL,
	PROTOCOLLO VARCHAR2(255) NOT NULL,
	INFO_ASSOCIATA VARCHAR2(255) NOT NULL,
	ora_registrazione TIMESTAMP,
	-- fk/pk columns
	-- fk/pk keys constraints
	CONSTRAINT pk_ID_MESSAGGIO_RELATIVO_PRG PRIMARY KEY (PROTOCOLLO,INFO_ASSOCIATA)
);


ALTER TABLE ID_MESSAGGIO_RELATIVO_PRG MODIFY ora_registrazione DEFAULT CURRENT_TIMESTAMP;

