/*
 * OpenSPCoop - Customizable API Gateway 
 * http://www.openspcoop2.org
 * 
 * Copyright (c) 2005-2018 Link.it srl (http://link.it). 
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */


package org.openspcoop2.utils.id;

import com.fasterxml.uuid.Generators;
import com.fasterxml.uuid.impl.TimeBasedGenerator;

/**
 * Implementazione tramite com.fasterxml.uuid.impl.TimeBasedGenerator;
 *
 * @author Poli Andrea (apoli@link.it)
 * @author $Author$
 * @version $Rev$, $Date$
 */

public class UniversallyUniqueIdentifierV1Generator extends AbstractUniversallyUniqueIdentifierGenerator{

// Version 1: This generates a unique ID based on a network card MAC address and a timer. 
// These IDs are easy to predict (given one, I might be able to guess another one) and can be traced back to your network card. It's not recommended to create these.
//	UUIDv1 is NOT secure. It isn't meant to be. It is meant to be UNIQUE, not un-guessable. UUIDv1 uses the current timestamp, plus a machine identifier, 
//	plus some random-ish stuff to make a number that will never be generated by that algorithm again. 
//	This is appropriate for a transaction ID (even if everyone is doing millions of transactions/s).

	// Generators are fully thread-safe, so a single instance may be shared among multiple threads.
	private TimeBasedGenerator uuidv1 = Generators.timeBasedGenerator();
	
	@Override
	public IUniqueIdentifier newID() throws UniqueIdentifierException {
		UniversallyUniqueIdentifier uuidOpenSPCoop = new UniversallyUniqueIdentifier();
		uuidOpenSPCoop.setUuid(this.uuidv1.generate());
		return uuidOpenSPCoop;
	}

}
