/*
 * OpenSPCoop - Customizable API Gateway 
 * http://www.openspcoop2.org
 * 
 * Copyright (c) 2005-2016 Link.it srl (http://link.it).
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.openspcoop2.example.pdd.client.sdi.ricezione_fatture;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-10-07T14:32:46.381+02:00
 * Generated source version: 2.7.4
 *
 * @author Andrea Poli (apoli@link.it)
 * @author $Author$
 * @version $Rev$, $Date$
 */
@WebService(targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0", name = "RicezioneFatture")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RicezioneFatture {

    @Oneway
    @WebMethod(operationName = "NotificaDecorrenzaTermini", action = "http://www.fatturapa.it/RicezioneFatture/NotificaDecorrenzaTermini")
    public void notificaDecorrenzaTermini(
        @WebParam(partName = "parametersNotifica", name = "fileSdI", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types")
        FileSdIType parametersNotifica
    );

    @WebResult(name = "rispostaRiceviFatture", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types", partName = "parametersOut")
    @WebMethod(operationName = "RiceviFatture", action = "http://www.fatturapa.it/RicezioneFatture/RiceviFattureSdI")
    public RispostaRiceviFattureType riceviFatture(
        @WebParam(partName = "parametersIn", name = "fileSdIConMetadati", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types")
        FileSdIConMetadatiType parametersIn
    );
}
