-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_pa_trasf_resp_2;
-- DROP INDEX idx_pa_trasf_resp_1;
-- DROP INDEX index_pa_transform_2;
-- DROP INDEX index_pa_transform_1;
-- DROP INDEX index_pa_azioni_1;
-- DROP INDEX index_pa_soggetti_1;
-- DROP INDEX index_pa_scope_1;
-- DROP INDEX index_pa_ruoli_1;
-- DROP INDEX index_porte_applicative_1;
-- DROP INDEX idx_pa_trasf_hdr_resp_1;
-- DROP INDEX idx_pa_trasf_url_1;
-- DROP INDEX idx_pa_trasf_hdr_1;
-- DROP INDEX INDEX_PA_SA_AUTH;
-- DROP INDEX INDEX_PA_WSSRES;
-- DROP INDEX INDEX_PA_WSSREQ;
-- DROP INDEX INDEX_PA_MTOMTRES;
-- DROP INDEX INDEX_PA_MTOMTREQ;
-- DROP INDEX INDEX_PA_PROP;
-- DROP INDEX INDEX_PA_AUTH_PROP;
-- DROP INDEX INDEX_PA_SA;
DROP TABLE pa_transform_risp_hdr_init_seq;
DROP TABLE pa_transform_risp_hdr;
DROP TABLE pa_transform_risp_init_seq;
DROP TABLE pa_transform_risp;
DROP TABLE pa_transform_url_init_seq;
DROP TABLE pa_transform_url;
DROP TABLE pa_transform_hdr_init_seq;
DROP TABLE pa_transform_hdr;
DROP TABLE pa_transform_init_seq;
DROP TABLE pa_transform;
DROP TABLE pa_cache_regole_init_seq;
DROP TABLE pa_cache_regole;
DROP TABLE pa_azioni_init_seq;
DROP TABLE pa_azioni;
DROP TABLE porte_applicative_sa_auth_init_seq;
DROP TABLE porte_applicative_sa_auth;
DROP TABLE pa_soggetti_init_seq;
DROP TABLE pa_soggetti;
DROP TABLE pa_scope_init_seq;
DROP TABLE pa_scope;
DROP TABLE pa_ruoli_init_seq;
DROP TABLE pa_ruoli;
DROP TABLE pa_correlazione_risposta_init_seq;
DROP TABLE pa_correlazione_risposta;
DROP TABLE pa_correlazione_init_seq;
DROP TABLE pa_correlazione;
DROP TABLE pa_security_response_init_seq;
DROP TABLE pa_security_response;
DROP TABLE pa_security_request_init_seq;
DROP TABLE pa_security_request;
DROP TABLE pa_mtom_response_init_seq;
DROP TABLE pa_mtom_response;
DROP TABLE pa_mtom_request_init_seq;
DROP TABLE pa_mtom_request;
DROP TABLE pa_properties_init_seq;
DROP TABLE pa_properties;
DROP TABLE pa_auth_properties_init_seq;
DROP TABLE pa_auth_properties;
DROP TABLE porte_applicative_sa_init_seq;
DROP TABLE porte_applicative_sa;
DROP TABLE porte_applicative_init_seq;
DROP TABLE porte_applicative;
DROP SEQUENCE seq_pa_transform_risp_hdr;
DROP SEQUENCE seq_pa_transform_risp;
DROP SEQUENCE seq_pa_transform_url;
DROP SEQUENCE seq_pa_transform_hdr;
DROP SEQUENCE seq_pa_transform;
DROP SEQUENCE seq_pa_cache_regole;
DROP SEQUENCE seq_pa_azioni;
DROP SEQUENCE seq_porte_applicative_sa_auth;
DROP SEQUENCE seq_pa_soggetti;
DROP SEQUENCE seq_pa_scope;
DROP SEQUENCE seq_pa_ruoli;
DROP SEQUENCE seq_pa_correlazione_risposta;
DROP SEQUENCE seq_pa_correlazione;
DROP SEQUENCE seq_pa_security_response;
DROP SEQUENCE seq_pa_security_request;
DROP SEQUENCE seq_pa_mtom_response;
DROP SEQUENCE seq_pa_mtom_request;
DROP SEQUENCE seq_pa_properties;
DROP SEQUENCE seq_pa_auth_properties;
DROP SEQUENCE seq_porte_applicative_sa;
DROP SEQUENCE seq_porte_applicative;
