-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_remote_store_key_1;
-- DROP INDEX index_remote_store_1;
-- DROP INDEX index_nodi_runtime_2;
-- DROP INDEX index_nodi_runtime_1;
-- DROP INDEX index_config_handlers_1;
-- DROP INDEX index_registro_plugins_1;
-- DROP INDEX index_generic_properties_1;
-- DROP INDEX index_pdd_sys_props_1;
-- DROP INDEX index_servizi_pdd_1;
-- DROP INDEX index_config_url_regole_1;
-- DROP INDEX REMOTE_STORE_CREATE;
-- DROP INDEX REMOTE_STORE_UPDATE;
-- DROP INDEX INDEX_NODI_OP;
-- DROP INDEX index_registro_plug_jar_1;
-- DROP INDEX index_generic_property_1;
-- DROP INDEX index_dump_config_1;
-- DROP INDEX index_filetrace_config_1;
-- DROP INDEX index_tracce_config_1;
DROP TABLE remote_store_key_init_seq;
DROP TABLE remote_store_key;
DROP TABLE remote_store_init_seq;
DROP TABLE remote_store;
DROP TABLE nodi_runtime_operations_init_seq;
DROP TABLE nodi_runtime_operations;
DROP TABLE nodi_runtime_init_seq;
DROP TABLE nodi_runtime;
DROP TABLE config_handlers_init_seq;
DROP TABLE config_handlers;
DROP TABLE registro_plug_jar_init_seq;
DROP TABLE registro_plug_jar;
DROP TABLE registro_plugins_init_seq;
DROP TABLE registro_plugins;
DROP TABLE canali_nodi_init_seq;
DROP TABLE canali_nodi;
DROP TABLE canali_configurazione_init_seq;
DROP TABLE canali_configurazione;
DROP TABLE generic_property_init_seq;
DROP TABLE generic_property;
DROP TABLE generic_properties_init_seq;
DROP TABLE generic_properties;
DROP TABLE pdd_sys_props_init_seq;
DROP TABLE pdd_sys_props;
DROP TABLE servizi_pdd_filtri_init_seq;
DROP TABLE servizi_pdd_filtri;
DROP TABLE servizi_pdd_init_seq;
DROP TABLE servizi_pdd;
DROP TABLE tracce_ds_prop_init_seq;
DROP TABLE tracce_ds_prop;
DROP TABLE tracce_ds_init_seq;
DROP TABLE tracce_ds;
DROP TABLE msgdiag_ds_prop_init_seq;
DROP TABLE msgdiag_ds_prop;
DROP TABLE msgdiag_ds_init_seq;
DROP TABLE msgdiag_ds;
DROP TABLE dump_appender_prop_init_seq;
DROP TABLE dump_appender_prop;
DROP TABLE dump_appender_init_seq;
DROP TABLE dump_appender;
DROP TABLE dump_config_regola_init_seq;
DROP TABLE dump_config_regola;
DROP TABLE dump_config_init_seq;
DROP TABLE dump_config;
DROP TABLE filetrace_config_init_seq;
DROP TABLE filetrace_config;
DROP TABLE tracce_config_init_seq;
DROP TABLE tracce_config;
DROP TABLE tracce_appender_prop_init_seq;
DROP TABLE tracce_appender_prop;
DROP TABLE tracce_appender_init_seq;
DROP TABLE tracce_appender;
DROP TABLE msgdiag_appender_prop_init_seq;
DROP TABLE msgdiag_appender_prop;
DROP TABLE msgdiag_appender_init_seq;
DROP TABLE msgdiag_appender;
DROP TABLE config_url_regole_init_seq;
DROP TABLE config_url_regole;
DROP TABLE config_url_invocazione_init_seq;
DROP TABLE config_url_invocazione;
DROP TABLE configurazione_init_seq;
DROP TABLE configurazione;
DROP TABLE config_cache_regole_init_seq;
DROP TABLE config_cache_regole;
DROP TABLE routing_init_seq;
DROP TABLE routing;
DROP TABLE registri_init_seq;
DROP TABLE registri;
DROP SEQUENCE seq_remote_store_key;
DROP SEQUENCE seq_remote_store;
DROP SEQUENCE seq_nodi_runtime_operations;
DROP SEQUENCE seq_nodi_runtime;
DROP SEQUENCE seq_config_handlers;
DROP SEQUENCE seq_registro_plug_jar;
DROP SEQUENCE seq_registro_plugins;
DROP SEQUENCE seq_canali_nodi;
DROP SEQUENCE seq_canali_configurazione;
DROP SEQUENCE seq_generic_property;
DROP SEQUENCE seq_generic_properties;
DROP SEQUENCE seq_pdd_sys_props;
DROP SEQUENCE seq_servizi_pdd_filtri;
DROP SEQUENCE seq_servizi_pdd;
DROP SEQUENCE seq_tracce_ds_prop;
DROP SEQUENCE seq_tracce_ds;
DROP SEQUENCE seq_msgdiag_ds_prop;
DROP SEQUENCE seq_msgdiag_ds;
DROP SEQUENCE seq_dump_appender_prop;
DROP SEQUENCE seq_dump_appender;
DROP SEQUENCE seq_dump_config_regola;
DROP SEQUENCE seq_dump_config;
DROP SEQUENCE seq_filetrace_config;
DROP SEQUENCE seq_tracce_config;
DROP SEQUENCE seq_tracce_appender_prop;
DROP SEQUENCE seq_tracce_appender;
DROP SEQUENCE seq_msgdiag_appender_prop;
DROP SEQUENCE seq_msgdiag_appender;
DROP SEQUENCE seq_config_url_regole;
DROP SEQUENCE seq_config_url_invocazione;
DROP SEQUENCE seq_configurazione;
DROP SEQUENCE seq_config_cache_regole;
DROP SEQUENCE seq_routing;
DROP SEQUENCE seq_registri;
