-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX INDEX_PD_WSSRES;
-- DROP INDEX INDEX_PD_WSSREQ;
-- DROP INDEX INDEX_PD_MTOMTRES;
-- DROP INDEX INDEX_PD_MTOMTREQ;
-- DROP INDEX INDEX_PD_SA;
-- DROP INDEX index_porte_delegate_1;
DROP TABLE pd_correlazione_risposta_init_seq;
DROP TABLE pd_correlazione_risposta;
DROP TABLE pd_correlazione_init_seq;
DROP TABLE pd_correlazione;
DROP TABLE pd_ws_response_init_seq;
DROP TABLE pd_ws_response;
DROP TABLE pd_ws_request_init_seq;
DROP TABLE pd_ws_request;
DROP TABLE pd_mtom_response_init_seq;
DROP TABLE pd_mtom_response;
DROP TABLE pd_mtom_request_init_seq;
DROP TABLE pd_mtom_request;
DROP TABLE porte_delegate_sa_init_seq;
DROP TABLE porte_delegate_sa;
DROP TABLE porte_delegate_init_seq;
DROP TABLE porte_delegate;
DROP SEQUENCE seq_pd_correlazione_risposta;
DROP SEQUENCE seq_pd_correlazione;
DROP SEQUENCE seq_pd_ws_response;
DROP SEQUENCE seq_pd_ws_request;
DROP SEQUENCE seq_pd_mtom_response;
DROP SEQUENCE seq_pd_mtom_request;
DROP SEQUENCE seq_porte_delegate_sa;
DROP SEQUENCE seq_porte_delegate;
