-- **** Audit Configuration ****

CREATE SEQUENCE seq_audit_conf AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;

CREATE TABLE audit_conf
(
	audit_engine INT NOT NULL,
	enabled INT NOT NULL,
	dump INT NOT NULL,
	dump_format VARCHAR(255) NOT NULL,
	-- fk/pk columns
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	-- fk/pk keys constraints
	CONSTRAINT pk_audit_conf PRIMARY KEY (id)
);


ALTER TABLE audit_conf ALTER COLUMN audit_engine SET DEFAULT 0;
ALTER TABLE audit_conf ALTER COLUMN enabled SET DEFAULT 0;
ALTER TABLE audit_conf ALTER COLUMN dump SET DEFAULT 0;
ALTER TABLE audit_conf ALTER COLUMN dump_format SET DEFAULT 'JSON';

CREATE TABLE audit_conf_init_seq (id BIGINT);
INSERT INTO audit_conf_init_seq VALUES (NEXT VALUE FOR seq_audit_conf);



CREATE SEQUENCE seq_audit_filters AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;

CREATE TABLE audit_filters
(
	-- Filter
	username VARCHAR(255),
	tipo_operazione VARCHAR(255),
	tipo VARCHAR(255),
	stato VARCHAR(255),
	-- Filtri basati su contenuto utilizzabili solo se il dump della configurazione generale e' abilitato
	dump_search VARCHAR(255),
	-- 1(espressione regolare)/0(semplice stringa da ricercare)
	dump_expr INT NOT NULL,
	-- Action
	enabled INT NOT NULL,
	dump INT NOT NULL,
	-- Tempo di registrazione
	ora_registrazione TIMESTAMP,
	-- fk/pk columns
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	-- check constraints
	CONSTRAINT chk_audit_filters_1 CHECK (tipo_operazione IN ('ADD','CHANGE','DEL')),
	CONSTRAINT chk_audit_filters_2 CHECK (stato IN ('requesting','error','completed')),
	-- fk/pk keys constraints
	CONSTRAINT pk_audit_filters PRIMARY KEY (id)
);


ALTER TABLE audit_filters ALTER COLUMN dump_expr SET DEFAULT 0;
ALTER TABLE audit_filters ALTER COLUMN enabled SET DEFAULT 0;
ALTER TABLE audit_filters ALTER COLUMN dump SET DEFAULT 0;
ALTER TABLE audit_filters ALTER COLUMN ora_registrazione SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE audit_filters_init_seq (id BIGINT);
INSERT INTO audit_filters_init_seq VALUES (NEXT VALUE FOR seq_audit_filters);



CREATE SEQUENCE seq_audit_appender AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;

CREATE TABLE audit_appender
(
	name VARCHAR(255) NOT NULL,
	class VARCHAR(255) NOT NULL,
	-- fk/pk columns
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	-- unique constraints
	CONSTRAINT unique_audit_appender_1 UNIQUE (name),
	-- fk/pk keys constraints
	CONSTRAINT pk_audit_appender PRIMARY KEY (id)
);

CREATE TABLE audit_appender_init_seq (id BIGINT);
INSERT INTO audit_appender_init_seq VALUES (NEXT VALUE FOR seq_audit_appender);



CREATE SEQUENCE seq_audit_appender_prop AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;

CREATE TABLE audit_appender_prop
(
	name VARCHAR(255) NOT NULL,
	value VARCHAR(255) NOT NULL,
	id_audit_appender BIGINT NOT NULL,
	-- fk/pk columns
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	-- fk/pk keys constraints
	CONSTRAINT fk_audit_appender_prop_1 FOREIGN KEY (id_audit_appender) REFERENCES audit_appender(id),
	CONSTRAINT pk_audit_appender_prop PRIMARY KEY (id)
);

CREATE TABLE audit_appender_prop_init_seq (id BIGINT);
INSERT INTO audit_appender_prop_init_seq VALUES (NEXT VALUE FOR seq_audit_appender_prop);


