-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX CORR_APPL_OLD ON CORRELAZIONE_APPLICATIVA ;
-- DROP INDEX CORR_APPL_SCADUTE ON CORRELAZIONE_APPLICATIVA ;
-- DROP INDEX MSG_SERV_APPL_TIMEOUT ON MSG_SERVIZI_APPLICATIVI ;
-- DROP INDEX MSG_SERV_APPL_LIST ON MSG_SERVIZI_APPLICATIVI ;
-- DROP INDEX MESSAGGI_TESTSUITE ON MESSAGGI ;
-- DROP INDEX MESSAGGI_RIFMSG ON MESSAGGI ;
-- DROP INDEX MESSAGGI_SEARCH ON MESSAGGI ;
DROP TABLE CORRELAZIONE_APPLICATIVA;
DROP TABLE DEFINIZIONE_MESSAGGI;
DROP TABLE MSG_SERVIZI_APPLICATIVI;
DROP TABLE MESSAGGI;
