ALTER TABLE ID_MESSAGGIO ADD ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE ID_MESSAGGIO_RELATIVO ADD ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ID_MESSAGGIO_PRG ADD ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ID_MESSAGGIO_RELATIVO_PRG ADD ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
