ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN TIPO_MITTENTE DROP NOT NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN MITTENTE DROP NOT NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN TIPO_DESTINATARIO DROP NOT NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN DESTINATARIO DROP NOT NULL;
CALL SYSPROC.ADMIN_CMD ('REORG TABLE REPOSITORY_BUSTE') ; 
