-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX INDEX_AC_SC_SC;
-- DROP INDEX INDEX_AC_SC;
-- DROP INDEX INDEX_APS;
-- DROP INDEX INDEX_AC_COOP_PAR;
-- DROP INDEX INDEX_OP_MESSAGES;
-- DROP INDEX INDEX_DOC_SEARCH;
DROP TABLE acc_serv_componenti;
DROP TABLE acc_serv_composti;
DROP TABLE servizi_azioni;
DROP TABLE servizi_fruitori;
DROP TABLE servizi;
DROP TABLE accordi_coop_partecipanti;
DROP TABLE accordi_cooperazione;
DROP TABLE operation_messages;
DROP TABLE port_type_azioni;
DROP TABLE port_type;
DROP TABLE accordi_azioni;
DROP TABLE accordi;
DROP TABLE documenti;
DROP SEQUENCE seq_acc_serv_componenti;
DROP SEQUENCE seq_acc_serv_composti;
DROP SEQUENCE seq_servizi_azioni;
DROP SEQUENCE seq_servizi_fruitori;
DROP SEQUENCE seq_servizi;
DROP SEQUENCE seq_accordi_coop_partecipanti;
DROP SEQUENCE seq_accordi_cooperazione;
DROP SEQUENCE seq_operation_messages;
DROP SEQUENCE seq_port_type_azioni;
DROP SEQUENCE seq_port_type;
DROP SEQUENCE seq_accordi_azioni;
DROP SEQUENCE seq_accordi;
DROP SEQUENCE seq_documenti;
