hazelcast:
  cluster-name: govway
  map:
    "hazelcast-*-rate-limiting":
      in-memory-format: BINARY
      #in-memory-format: OBJECT
      backup-count: 0
      async-backup-count: 1

    near-cache:
      in-memory-format: BINARY
      #in-memory-format: OBJECT

  serialization:
    serializers:
      - type-class: org.openspcoop2.core.controllo_traffico.beans.IDUnivocoGroupByPolicy
        class-name: org.openspcoop2.pdd.core.controllo_traffico.policy.driver.hazelcast.IDUnivocoGroupByPolicyStreamSerializer

  network:
    port:
      auto-increment: false
      port: 5704
