CREATE TABLE tracce (
     descrizione VARCHAR(255) NOT NULL,
     gdo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     gdo2 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     tipo_mittente VARCHAR(255) NOT NULL,
     mittente VARCHAR(255) NOT NULL,
     tipo_destinatario VARCHAR(255) NOT NULL,
     destinatario VARCHAR(255) NOT NULL,
     campo_vuoto VARCHAR(255),
     campo_update VARCHAR(255),
     campo_int_update INT,
	 id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE NO CACHE)
);
CREATE TABLE msgdiagnostici (
     descrizione VARCHAR(255) NOT NULL,
     gdo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     gdo2 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     tipo_mittente VARCHAR(255) NOT NULL,
     mittente VARCHAR(255) NOT NULL,
     tipo_destinatario VARCHAR(255) NOT NULL,
     destinatario VARCHAR(255) NOT NULL,
     campo_vuoto VARCHAR(255),
     campo_update VARCHAR(255),
     campo_int_update INT,
	 id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE NO CACHE)
);