CREATE SEQUENCE seq_tracce AS BIGINT START WITH 1 INCREMENT BY 1 ;
CREATE TABLE tracce (
     descrizione VARCHAR(255) NOT NULL,
     gdo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     gdo2 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     tipo_mittente VARCHAR(255) NOT NULL,
     mittente VARCHAR(255) NOT NULL,
     tipo_destinatario VARCHAR(255) NOT NULL,
     destinatario VARCHAR(255) NOT NULL,
     campo_vuoto VARCHAR(255),
     campo_update VARCHAR(255),
     campo_int_update INT,
	 id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1)
);
CREATE TABLE tracce_init_seq (id BIGINT);
INSERT INTO tracce_init_seq VALUES (NEXT VALUE FOR seq_tracce);
CREATE SEQUENCE seq_msgdiagnostici AS BIGINT START WITH 1 INCREMENT BY 1 ;
CREATE TABLE msgdiagnostici (
     descrizione VARCHAR(255) NOT NULL,
     gdo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     gdo2 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     tipo_mittente VARCHAR(255) NOT NULL,
     mittente VARCHAR(255) NOT NULL,
     tipo_destinatario VARCHAR(255) NOT NULL,
     destinatario VARCHAR(255) NOT NULL,
     campo_vuoto VARCHAR(255),
     campo_update VARCHAR(255),
     campo_int_update INT,
	 id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1)
);
CREATE TABLE msgdiagnostici_init_seq (id BIGINT);
INSERT INTO msgdiagnostici_init_seq VALUES (NEXT VALUE FOR seq_msgdiagnostici);