# snakeyaml-1.33-gov4j-1.jar
#
# La libreria viene utilizzata solamente per la gestione delle interfacce yaml
# caricate sulla console dagli amministratori. Non viene utilizzata per input
# fornito dinamicamente nelle richieste gestite dal Gateway.
#
# OWASP Suppression: mvn/dependencies/owasp/falsePositives/snakeyaml.xml

# CVE-2022-1471 - SnakeYaml Constructor() does not restrict types during deserialization,
# deserializing attacker-provided content can lead to remote code execution.
[[IgnoredVulns]]
id = "CVE-2022-1471"
reason = "Falso positivo: snakeyaml usato solo per interfacce yaml caricate dagli amministratori sulla console, non per input dinamico nelle richieste del Gateway"
