/*
 * GovWay - A customizable API Gateway
 * https://govway.org
 * 
 * Copyright (c) 2005-2023 Link.it srl (https://link.it). 
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */



package org.openspcoop2.core.commons;

/**
 * Enumeration per Controlli
 *
 * @author Stefano Corallo (corallo@link.it)
 * @author $Author$
 * @version $Rev$, $Date$
 */

public enum ErrorsHandlerCostant {

	IN_USO_IN_PORTE_APPLICATIVE, IN_USO_IN_PORTE_DELEGATE, IN_USO_IN_SERVIZI_APPLICATIVI,
	IN_USO_IN_SERVIZI, IS_FRUITORE,
	IN_USO_IN_MAPPING_FRUIZIONE_PD, IN_USO_IN_MAPPING_EROGAZIONE_PA,
	IN_USO_IN_PORTE_APPLICATIVE_MODI, IN_USO_IN_MAPPING_EROGAZIONE_PA_MODI,
	IS_CORRELATA,
	IN_USO_IN_SOGGETTI,
	POSSIEDE_FRUITORI, 
	IS_REFERENTE,IS_REFERENTE_COOPERAZIONE,
	IS_PARTECIPANTE_COOPERAZIONE, 
	IN_USO_IN_ACCORDI,
	IS_SERVIZIO_COMPONENTE_IN_ACCORDI,
	UTENTE,
	CONTROLLO_TRAFFICO,
	AUTENTICAZIONE_PD,
	AUTENTICAZIONE_MAPPING_PD,
	AUTENTICAZIONE_PA,
	AUTENTICAZIONE_MAPPING_PA,
	AUTORIZZAZIONE,
	AUTORIZZAZIONE_MAPPING,
	AUTORIZZAZIONE_PD,
	AUTORIZZAZIONE_MAPPING_PD,
	AUTORIZZAZIONE_PA,
	AUTORIZZAZIONE_MAPPING_PA,
	AUTORIZZAZIONE_PA_MODI,
	AUTORIZZAZIONE_MAPPING_PA_MODI,
	AUTORIZZAZIONE_CONTENUTI_PD,
	AUTORIZZAZIONE_CONTENUTI_MAPPING_PD,
	AUTORIZZAZIONE_CONTENUTI_PA,
	AUTORIZZAZIONE_CONTENUTI_MAPPING_PA,
	AUTORIZZAZIONE_TOKEN_PD,
	AUTORIZZAZIONE_TOKEN_MAPPING_PD,
	AUTORIZZAZIONE_TOKEN_PA,
	AUTORIZZAZIONE_TOKEN_MAPPING_PA,
	RUOLI,
	RUOLI_MAPPING,
	RUOLI_PA,
	RUOLI_MAPPING_PA,
	RUOLI_TOKEN_PD,
	RUOLI_TOKEN_MAPPING_PD,
	RUOLI_TOKEN_PA,
	RUOLI_TOKEN_MAPPING_PA,
	RUOLI_TOKEN_PA_MODI,
	RUOLI_TOKEN_MAPPING_PA_MODI,
	INTEGRAZIONE_PD,
	INTEGRAZIONE_MAPPING_PD,
	INTEGRAZIONE_PA,
	INTEGRAZIONE_MAPPING_PA,
	BEHAVIOUR_PA,
	BEHAVIOUR_MAPPING_PA,
	TRASFORMAZIONE_PD,
	TRASFORMAZIONE_MAPPING_PD,
	TRASFORMAZIONE_PA,
	TRASFORMAZIONE_MAPPING_PA,
	URLINVOCAZIONE_PD,
	URLINVOCAZIONE_MAPPING_PD,
	URLINVOCAZIONE_PA,
	URLINVOCAZIONE_MAPPING_PA,
	CONFIGURAZIONE_REGOLE_PROXY_PASS,
	CONNETTORE_PD,
	CONNETTORE_MAPPING_PD,
	CONNETTORE_PA,
	CONNETTORE_MAPPING_PA,
	TOKEN_PD,
	TOKEN_MAPPING_PD,
	TOKEN_PA,
	TOKEN_MAPPING_PA,
	TOKEN_SA,
	TOKEN_SA_MODI,
	TOKEN_NEGOZIAZIONE_PD,
	TOKEN_NEGOZIAZIONE_MAPPING_PD,
	TOKEN_NEGOZIAZIONE_PA,
	TOKEN_NEGOZIAZIONE_MAPPING_PA,
	ATTRIBUTE_AUTHORITY_PD,
	ATTRIBUTE_AUTHORITY_MAPPING_PD,
	ATTRIBUTE_AUTHORITY_PA,
	ATTRIBUTE_AUTHORITY_MAPPING_PA,
	IN_USO_IN_CANALE_NODO,
	ALLARMI, ALLARMI_PD, ALLARMI_PA, ALLARMI_MAPPING_PD, ALLARMI_MAPPING_PA,
	MESSAGE_HANDLER, MESSAGE_HANDLER_PD, MESSAGE_HANDLER_PA, MESSAGE_HANDLER_MAPPING_PD, MESSAGE_HANDLER_MAPPING_PA,
	SERVICE_HANDLER;

}
