<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
				  xmlns:tns="http://www.openspcoop2.org/pdd/monitor/management" 
				  xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/"
				  name="MessaggioService"
				  targetNamespace="http://www.openspcoop2.org/pdd/monitor/management">

	<wsdl:import namespace="http://www.openspcoop2.org/pdd/monitor/management" 
				 location="MessaggioAll.wsdl"/>
	
	<!-- BINDING (SOAP11) --> 
	
	<wsdl:binding name="MessaggioServiceSoap11Binding" type="tns:Messaggio">
		<soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsdl:operation name="findAll">
			<soap11:operation soapAction="findAll" style="document"/>
			<wsdl:input name="findAll">
				<soap11:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="findAllResponse">
				<soap11:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="monitor-service-exception">
				<soap11:fault name="monitor-service-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-implemented-exception">
				<soap11:fault name="monitor-not-implemented-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-authorized-exception">
				<soap11:fault name="monitor-not-authorized-exception" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>


		<wsdl:operation name="count">
			<soap11:operation soapAction="count" style="document"/>
			<wsdl:input name="count">
				<soap11:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="countResponse">
				<soap11:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="monitor-service-exception">
				<soap11:fault name="monitor-service-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-implemented-exception">
				<soap11:fault name="monitor-not-implemented-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-authorized-exception">
				<soap11:fault name="monitor-not-authorized-exception" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>


		

		<wsdl:operation name="deleteAllByFilter">
			<soap11:operation soapAction="deleteAllByFilter" style="document"/>
			<wsdl:input name="deleteAllByFilter">
				<soap11:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="deleteAllByFilterResponse">
				<soap11:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="monitor-service-exception">
				<soap11:fault name="monitor-service-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-implemented-exception">
				<soap11:fault name="monitor-not-implemented-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-authorized-exception">
				<soap11:fault name="monitor-not-authorized-exception" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	
    

	</wsdl:binding>

	<!-- SERVICE -->	
	<wsdl:service name="MessaggioSoap11Service">	

		<wsdl:port binding="tns:MessaggioServiceSoap11Binding" name="MessaggioPortSoap11">
			<soap11:address location="http://localhost:8080/monitor/Messaggio/Soap11"/>
		</wsdl:port>	
			
	</wsdl:service>
	
</wsdl:definitions>
