<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
				  xmlns:tns="http://www.openspcoop2.org/pdd/monitor/management" 
				  xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/"
				  name="StatoPddService"
				  targetNamespace="http://www.openspcoop2.org/pdd/monitor/management">

	<wsdl:import namespace="http://www.openspcoop2.org/pdd/monitor/management" 
				 location="StatoPddAll.wsdl"/>
	
	<!-- BINDING (SOAP11) --> 
	
	<wsdl:binding name="StatoPddServiceSoap11Binding" type="tns:StatoPdd">
		<soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>


		<wsdl:operation name="find">
			<soap11:operation soapAction="find" style="document"/>
			<wsdl:input name="find">
				<soap11:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="findResponse">
				<soap11:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="monitor-service-exception">
				<soap11:fault name="monitor-service-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-found-exception">
				<soap11:fault name="monitor-not-found-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-multiple-result-exception">
				<soap11:fault name="monitor-multiple-result-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-implemented-exception">
				<soap11:fault name="monitor-not-implemented-exception" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="monitor-not-authorized-exception">
				<soap11:fault name="monitor-not-authorized-exception" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>



		

	
    

	</wsdl:binding>

	<!-- SERVICE -->	
	<wsdl:service name="StatoPddSoap11Service">	

		<wsdl:port binding="tns:StatoPddServiceSoap11Binding" name="StatoPddPortSoap11">
			<soap11:address location="http://localhost:8080/monitor/StatoPdd/Soap11"/>
		</wsdl:port>	
			
	</wsdl:service>
	
</wsdl:definitions>
