/*
 * OpenSPCoop v2 - Customizable SOAP Message Broker 
 * http://www.openspcoop2.org
 * 
 * Copyright (c) 2005-2016 Link.it srl (http://link.it).
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.openspcoop2.pdd.monitor.ws.client.statopdd.all;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-12-01T13:15:50.070+01:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "StatoPddSoap12Service", 
                  wsdlLocation = "deploy/wsdl/StatoPddAll_PortSoap12.wsdl",
                  targetNamespace = "http://www.openspcoop2.org/pdd/monitor/management") 
public class StatoPddSoap12Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.openspcoop2.org/pdd/monitor/management", "StatoPddSoap12Service");
    public final static QName StatoPddPortSoap12 = new QName("http://www.openspcoop2.org/pdd/monitor/management", "StatoPddPortSoap12");
    static {
        URL url = StatoPddSoap12Service.class.getResource("deploy/wsdl/StatoPddAll_PortSoap12.wsdl");
        if (url == null) {
            url = StatoPddSoap12Service.class.getClassLoader().getResource("deploy/wsdl/StatoPddAll_PortSoap12.wsdl");
        } 
        if (url == null) {
            
		}
		if (url==null ){
			url = StatoPddSoap12Service.class.getResource("/monitor/StatoPddAll_PortSoap12.wsdl");
		}
		if (url==null ){
			url = StatoPddSoap12Service.class.getClassLoader().getResource("/monitor/StatoPddAll_PortSoap12.wsdl");
		}
		if (url==null ){
			java.util.logging.Logger.getLogger(StatoPddSoap12Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "deploy/wsdl/StatoPddAll_PortSoap12.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public StatoPddSoap12Service(URL wsdlLocation) {
        super(wsdlLocation, StatoPddSoap12Service.SERVICE);
    }

    public StatoPddSoap12Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatoPddSoap12Service() {
        super(StatoPddSoap12Service.WSDL_LOCATION, StatoPddSoap12Service.SERVICE);
    }
    

    /**
     *
     * @return
     *     returns StatoPdd
     */
    @WebEndpoint(name = "StatoPddPortSoap12")
    public StatoPdd getStatoPddPortSoap12() {
        return super.getPort(StatoPddSoap12Service.StatoPddPortSoap12, StatoPdd.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatoPdd
     */
    @WebEndpoint(name = "StatoPddPortSoap12")
    public StatoPdd getStatoPddPortSoap12(WebServiceFeature... features) {
        return super.getPort(StatoPddSoap12Service.StatoPddPortSoap12, StatoPdd.class, features);
    }

}
