package org.openspcoop2.core.diagnostica.ws.client.informazioniprotocollotransazione.search;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-02-20T15:28:43.213+01:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "InformazioniProtocolloTransazioneSoap12Service", 
                  wsdlLocation = "deploy/wsdl/InformazioniProtocolloTransazioneSearch_PortSoap12.wsdl",
                  targetNamespace = "http://www.openspcoop2.org/core/diagnostica/management") 
public class InformazioniProtocolloTransazioneSoap12Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.openspcoop2.org/core/diagnostica/management", "InformazioniProtocolloTransazioneSoap12Service");
    public final static QName InformazioniProtocolloTransazionePortSoap12 = new QName("http://www.openspcoop2.org/core/diagnostica/management", "InformazioniProtocolloTransazionePortSoap12");
    static {
        URL url = InformazioniProtocolloTransazioneSoap12Service.class.getResource("deploy/wsdl/InformazioniProtocolloTransazioneSearch_PortSoap12.wsdl");
        if (url == null) {
            url = InformazioniProtocolloTransazioneSoap12Service.class.getClassLoader().getResource("deploy/wsdl/InformazioniProtocolloTransazioneSearch_PortSoap12.wsdl");
        } 
        if (url == null) {
            
		}
		if (url==null ){
			url = InformazioniProtocolloTransazioneSoap12Service.class.getResource("/diagnostica/InformazioniProtocolloTransazioneSearch_PortSoap12.wsdl");
		}
		if (url==null ){
			url = InformazioniProtocolloTransazioneSoap12Service.class.getClassLoader().getResource("/diagnostica/InformazioniProtocolloTransazioneSearch_PortSoap12.wsdl");
		}
		if (url==null ){
			java.util.logging.Logger.getLogger(InformazioniProtocolloTransazioneSoap12Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "deploy/wsdl/InformazioniProtocolloTransazioneSearch_PortSoap12.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public InformazioniProtocolloTransazioneSoap12Service(URL wsdlLocation) {
        super(wsdlLocation, InformazioniProtocolloTransazioneSoap12Service.SERVICE);
    }

    public InformazioniProtocolloTransazioneSoap12Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InformazioniProtocolloTransazioneSoap12Service() {
        super(InformazioniProtocolloTransazioneSoap12Service.WSDL_LOCATION, InformazioniProtocolloTransazioneSoap12Service.SERVICE);
    }
    

    /**
     *
     * @return
     *     returns InformazioniProtocolloTransazione
     */
    @WebEndpoint(name = "InformazioniProtocolloTransazionePortSoap12")
    public InformazioniProtocolloTransazione getInformazioniProtocolloTransazionePortSoap12() {
        return super.getPort(InformazioniProtocolloTransazioneSoap12Service.InformazioniProtocolloTransazionePortSoap12, InformazioniProtocolloTransazione.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InformazioniProtocolloTransazione
     */
    @WebEndpoint(name = "InformazioniProtocolloTransazionePortSoap12")
    public InformazioniProtocolloTransazione getInformazioniProtocolloTransazionePortSoap12(WebServiceFeature... features) {
        return super.getPort(InformazioniProtocolloTransazioneSoap12Service.InformazioniProtocolloTransazionePortSoap12, InformazioniProtocolloTransazione.class, features);
    }

}
