/*
 * GovWay - A customizable API Gateway 
 * https://govway.org
 * 
 * Copyright (c) 2005-2021 Link.it srl (https://link.it).
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.openspcoop2.core.statistiche.utils;

import java.util.ArrayList;
import java.util.List;

import org.openspcoop2.core.commons.ExpressionUtils;
import org.openspcoop2.core.statistiche.StatisticaGiornaliera;
import org.openspcoop2.core.statistiche.StatisticaMensile;
import org.openspcoop2.core.statistiche.StatisticaOraria;
import org.openspcoop2.core.statistiche.StatisticaSettimanale;
import org.openspcoop2.generic_project.beans.IField;
import org.openspcoop2.generic_project.expression.IExpression;


/**     
 * StatisticheIndexUtils
 *
 * @author Poli Andrea (poli@link.it)
 * @author $Author$
 * @version $Rev$, $Date$
 */
public class StatisticheIndexUtils {

	private static final String PROP_NAME_SOLO_COLONNE_INDICIZZATE_FULL_INDEX = "SoloColonneIndiceFullIndex";
	
	public static void enableSoloColonneIndicizzateFullIndex(IExpression expr) {
		ExpressionUtils.enable(expr, PROP_NAME_SOLO_COLONNE_INDICIZZATE_FULL_INDEX);
	}
	public static boolean isEnabledSoloColonneIndicizzateFullIndex(IExpression expr) {
		return ExpressionUtils.isEnabled(expr, PROP_NAME_SOLO_COLONNE_INDICIZZATE_FULL_INDEX);
	}

	
	
	public static List<IField> LISTA_COLONNE_INDEX_STAT_ORARIA = new ArrayList<IField>();
	static {
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.DATA);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.STATO_RECORD);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.ESITO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.ESITO_CONTESTO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.ID_PORTA);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TIPO_PORTA);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TIPO_DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TIPO_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.VERSIONE_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.AZIONE);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TIPO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.MITTENTE);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.SERVIZIO_APPLICATIVO);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TRASPORTO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TOKEN_ISSUER);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TOKEN_CLIENT_ID);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TOKEN_SUBJECT);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TOKEN_USERNAME);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.TOKEN_MAIL);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.CLIENT_ADDRESS);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.GRUPPI);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.URI_API);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.CLUSTER_ID);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.NUMERO_TRANSAZIONI);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_COMPLESSIVA);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_INTERNA);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_ESTERNA);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.LATENZA_TOTALE);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.LATENZA_PORTA);
		LISTA_COLONNE_INDEX_STAT_ORARIA.add(StatisticaOraria.model().STATISTICA_BASE.LATENZA_SERVIZIO);
	}
	
	public static List<IField> LISTA_COLONNE_INDEX_STAT_GIORNALIERA = new ArrayList<IField>();
	static {
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.DATA);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.STATO_RECORD);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.ESITO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.ESITO_CONTESTO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.ID_PORTA);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TIPO_PORTA);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TIPO_DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TIPO_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.VERSIONE_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.AZIONE);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TIPO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.MITTENTE);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.SERVIZIO_APPLICATIVO);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TRASPORTO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TOKEN_ISSUER);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TOKEN_CLIENT_ID);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TOKEN_SUBJECT);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TOKEN_USERNAME);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.TOKEN_MAIL);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.CLIENT_ADDRESS);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.GRUPPI);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.URI_API);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.CLUSTER_ID);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.NUMERO_TRANSAZIONI);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_COMPLESSIVA);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_INTERNA);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_ESTERNA);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.LATENZA_TOTALE);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.LATENZA_PORTA);
		LISTA_COLONNE_INDEX_STAT_GIORNALIERA.add(StatisticaGiornaliera.model().STATISTICA_BASE.LATENZA_SERVIZIO);
	}
 
	public static List<IField> LISTA_COLONNE_INDEX_STAT_SETTIMANALE = new ArrayList<IField>();
	static {
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.DATA);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.STATO_RECORD);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.ESITO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.ESITO_CONTESTO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.ID_PORTA);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TIPO_PORTA);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TIPO_DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TIPO_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.VERSIONE_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.AZIONE);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TIPO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.MITTENTE);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.SERVIZIO_APPLICATIVO);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TRASPORTO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TOKEN_ISSUER);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TOKEN_CLIENT_ID);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TOKEN_SUBJECT);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TOKEN_USERNAME);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.TOKEN_MAIL);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.CLIENT_ADDRESS);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.GRUPPI);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.URI_API);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.CLUSTER_ID);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.NUMERO_TRANSAZIONI);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_COMPLESSIVA);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_INTERNA);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_ESTERNA);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.LATENZA_TOTALE);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.LATENZA_PORTA);
		LISTA_COLONNE_INDEX_STAT_SETTIMANALE.add(StatisticaSettimanale.model().STATISTICA_BASE.LATENZA_SERVIZIO);
	}
	
	public static List<IField> LISTA_COLONNE_INDEX_STAT_MENSILE = new ArrayList<IField>();
	static {
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.DATA);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.STATO_RECORD);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.ESITO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.ESITO_CONTESTO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.ID_PORTA);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TIPO_PORTA);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TIPO_DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.DESTINATARIO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TIPO_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.VERSIONE_SERVIZIO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.AZIONE);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TIPO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.MITTENTE);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.SERVIZIO_APPLICATIVO);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TRASPORTO_MITTENTE);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TOKEN_ISSUER);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TOKEN_CLIENT_ID);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TOKEN_SUBJECT);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TOKEN_USERNAME);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.TOKEN_MAIL);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.CLIENT_ADDRESS);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.GRUPPI);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.URI_API);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.CLUSTER_ID);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.NUMERO_TRANSAZIONI);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_COMPLESSIVA);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_INTERNA);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.DIMENSIONI_BYTES_BANDA_ESTERNA);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.LATENZA_TOTALE);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.LATENZA_PORTA);
		LISTA_COLONNE_INDEX_STAT_MENSILE.add(StatisticaMensile.model().STATISTICA_BASE.LATENZA_SERVIZIO);
	}

}