<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.openspcoop2.org/example" xmlns:specificasemiformaleimportwsdl="http://www.openspcoop2.org/example/specificasemiformale/importwsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:allegatoimportwsdl="http://www.openspcoop2.org/example/allegato/importwsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:spc="http://www.openspcoop2.org/example" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.openspcoop2.org/example" location="../specificaInterfaccia/InterfacciaLogicaErogatore.wsdl">
    </wsdl:import>
  <wsdl:types>
  </wsdl:types>
  <wsdl:binding name="OnewayBinding" type="spc:Oneway">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="notifica">
        <soap:operation soapAction="" style="document"/>
        <wsdl:input name="notificaRequest">
          <soap:body parts="notificaRequestPart" use="literal"/>
          <soap:body parts="notificaRequestPart2" use="literal"/>
        </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="notifica2">
        <soap:operation soapAction="" style="document"/>
        <wsdl:input name="notificaRequestImportato">
            <soap:body parts="notificaRequestPartImportato" use="literal"/>
        </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="SincronoBinding" type="spc:Sincrono">
     <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
     <wsdl:operation name="echo">
        <soap:operation soapAction="" style="document"/>
        <wsdl:input name="notificaRequestIncluso">
            <soap:body parts="notificaRequestPartIncluso" use="literal"/>
        </wsdl:input>
     </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OnewayService">
    <wsdl:port name="NotificaPort" binding="spc:OnewayBinding">
      <soap:address location="http://localhost:8080/"/>
    </wsdl:port>
  </wsdl:service>
  <wsdl:service name="SincronoService">
      <wsdl:port name="EchoPort" binding="spc:SincronoBinding">
          <soap:address location="http://localhost:8080/"/>
       </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
