ALTER TABLE ID_MESSAGGIO ADD COLUMN ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE ID_MESSAGGIO_RELATIVO ADD COLUMN ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ID_MESSAGGIO_PRG ADD COLUMN ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ID_MESSAGGIO_RELATIVO_PRG ADD COLUMN ora_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
