ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN TIPO_MITTENTE SET NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN MITTENTE SET NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN TIPO_DESTINATARIO SET NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN DESTINATARIO SET NULL;
