-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX INDEX_AC_SC_SERV;
-- DROP INDEX INDEX_AC_SC_SC;
-- DROP INDEX INDEX_AC_SC;
-- DROP INDEX index_serv_fru_azioni_1;
-- DROP INDEX INDEX_SERV_FRU_SOG;
-- DROP INDEX index_servizi_azioni_1;
-- DROP INDEX INDEX_SERV_SOG;
-- DROP INDEX INDEX_SERV_ACC;
-- DROP INDEX INDEX_AC_SOG;
-- DROP INDEX INDEX_AC_COOP_PAR;
-- DROP INDEX INDEX_OP_MESSAGES;
-- DROP INDEX index_accordi_1;
-- DROP INDEX INDEX_DOC_SEARCH;
DROP TABLE acc_serv_componenti;
DROP TABLE acc_serv_composti;
DROP TABLE servizi_fruitori_azione;
DROP TABLE servizi_fruitori_azioni;
DROP TABLE servizi_fruitori;
DROP TABLE servizi_azione;
DROP TABLE servizi_azioni;
DROP TABLE servizi;
DROP TABLE accordi_coop_partecipanti;
DROP TABLE accordi_cooperazione;
DROP TABLE accordi_gruppi;
DROP TABLE api_resources_parameter;
DROP TABLE api_resources_media;
DROP TABLE api_resources_response;
DROP TABLE api_resources;
DROP TABLE operation_messages;
DROP TABLE port_type_azioni;
DROP TABLE port_type;
DROP TABLE accordi_azioni;
DROP TABLE accordi;
DROP TABLE documenti;
