-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX INDEX_AC_SC_SC;
-- DROP INDEX INDEX_AC_SC;
-- DROP INDEX index_serv_fru_azioni_1;
-- DROP INDEX index_servizi_azioni_1;
-- DROP INDEX INDEX_AC_COOP_PAR;
-- DROP INDEX INDEX_OP_MESSAGES;
-- DROP INDEX INDEX_DOC_SEARCH;
DROP TRIGGER trg_acc_serv_componenti;
DROP TRIGGER trg_acc_serv_composti;
DROP TRIGGER trg_servizi_fruitori_azione;
DROP TRIGGER trg_servizi_fruitori_azioni;
DROP TRIGGER trg_servizi_fruitori;
DROP TRIGGER trg_servizi_azione;
DROP TRIGGER trg_servizi_azioni;
DROP TRIGGER trg_servizi;
DROP TRIGGER trg_accordi_coop_partecipanti;
DROP TRIGGER trg_accordi_cooperazione;
DROP TRIGGER trg_api_resources_parameter;
DROP TRIGGER trg_api_resources_media;
DROP TRIGGER trg_api_resources_response;
DROP TRIGGER trg_api_resources;
DROP TRIGGER trg_operation_messages;
DROP TRIGGER trg_port_type_azioni;
DROP TRIGGER trg_port_type;
DROP TRIGGER trg_accordi_azioni;
DROP TRIGGER trg_accordi;
DROP TRIGGER trg_documenti;
DROP TABLE acc_serv_componenti;
DROP TABLE acc_serv_composti;
DROP TABLE servizi_fruitori_azione;
DROP TABLE servizi_fruitori_azioni;
DROP TABLE servizi_fruitori;
DROP TABLE servizi_azione;
DROP TABLE servizi_azioni;
DROP TABLE servizi;
DROP TABLE accordi_coop_partecipanti;
DROP TABLE accordi_cooperazione;
DROP TABLE api_resources_parameter;
DROP TABLE api_resources_media;
DROP TABLE api_resources_response;
DROP TABLE api_resources;
DROP TABLE operation_messages;
DROP TABLE port_type_azioni;
DROP TABLE port_type;
DROP TABLE accordi_azioni;
DROP TABLE accordi;
DROP TABLE documenti;
DROP SEQUENCE seq_acc_serv_componenti;
DROP SEQUENCE seq_acc_serv_composti;
DROP SEQUENCE seq_servizi_fruitori_azione;
DROP SEQUENCE seq_servizi_fruitori_azioni;
DROP SEQUENCE seq_servizi_fruitori;
DROP SEQUENCE seq_servizi_azione;
DROP SEQUENCE seq_servizi_azioni;
DROP SEQUENCE seq_servizi;
DROP SEQUENCE seq_accordi_coop_partecipanti;
DROP SEQUENCE seq_accordi_cooperazione;
DROP SEQUENCE seq_api_resources_parameter;
DROP SEQUENCE seq_api_resources_media;
DROP SEQUENCE seq_api_resources_response;
DROP SEQUENCE seq_api_resources;
DROP SEQUENCE seq_operation_messages;
DROP SEQUENCE seq_port_type_azioni;
DROP SEQUENCE seq_port_type;
DROP SEQUENCE seq_accordi_azioni;
DROP SEQUENCE seq_accordi;
DROP SEQUENCE seq_documenti;
