package org.openspcoop2.example.server.mtom.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2017-02-21T15:25:10.694+01:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://www.openspcoop2.org/example/server/mtom/ws", name = "MTOMServiceExample")
@XmlSeeAlso({org.openspcoop2.example.server.mtom.ObjectFactory.class})
public interface MTOMServiceExample {

    @RequestWrapper(localName = "echo", targetNamespace = "http://www.openspcoop2.org/example/server/mtom", className = "org.openspcoop2.example.server.mtom.Echo")
    @WebMethod(action = "echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://www.openspcoop2.org/example/server/mtom", className = "org.openspcoop2.example.server.mtom.EchoResponse")
    public void echo(
        @WebParam(name = "richiesta", targetNamespace = "http://www.openspcoop2.org/example/server/mtom")
        java.lang.String richiesta,
        @WebParam(name = "ImageData", targetNamespace = "http://www.openspcoop2.org/example/server/mtom")
        javax.xml.transform.Source imageData,
        @WebParam(name = "other", targetNamespace = "http://www.openspcoop2.org/example/server/mtom")
        java.util.List<javax.activation.DataHandler> other,
        @WebParam(mode = WebParam.Mode.OUT, name = "risposta", targetNamespace = "http://www.openspcoop2.org/example/server/mtom")
        javax.xml.ws.Holder<java.lang.String> risposta,
        @WebParam(mode = WebParam.Mode.OUT, name = "ImageDataResponse", targetNamespace = "http://www.openspcoop2.org/example/server/mtom")
        javax.xml.ws.Holder<javax.xml.transform.Source> imageDataResponse,
        @WebParam(mode = WebParam.Mode.OUT, name = "otherResponse", targetNamespace = "http://www.openspcoop2.org/example/server/mtom")
        javax.xml.ws.Holder<java.util.List<javax.activation.DataHandler>> otherResponse
    );
}
