-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_pa_trasf_hdr_resp_1;
-- DROP INDEX idx_pa_trasf_url_1;
-- DROP INDEX idx_pa_trasf_hdr_1;
-- DROP INDEX INDEX_PA_CACHE;
-- DROP INDEX INDEX_PA_SA_AUTH;
-- DROP INDEX INDEX_PA_CORR_RES;
-- DROP INDEX INDEX_PA_CORR_REQ;
-- DROP INDEX INDEX_PA_WSSRES;
-- DROP INDEX INDEX_PA_WSSREQ;
-- DROP INDEX INDEX_PA_MTOMTRES;
-- DROP INDEX INDEX_PA_MTOMTREQ;
-- DROP INDEX INDEX_PA_PROP;
-- DROP INDEX INDEX_PA_CT_PROP;
-- DROP INDEX idx_pa_ct_props_1;
-- DROP INDEX INDEX_PA_AUTHZC_PROP;
-- DROP INDEX INDEX_PA_AUTHZ_PROP;
-- DROP INDEX INDEX_PA_AUTH_PROP;
-- DROP INDEX INDEX_PA_BEHAVIOUR_PROP;
-- DROP INDEX INDEX_PA_SA_PROP;
-- DROP INDEX INDEX_PA_SA_CODA_MAX;
-- DROP INDEX INDEX_PA_SA_CODA;
-- DROP INDEX INDEX_PA_SA;
-- DROP INDEX index_porte_applicative_2;
-- DROP INDEX index_porte_applicative_1;
DROP TRIGGER trg_pa_aa;
DROP TRIGGER trg_pa_handlers;
DROP TRIGGER trg_pa_transform_risp_hdr;
DROP TRIGGER trg_pa_transform_risp;
DROP TRIGGER trg_pa_transform_url;
DROP TRIGGER trg_pa_transform_hdr;
DROP TRIGGER trg_pa_transform_sa;
DROP TRIGGER trg_pa_transform_soggetti;
DROP TRIGGER trg_pa_transform;
DROP TRIGGER trg_pa_cache_regole;
DROP TRIGGER trg_pa_azioni;
DROP TRIGGER trg_porte_applicative_sa_auth;
DROP TRIGGER trg_pa_soggetti;
DROP TRIGGER trg_pa_scope;
DROP TRIGGER trg_pa_ruoli;
DROP TRIGGER trg_pa_correlazione_risposta;
DROP TRIGGER trg_pa_correlazione;
DROP TRIGGER trg_pa_security_response;
DROP TRIGGER trg_pa_security_request;
DROP TRIGGER trg_pa_mtom_response;
DROP TRIGGER trg_pa_mtom_request;
DROP TRIGGER trg_pa_properties;
DROP TRIGGER trg_pa_ct_properties;
DROP TRIGGER trg_pa_authzc_properties;
DROP TRIGGER trg_pa_authz_properties;
DROP TRIGGER trg_pa_auth_properties;
DROP TRIGGER trg_pa_behaviour_props;
DROP TRIGGER trg_pa_sa_properties;
DROP TRIGGER trg_porte_applicative_sa;
DROP TRIGGER trg_porte_applicative;
DROP TABLE pa_aa;
DROP TABLE pa_handlers;
DROP TABLE pa_transform_risp_hdr;
DROP TABLE pa_transform_risp;
DROP TABLE pa_transform_url;
DROP TABLE pa_transform_hdr;
DROP TABLE pa_transform_sa;
DROP TABLE pa_transform_soggetti;
DROP TABLE pa_transform;
DROP TABLE pa_cache_regole;
DROP TABLE pa_azioni;
DROP TABLE porte_applicative_sa_auth;
DROP TABLE pa_soggetti;
DROP TABLE pa_scope;
DROP TABLE pa_ruoli;
DROP TABLE pa_correlazione_risposta;
DROP TABLE pa_correlazione;
DROP TABLE pa_security_response;
DROP TABLE pa_security_request;
DROP TABLE pa_mtom_response;
DROP TABLE pa_mtom_request;
DROP TABLE pa_properties;
DROP TABLE pa_ct_properties;
DROP TABLE pa_authzc_properties;
DROP TABLE pa_authz_properties;
DROP TABLE pa_auth_properties;
DROP TABLE pa_behaviour_props;
DROP TABLE pa_sa_properties;
DROP TABLE porte_applicative_sa;
DROP TABLE porte_applicative;
DROP SEQUENCE seq_pa_aa;
DROP SEQUENCE seq_pa_handlers;
DROP SEQUENCE seq_pa_transform_risp_hdr;
DROP SEQUENCE seq_pa_transform_risp;
DROP SEQUENCE seq_pa_transform_url;
DROP SEQUENCE seq_pa_transform_hdr;
DROP SEQUENCE seq_pa_transform_sa;
DROP SEQUENCE seq_pa_transform_soggetti;
DROP SEQUENCE seq_pa_transform;
DROP SEQUENCE seq_pa_cache_regole;
DROP SEQUENCE seq_pa_azioni;
DROP SEQUENCE seq_porte_applicative_sa_auth;
DROP SEQUENCE seq_pa_soggetti;
DROP SEQUENCE seq_pa_scope;
DROP SEQUENCE seq_pa_ruoli;
DROP SEQUENCE seq_pa_correlazione_risposta;
DROP SEQUENCE seq_pa_correlazione;
DROP SEQUENCE seq_pa_security_response;
DROP SEQUENCE seq_pa_security_request;
DROP SEQUENCE seq_pa_mtom_response;
DROP SEQUENCE seq_pa_mtom_request;
DROP SEQUENCE seq_pa_properties;
DROP SEQUENCE seq_pa_ct_properties;
DROP SEQUENCE seq_pa_authzc_properties;
DROP SEQUENCE seq_pa_authz_properties;
DROP SEQUENCE seq_pa_auth_properties;
DROP SEQUENCE seq_pa_behaviour_props;
DROP SEQUENCE seq_pa_sa_properties;
DROP SEQUENCE seq_porte_applicative_sa;
DROP SEQUENCE seq_porte_applicative;
