CREATE SEQUENCE seq_statistiche AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;
ALTER TABLE statistiche ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
UPDATE statistiche SET id = NEXT VALUE FOR seq_statistiche;
ALTER TABLE statistiche ALTER COLUMN id SET NOT NULL;
ALTER TABLE statistiche ADD CONSTRAINT pk_statistiche PRIMARY KEY (id);
CREATE TABLE statistiche_init_seq (id BIGINT);
INSERT INTO statistiche_init_seq VALUES (NEXT VALUE FOR seq_statistiche);

