-- Il bug provocava duplici inserimenti con stessi dati della chiave primaria (escludendo il counter). 
-- Se esistono entry con stessi dati di chiave primaria, prima di applicare la patch devono essere eliminate
-- DELETE FROM ID_MESSAGGIO;
-- DELETE FROM ID_MESSAGGIO_RELATIVO;
-- DELETE FROM ID_MESSAGGIO_PRG;
-- DELETE FROM ID_MESSAGGIO_RELATIVO_PRG;

ALTER TABLE ID_MESSAGGIO DROP PRIMARY KEY;
ALTER TABLE ID_MESSAGGIO ADD CONSTRAINT pk_ID_MESSAGGIO PRIMARY KEY (PROTOCOLLO);

ALTER TABLE ID_MESSAGGIO_RELATIVO DROP PRIMARY KEY;
ALTER TABLE ID_MESSAGGIO_RELATIVO ADD CONSTRAINT pk_ID_MESSAGGIO_RELATIVO PRIMARY KEY (PROTOCOLLO,INFO_ASSOCIATA);

ALTER TABLE ID_MESSAGGIO_PRG DROP PRIMARY KEY;
ALTER TABLE ID_MESSAGGIO_PRG ADD CONSTRAINT pk_ID_MESSAGGIO_PRG PRIMARY KEY (PROTOCOLLO);

ALTER TABLE ID_MESSAGGIO_RELATIVO_PRG DROP PRIMARY KEY;
ALTER TABLE ID_MESSAGGIO_RELATIVO_PRG ADD CONSTRAINT pk_ID_MESSAGGIO_RELATIVO_PRG PRIMARY KEY (PROTOCOLLO,INFO_ASSOCIATA);

