-- Precisione ai millisecondi supportata dalla versione 5.6.4, se si utilizza una versione precedente non usare il suffisso '(3)'
ALTER TABLE ID_MESSAGGIO ADD COLUMN ora_registrazione TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3); 
ALTER TABLE ID_MESSAGGIO_RELATIVO ADD COLUMN ora_registrazione TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE ID_MESSAGGIO_PRG ADD COLUMN ora_registrazione TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE ID_MESSAGGIO_RELATIVO_PRG ADD COLUMN ora_registrazione TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3);
