ALTER TABLE REPOSITORY_BUSTE MODIFY COLUMN TIPO_MITTENTE VARCHAR(255) NULL;
ALTER TABLE REPOSITORY_BUSTE MODIFY COLUMN MITTENTE VARCHAR(255) NULL;
ALTER TABLE REPOSITORY_BUSTE MODIFY COLUMN TIPO_DESTINATARIO VARCHAR(255) NULL;
ALTER TABLE REPOSITORY_BUSTE MODIFY COLUMN DESTINATARIO VARCHAR(255) NULL;
