ALTER TABLE DEFINIZIONE_MESSAGGI ADD COLUMN RESPONSE_CONTENT_TYPE VARCHAR(255);
ALTER TABLE DEFINIZIONE_MESSAGGI ADD COLUMN RESPONSE_MSG_BYTES MEDIUMBLOB;
ALTER TABLE DEFINIZIONE_MESSAGGI ADD COLUMN RESPONSE_MSG_CONTEXT MEDIUMBLOB;
