-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
DROP TABLE ID_MESSAGGIO_RELATIVO_PRG;
DROP TABLE ID_MESSAGGIO_PRG;
DROP TABLE ID_MESSAGGIO_RELATIVO;
DROP TABLE ID_MESSAGGIO;
