ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN TIPO_MITTENTE VARCHAR(255) NULL; 
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN MITTENTE VARCHAR(255) NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN TIPO_DESTINATARIO VARCHAR(255) NULL;
ALTER TABLE REPOSITORY_BUSTE ALTER COLUMN DESTINATARIO VARCHAR(255) NULL;

