ALTER TABLE OP2_SEMAPHORE ALTER COLUMN applicative_id VARCHAR(255) NOT NULL;
ALTER TABLE OP2_SEMAPHORE ADD CONSTRAINT uniq_semaphore_1 UNIQUE (applicative_id);
CREATE UNIQUE INDEX idx_semaphore_1 ON OP2_SEMAPHORE (applicative_id);
