ALTER TABLE DEFINIZIONE_MESSAGGI ADD RESPONSE_CONTENT_TYPE VARCHAR(255);
ALTER TABLE DEFINIZIONE_MESSAGGI ADD RESPONSE_MSG_BYTES VARBINARY(MAX);
ALTER TABLE DEFINIZIONE_MESSAGGI ADD RESPONSE_MSG_CONTEXT VARBINARY(MAX);
