DROP INDEX MSG_SERV_APPL_LIST ON MSG_SERVIZI_APPLICATIVI;
DROP INDEX MSG_SERV_APPL_GET_IM_MSG_ID ON MSG_SERVIZI_APPLICATIVI;
DROP INDEX MSG_SERV_APPL_ACQUIRE_SEND ON MSG_SERVIZI_APPLICATIVI;
ALTER TABLE MSG_SERVIZI_APPLICATIVI DROP CONSTRAINT pk_MSG_SERVIZI_APPLICATIVI;
ALTER TABLE MSG_SERVIZI_APPLICATIVI ALTER COLUMN SERVIZIO_APPLICATIVO VARCHAR(645) NOT NULL;
ALTER TABLE MSG_SERVIZI_APPLICATIVI ADD CONSTRAINT pk_MSG_SERVIZI_APPLICATIVI PRIMARY KEY (ID_MESSAGGIO,SERVIZIO_APPLICATIVO);
CREATE INDEX MSG_SERV_APPL_LIST ON MSG_SERVIZI_APPLICATIVI (SERVIZIO_APPLICATIVO,INTEGRATION_MANAGER);
CREATE INDEX MSG_SERV_APPL_GET_IM_MSG_ID ON MSG_SERVIZI_APPLICATIVI (ID_MESSAGGIO,SERVIZIO_APPLICATIVO,INTEGRATION_MANAGER);
CREATE INDEX MSG_SERV_APPL_ACQUIRE_SEND ON MSG_SERVIZI_APPLICATIVI (ID_MESSAGGIO,TIPO_CONSEGNA,ATTESA_ESITO,CODA,PRIORITA,SERVIZIO_APPLICATIVO,ERRORE_PROCESSAMENTO_COMPACT,RISPEDIZIONE,LOCK_CONSEGNA);

ALTER TABLE SEQUENZA_DA_INVIARE DROP CONSTRAINT pk_SEQUENZA_DA_INVIARE;
ALTER TABLE SEQUENZA_DA_INVIARE ALTER COLUMN MITTENTE VARCHAR(80) NOT NULL;
ALTER TABLE SEQUENZA_DA_INVIARE ALTER COLUMN TIPO_MITTENTE VARCHAR(20) NOT NULL;
ALTER TABLE SEQUENZA_DA_INVIARE ALTER COLUMN DESTINATARIO VARCHAR(80) NOT NULL;
ALTER TABLE SEQUENZA_DA_INVIARE ALTER COLUMN TIPO_DESTINATARIO VARCHAR(20) NOT NULL;
ALTER TABLE SEQUENZA_DA_INVIARE ALTER COLUMN TIPO_SERVIZIO VARCHAR(20) NOT NULL;
ALTER TABLE SEQUENZA_DA_INVIARE ADD CONSTRAINT pk_SEQUENZA_DA_INVIARE PRIMARY KEY (MITTENTE,TIPO_MITTENTE,DESTINATARIO,TIPO_DESTINATARIO,SERVIZIO,TIPO_SERVIZIO,AZIONE);

ALTER TABLE SEQUENZA_DA_RICEVERE ALTER COLUMN MITTENTE VARCHAR(80) NOT NULL;
ALTER TABLE SEQUENZA_DA_RICEVERE ALTER COLUMN TIPO_MITTENTE VARCHAR(20) NOT NULL;
ALTER TABLE SEQUENZA_DA_RICEVERE ALTER COLUMN DESTINATARIO VARCHAR(80) NOT NULL;
ALTER TABLE SEQUENZA_DA_RICEVERE ALTER COLUMN TIPO_DESTINATARIO VARCHAR(20) NOT NULL;
ALTER TABLE SEQUENZA_DA_RICEVERE ALTER COLUMN TIPO_SERVIZIO VARCHAR(20) NOT NULL;
