-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_pd_trasf_resp_2 ON pd_transform_risp ;
-- DROP INDEX idx_pd_trasf_resp_1 ON pd_transform_risp ;
-- DROP INDEX index_pd_transform_sa_1 ON pd_transform_sa ;
-- DROP INDEX index_pd_transform_2 ON pd_transform ;
-- DROP INDEX index_pd_transform_1 ON pd_transform ;
-- DROP INDEX index_pd_azioni_1 ON pd_azioni ;
-- DROP INDEX index_pd_scope_1 ON pd_scope ;
-- DROP INDEX index_pd_ruoli_1 ON pd_ruoli ;
-- DROP INDEX index_porte_delegate_1 ON porte_delegate ;
-- DROP INDEX idx_pd_trasf_hdr_resp_1 ON pd_transform_risp_hdr ;
-- DROP INDEX idx_pd_trasf_url_1 ON pd_transform_url ;
-- DROP INDEX idx_pd_trasf_hdr_1 ON pd_transform_hdr ;
-- DROP INDEX INDEX_PD_CACHE ON pd_cache_regole ;
-- DROP INDEX INDEX_PD_CORR_RES ON pd_correlazione_risposta ;
-- DROP INDEX INDEX_PD_CORR_REQ ON pd_correlazione ;
-- DROP INDEX INDEX_PD_WSSRES ON pd_security_response ;
-- DROP INDEX INDEX_PD_WSSREQ ON pd_security_request ;
-- DROP INDEX INDEX_PD_MTOMTRES ON pd_mtom_response ;
-- DROP INDEX INDEX_PD_MTOMTREQ ON pd_mtom_request ;
-- DROP INDEX INDEX_PD_PROP ON pd_properties ;
-- DROP INDEX INDEX_PD_AUTHZC_PROP ON pd_authzc_properties ;
-- DROP INDEX INDEX_PD_AUTHZ_PROP ON pd_authz_properties ;
-- DROP INDEX INDEX_PD_AUTH_PROP ON pd_auth_properties ;
-- DROP INDEX INDEX_PD_SA ON porte_delegate_sa ;
-- DROP INDEX index_porte_delegate_3 ON porte_delegate ;
-- DROP INDEX index_porte_delegate_2 ON porte_delegate ;
DROP TABLE pd_transform_risp_hdr;
DROP TABLE pd_transform_risp;
DROP TABLE pd_transform_url;
DROP TABLE pd_transform_hdr;
DROP TABLE pd_transform_sa;
DROP TABLE pd_transform;
DROP TABLE pd_cache_regole;
DROP TABLE pd_azioni;
DROP TABLE pd_scope;
DROP TABLE pd_ruoli;
DROP TABLE pd_correlazione_risposta;
DROP TABLE pd_correlazione;
DROP TABLE pd_security_response;
DROP TABLE pd_security_request;
DROP TABLE pd_mtom_response;
DROP TABLE pd_mtom_request;
DROP TABLE pd_properties;
DROP TABLE pd_authzc_properties;
DROP TABLE pd_authz_properties;
DROP TABLE pd_auth_properties;
DROP TABLE porte_delegate_sa;
DROP TABLE porte_delegate;
