-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_remote_store_key_1 ON remote_store_key ;
-- DROP INDEX index_remote_store_1 ON remote_store ;
-- DROP INDEX index_nodi_runtime_2 ON nodi_runtime ;
-- DROP INDEX index_nodi_runtime_1 ON nodi_runtime ;
-- DROP INDEX index_config_handlers_1 ON config_handlers ;
-- DROP INDEX index_registro_plugins_1 ON registro_plugins ;
-- DROP INDEX index_generic_properties_1 ON generic_properties ;
-- DROP INDEX index_pdd_sys_props_1 ON pdd_sys_props ;
-- DROP INDEX index_servizi_pdd_1 ON servizi_pdd ;
-- DROP INDEX index_config_url_regole_1 ON config_url_regole ;
-- DROP INDEX REMOTE_STORE_CREATE ON remote_store_key ;
-- DROP INDEX REMOTE_STORE_UPDATE ON remote_store_key ;
-- DROP INDEX INDEX_NODI_OP ON nodi_runtime_operations ;
-- DROP INDEX index_registro_plug_jar_1 ON registro_plug_jar ;
-- DROP INDEX index_generic_property_1 ON generic_property ;
-- DROP INDEX index_dump_config_1 ON dump_config ;
-- DROP INDEX index_filetrace_config_1 ON filetrace_config ;
-- DROP INDEX index_tracce_config_1 ON tracce_config ;
DROP TABLE remote_store_key;
DROP TABLE remote_store;
DROP TABLE nodi_runtime_operations;
DROP TABLE nodi_runtime;
DROP TABLE config_handlers;
DROP TABLE registro_plug_jar;
DROP TABLE registro_plugins;
DROP TABLE canali_nodi;
DROP TABLE canali_configurazione;
DROP TABLE generic_property;
DROP TABLE generic_properties;
DROP TABLE pdd_sys_props;
DROP TABLE servizi_pdd_filtri;
DROP TABLE servizi_pdd;
DROP TABLE tracce_ds_prop;
DROP TABLE tracce_ds;
DROP TABLE msgdiag_ds_prop;
DROP TABLE msgdiag_ds;
DROP TABLE dump_appender_prop;
DROP TABLE dump_appender;
DROP TABLE dump_config_regola;
DROP TABLE dump_config;
DROP TABLE filetrace_config;
DROP TABLE tracce_config;
DROP TABLE tracce_appender_prop;
DROP TABLE tracce_appender;
DROP TABLE msgdiag_appender_prop;
DROP TABLE msgdiag_appender;
DROP TABLE config_url_regole;
DROP TABLE config_url_invocazione;
DROP TABLE configurazione;
DROP TABLE config_cache_regole;
DROP TABLE routing;
DROP TABLE registri;
