-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_pa_trasf_resp_2 ON pa_transform_risp ;
-- DROP INDEX idx_pa_trasf_resp_1 ON pa_transform_risp ;
-- DROP INDEX index_pa_transform_sa_1 ON pa_transform_sa ;
-- DROP INDEX index_pa_transform_soggetti_1 ON pa_transform_soggetti ;
-- DROP INDEX index_pa_transform_2 ON pa_transform ;
-- DROP INDEX index_pa_transform_1 ON pa_transform ;
-- DROP INDEX index_pa_azioni_1 ON pa_azioni ;
-- DROP INDEX index_pa_soggetti_1 ON pa_soggetti ;
-- DROP INDEX index_pa_scope_1 ON pa_scope ;
-- DROP INDEX index_pa_ruoli_1 ON pa_ruoli ;
-- DROP INDEX index_porte_applicative_1 ON porte_applicative ;
-- DROP INDEX idx_pa_trasf_hdr_resp_1 ON pa_transform_risp_hdr ;
-- DROP INDEX idx_pa_trasf_url_1 ON pa_transform_url ;
-- DROP INDEX idx_pa_trasf_hdr_1 ON pa_transform_hdr ;
-- DROP INDEX INDEX_PA_CACHE ON pa_cache_regole ;
-- DROP INDEX INDEX_PA_SA_AUTH ON porte_applicative_sa_auth ;
-- DROP INDEX INDEX_PA_CORR_RES ON pa_correlazione_risposta ;
-- DROP INDEX INDEX_PA_CORR_REQ ON pa_correlazione ;
-- DROP INDEX INDEX_PA_WSSRES ON pa_security_response ;
-- DROP INDEX INDEX_PA_WSSREQ ON pa_security_request ;
-- DROP INDEX INDEX_PA_MTOMTRES ON pa_mtom_response ;
-- DROP INDEX INDEX_PA_MTOMTREQ ON pa_mtom_request ;
-- DROP INDEX INDEX_PA_PROP ON pa_properties ;
-- DROP INDEX INDEX_PA_AUTHZC_PROP ON pa_authzc_properties ;
-- DROP INDEX INDEX_PA_AUTHZ_PROP ON pa_authz_properties ;
-- DROP INDEX INDEX_PA_AUTH_PROP ON pa_auth_properties ;
-- DROP INDEX INDEX_PA_BEHAVIOUR_PROP ON pa_behaviour_props ;
-- DROP INDEX INDEX_PA_SA_PROP ON pa_sa_properties ;
-- DROP INDEX INDEX_PA_SA ON porte_applicative_sa ;
-- DROP INDEX index_porte_applicative_2 ON porte_applicative ;
DROP TABLE pa_transform_risp_hdr;
DROP TABLE pa_transform_risp;
DROP TABLE pa_transform_url;
DROP TABLE pa_transform_hdr;
DROP TABLE pa_transform_sa;
DROP TABLE pa_transform_soggetti;
DROP TABLE pa_transform;
DROP TABLE pa_cache_regole;
DROP TABLE pa_azioni;
DROP TABLE porte_applicative_sa_auth;
DROP TABLE pa_soggetti;
DROP TABLE pa_scope;
DROP TABLE pa_ruoli;
DROP TABLE pa_correlazione_risposta;
DROP TABLE pa_correlazione;
DROP TABLE pa_security_response;
DROP TABLE pa_security_request;
DROP TABLE pa_mtom_response;
DROP TABLE pa_mtom_request;
DROP TABLE pa_properties;
DROP TABLE pa_authzc_properties;
DROP TABLE pa_authz_properties;
DROP TABLE pa_auth_properties;
DROP TABLE pa_behaviour_props;
DROP TABLE pa_sa_properties;
DROP TABLE porte_applicative_sa;
DROP TABLE porte_applicative;
