
CREATE SEQUENCE seq_LISTA_EXT_PROTOCOL_INFO MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 INCREMENT BY 1 CACHE 2 CYCLE;

CREATE TABLE LISTA_EXT_PROTOCOL_INFO
(
        ID_MESSAGGIO VARCHAR(255) NOT NULL,
        TIPO VARCHAR(255) NOT NULL,
        NOME VARCHAR(255) NOT NULL,
        VALORE CLOB NOT NULL,
        -- fk/pk columns
        id NUMBER NOT NULL,
        -- check constraints
        CONSTRAINT chk_LISTA_EXT_PROTOCOL_INFO_1 CHECK (TIPO IN ('INBOX','OUTBOX')),
        -- fk/pk keys constraints
        CONSTRAINT fk_LISTA_EXT_PROTOCOL_INFO_1 FOREIGN KEY (ID_MESSAGGIO,TIPO) REFERENCES REPOSITORY_BUSTE(ID_MESSAGGIO,TIPO) ON DELETE CASCADE,
        CONSTRAINT pk_LISTA_EXT_PROTOCOL_INFO PRIMARY KEY (id)
);

-- index
CREATE INDEX LISTA_EXT_ID ON LISTA_EXT_PROTOCOL_INFO (ID_MESSAGGIO,TIPO);
CREATE TRIGGER trg_LISTA_EXT_PROTOCOL_INFO
BEFORE
insert on LISTA_EXT_PROTOCOL_INFO
for each row
begin
   IF (:new.id IS NULL) THEN
      SELECT seq_LISTA_EXT_PROTOCOL_INFO.nextval INTO :new.id
                FROM DUAL;
   END IF;
end;
/


