ALTER TABLE REPOSITORY_BUSTE MODIFY (TIPO_MITTENTE NULL);
ALTER TABLE REPOSITORY_BUSTE MODIFY (MITTENTE NULL);
ALTER TABLE REPOSITORY_BUSTE MODIFY (TIPO_DESTINATARIO NULL);
ALTER TABLE REPOSITORY_BUSTE MODIFY (DESTINATARIO NULL);
