CREATE INDEX MESSAGGI_ACQUIRE_SEND ON MESSAGGI (ORA_REGISTRAZIONE,PROPRIETARIO,TIPO,ID_MESSAGGIO);

ALTER TABLE MSG_SERVIZI_APPLICATIVI MODIFY TIPO_CONSEGNA VARCHAR2(40);

UPDATE MSG_SERVIZI_APPLICATIVI SET ATTESA_ESITO=0 WHERE ATTESA_ESITO IS NULL;
ALTER TABLE MSG_SERVIZI_APPLICATIVI MODIFY ATTESA_ESITO NOT NULL;
ALTER TABLE MSG_SERVIZI_APPLICATIVI MODIFY ATTESA_ESITO DEFAULT 0;

ALTER TABLE MSG_SERVIZI_APPLICATIVI ADD CODA VARCHAR2(10);
ALTER TABLE MSG_SERVIZI_APPLICATIVI ADD PRIORITA VARCHAR2(10);
UPDATE MSG_SERVIZI_APPLICATIVI SET CODA='DEFAULT';
UPDATE MSG_SERVIZI_APPLICATIVI SET PRIORITA='DEFAULT';
ALTER TABLE MSG_SERVIZI_APPLICATIVI MODIFY CODA DEFAULT 'UNSET';
ALTER TABLE MSG_SERVIZI_APPLICATIVI MODIFY PRIORITA DEFAULT 'UNSET';

DROP INDEX MSG_SERV_APPL_ACQUIRE_SEND;
CREATE INDEX MSG_SERV_APPL_ACQUIRE_SEND ON MSG_SERVIZI_APPLICATIVI (ID_MESSAGGIO,TIPO_CONSEGNA,ATTESA_ESITO,CODA,PRIORITA,SERVIZIO_APPLICATIVO,ERRORE_PROCESSAMENTO_COMPACT,RISPEDIZIONE,LOCK_CONSEGNA);
DROP INDEX MSG_SERV_APPL_RELEASE_SEND;
CREATE INDEX MSG_SERV_APPL_RELEASE_SEND ON MSG_SERVIZI_APPLICATIVI (CLUSTER_ID,CODA,LOCK_CONSEGNA);
