ALTER TABLE DEFINIZIONE_MESSAGGI ADD RESPONSE_CONTENT_TYPE VARCHAR2(255);
ALTER TABLE DEFINIZIONE_MESSAGGI ADD RESPONSE_MSG_BYTES BLOB;
ALTER TABLE DEFINIZIONE_MESSAGGI ADD RESPONSE_MSG_CONTEXT BLOB;
