-- **** Interazioni Asincrone PDND ****

CREATE SEQUENCE seq_PDND_INTERAZIONI_ASYNC MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 INCREMENT BY 1 CACHE 2 CYCLE;

CREATE TABLE PDND_INTERAZIONI_ASYNC
(
	INTERACTION_ID VARCHAR2(255) NOT NULL,
	RUOLO VARCHAR2(255) NOT NULL,
	FASE VARCHAR2(255) NOT NULL,
	TIPO_FRUITORE VARCHAR2(255),
	FRUITORE VARCHAR2(255),
	TIPO_EROGATORE VARCHAR2(255) NOT NULL,
	EROGATORE VARCHAR2(255) NOT NULL,
	TIPO_SERVIZIO VARCHAR2(255) NOT NULL,
	SERVIZIO VARCHAR2(255) NOT NULL,
	VERSIONE_SERVIZIO NUMBER NOT NULL,
	TIPO_SERVIZIO_CALLBACK VARCHAR2(255),
	SERVIZIO_CALLBACK VARCHAR2(255),
	VERSIONE_SERVIZIO_CALLBACK NUMBER,
	PURPOSE_ID VARCHAR2(255),
	CONSUMER_ID VARCHAR2(255),
	CLIENT_ID VARCHAR2(255),
	URL_CALLBACK VARCHAR2(4000),
	ENTITY_NUMBER NUMBER,
	TEMPO_MAX_CALLBACK NUMBER,
	TEMPO_DISPONIBILITA NUMBER,
	CONFERMA_RICHIESTA NUMBER NOT NULL,
	LIMITE_ENTITA NUMBER,
	NUMERO_GET_RESOURCE NUMBER NOT NULL,
	ID_TRANSAZIONE_START VARCHAR2(255),
	DATA_START TIMESTAMP NOT NULL,
	DATA_CALLBACK TIMESTAMP,
	DATA_GET_RESOURCE TIMESTAMP,
	DATA_CONFIRMATION TIMESTAMP,
	DATA_SCADENZA TIMESTAMP,
	DATA_AGGIORNAMENTO TIMESTAMP NOT NULL,
	-- fk/pk columns
	id NUMBER NOT NULL,
	-- unique constraints
	CONSTRAINT uniq_pdnd_async_1 UNIQUE (INTERACTION_ID,RUOLO),
	-- fk/pk keys constraints
	CONSTRAINT pk_PDND_INTERAZIONI_ASYNC PRIMARY KEY (id)
);

-- index
CREATE INDEX PDND_ASYNC_SCADENZA ON PDND_INTERAZIONI_ASYNC (DATA_SCADENZA);
CREATE INDEX PDND_ASYNC_AGGIORNAMENTO ON PDND_INTERAZIONI_ASYNC (DATA_AGGIORNAMENTO);
CREATE INDEX PDND_ASYNC_SEARCH ON PDND_INTERAZIONI_ASYNC (DATA_START,RUOLO);

ALTER TABLE PDND_INTERAZIONI_ASYNC MODIFY CONFERMA_RICHIESTA DEFAULT 0;
ALTER TABLE PDND_INTERAZIONI_ASYNC MODIFY NUMERO_GET_RESOURCE DEFAULT 0;

CREATE TRIGGER trg_PDND_INTERAZIONI_ASYNC
BEFORE
insert on PDND_INTERAZIONI_ASYNC
for each row
begin
   IF (:new.id IS NULL) THEN
      SELECT seq_PDND_INTERAZIONI_ASYNC.nextval INTO :new.id
                FROM DUAL;
   END IF;
end;
/
