-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_acc_serv_composti_1 ON acc_serv_composti ;
-- DROP INDEX index_serv_fru_azione_1 ON servizi_fruitori_azione ;
-- DROP INDEX index_servizi_fruitori_1 ON servizi_fruitori ;
-- DROP INDEX index_servizi_azione_1 ON servizi_azione ;
-- DROP INDEX index_servizi_1 ON servizi ;
-- DROP INDEX index_accordi_cooperazione_1 ON accordi_cooperazione ;
-- DROP INDEX idx_acc_gruppi_1 ON accordi_gruppi ;
-- DROP INDEX index_api_resp_1 ON api_resources_response ;
-- DROP INDEX index_api_resources_2 ON api_resources ;
-- DROP INDEX index_api_resources_1 ON api_resources ;
-- DROP INDEX index_port_type_azioni_1 ON port_type_azioni ;
-- DROP INDEX index_port_type_1 ON port_type ;
-- DROP INDEX index_accordi_azioni_1 ON accordi_azioni ;
-- DROP INDEX index_accordi_1 ON accordi ;
-- DROP INDEX index_documenti_1 ON documenti ;
-- DROP INDEX INDEX_AC_SC_SERV ON acc_serv_componenti ;
-- DROP INDEX INDEX_AC_SC_SC ON acc_serv_componenti ;
-- DROP INDEX INDEX_AC_SC ON acc_serv_composti ;
-- DROP INDEX index_serv_fru_azioni_1 ON servizi_fruitori_azioni ;
-- DROP INDEX INDEX_SERV_FRU_SOG ON servizi_fruitori ;
-- DROP INDEX index_servizi_azioni_1 ON servizi_azioni ;
-- DROP INDEX INDEX_SERV_SOG ON servizi ;
-- DROP INDEX INDEX_SERV_ACC ON servizi ;
-- DROP INDEX INDEX_AC_SOG ON accordi_coop_partecipanti ;
-- DROP INDEX INDEX_AC_COOP_PAR ON accordi_coop_partecipanti ;
-- DROP INDEX INDEX_OP_MESSAGES ON operation_messages ;
-- DROP INDEX index_accordi_2 ON accordi ;
-- DROP INDEX INDEX_DOC_SEARCH ON documenti ;
DROP TABLE acc_serv_componenti;
DROP TABLE acc_serv_composti;
DROP TABLE servizi_fruitori_azione;
DROP TABLE servizi_fruitori_azioni;
DROP TABLE servizi_fruitori;
DROP TABLE servizi_azione;
DROP TABLE servizi_azioni;
DROP TABLE servizi;
DROP TABLE accordi_coop_partecipanti;
DROP TABLE accordi_cooperazione;
DROP TABLE accordi_gruppi;
DROP TABLE api_resources_parameter;
DROP TABLE api_resources_media;
DROP TABLE api_resources_response;
DROP TABLE api_resources;
DROP TABLE operation_messages;
DROP TABLE port_type_azioni;
DROP TABLE port_type;
DROP TABLE accordi_azioni;
DROP TABLE accordi;
DROP TABLE documenti;
