-- **** Ruoli ****

CREATE SEQUENCE seq_ruoli AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;

CREATE TABLE ruoli
(
	nome VARCHAR(255) NOT NULL,
	descrizione VARCHAR(4000),
	tipologia VARCHAR(255) NOT NULL,
	nome_esterno VARCHAR(255),
	contesto_utilizzo VARCHAR(255) NOT NULL,
	superuser VARCHAR(255),
	ora_registrazione TIMESTAMP,
	utente_richiedente VARCHAR(255),
	data_creazione TIMESTAMP,
	utente_ultima_modifica VARCHAR(255),
	data_ultima_modifica TIMESTAMP,
	-- fk/pk columns
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	-- check constraints
	CONSTRAINT chk_ruoli_1 CHECK (tipologia IN ('interno','esterno','qualsiasi')),
	CONSTRAINT chk_ruoli_2 CHECK (contesto_utilizzo IN ('portaDelegata','portaApplicativa','qualsiasi')),
	-- unique constraints
	CONSTRAINT unique_ruoli_1 UNIQUE (nome),
	-- fk/pk keys constraints
	CONSTRAINT pk_ruoli PRIMARY KEY (id)
);

-- index
CREATE UNIQUE INDEX index_ruoli_1 ON ruoli (nome);

ALTER TABLE ruoli ALTER COLUMN tipologia SET DEFAULT 'qualsiasi';
ALTER TABLE ruoli ALTER COLUMN contesto_utilizzo SET DEFAULT 'qualsiasi';
ALTER TABLE ruoli ALTER COLUMN ora_registrazione SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE ruoli_init_seq (id BIGINT);
INSERT INTO ruoli_init_seq VALUES (NEXT VALUE FOR seq_ruoli);


