//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.11 at 06:22:00 PM CEST 
//


package org.openspcoop2.web.monitor.transazioni.core.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for filtro-contenuti complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filtro-contenuti">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="risorsa" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="nome" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ricerca-personalizzata" type="{http://www.openspcoop2.org/web/monitor/transazioni/core/search}ricerca-personalizzata" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filtro-contenuti", namespace = "http://www.openspcoop2.org/web/monitor/transazioni/core/search", propOrder = {
    "stato",
    "risorsa",
    "ricercaPersonalizzata"
})
public class FiltroContenuti {

    @XmlElement(namespace = "http://www.openspcoop2.org/web/monitor/transazioni/core/search")
    protected String stato;
    @XmlElement(namespace = "http://www.openspcoop2.org/web/monitor/transazioni/core/search")
    protected FiltroContenuti.Risorsa risorsa;
    @XmlElement(name = "ricerca-personalizzata", namespace = "http://www.openspcoop2.org/web/monitor/transazioni/core/search")
    protected RicercaPersonalizzata ricercaPersonalizzata;

    /**
     * Gets the value of the stato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStato() {
        return this.stato;
    }

    /**
     * Sets the value of the stato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStato(String value) {
        this.stato = value;
    }

    /**
     * Gets the value of the risorsa property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroContenuti.Risorsa }
     *     
     */
    public FiltroContenuti.Risorsa getRisorsa() {
        return this.risorsa;
    }

    /**
     * Sets the value of the risorsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroContenuti.Risorsa }
     *     
     */
    public void setRisorsa(FiltroContenuti.Risorsa value) {
        this.risorsa = value;
    }

    /**
     * Gets the value of the ricercaPersonalizzata property.
     * 
     * @return
     *     possible object is
     *     {@link RicercaPersonalizzata }
     *     
     */
    public RicercaPersonalizzata getRicercaPersonalizzata() {
        return this.ricercaPersonalizzata;
    }

    /**
     * Sets the value of the ricercaPersonalizzata property.
     * 
     * @param value
     *     allowed object is
     *     {@link RicercaPersonalizzata }
     *     
     */
    public void setRicercaPersonalizzata(RicercaPersonalizzata value) {
        this.ricercaPersonalizzata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="nome" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Risorsa {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "nome", required = true)
        protected String nome;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return this.value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the nome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNome() {
            return this.nome;
        }

        /**
         * Sets the value of the nome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNome(String value) {
            this.nome = value;
        }

    }

}
