/*
 * GovWay - A customizable API Gateway 
 * https://govway.org
 * 
 * Copyright (c) 2005-2020 Link.it srl (https://link.it).
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 04:38:18 PM CEST 
//


package org.openspcoop2.web.monitor.transazioni.core.search;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openspcoop2.web.monitor.transazioni.core.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 * @author Pintori Giuliano (pintori@link.it)
 * @author $Author$
 * @version $Rev$, $Date$
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Transazione_QNAME = new QName("http://www.openspcoop2.org/web/monitor/transazioni/core/search", "transazione");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openspcoop2.web.monitor.transazioni.core.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FiltroContenuti }
     * 
     */
    public FiltroContenuti createFiltroContenuti() {
        return new FiltroContenuti();
    }

    /**
     * Create an instance of {@link RicercaPersonalizzata }
     * 
     */
    public RicercaPersonalizzata createRicercaPersonalizzata() {
        return new RicercaPersonalizzata();
    }

    /**
     * Create an instance of {@link TransazioneType }
     * 
     */
    public TransazioneType createTransazioneType() {
        return new TransazioneType();
    }

    /**
     * Create an instance of {@link FiltroContenuti.Risorsa }
     * 
     */
    public FiltroContenuti.Risorsa createFiltroContenutiRisorsa() {
        return new FiltroContenuti.Risorsa();
    }

    /**
     * Create an instance of {@link RicercaPersonalizzata.Parameter }
     * 
     */
    public RicercaPersonalizzata.Parameter createRicercaPersonalizzataParameter() {
        return new RicercaPersonalizzata.Parameter();
    }

    /**
     * Create an instance of {@link TransazioneType.Periodo }
     * 
     */
    public TransazioneType.Periodo createTransazioneTypePeriodo() {
        return new TransazioneType.Periodo();
    }

    /**
     * Create an instance of {@link TransazioneType.SoggettoLocale }
     * 
     */
    public TransazioneType.SoggettoLocale createTransazioneTypeSoggettoLocale() {
        return new TransazioneType.SoggettoLocale();
    }

    /**
     * Create an instance of {@link TransazioneType.SoggettoRemoto }
     * 
     */
    public TransazioneType.SoggettoRemoto createTransazioneTypeSoggettoRemoto() {
        return new TransazioneType.SoggettoRemoto();
    }

    /**
     * Create an instance of {@link TransazioneType.SoggettoMittente }
     * 
     */
    public TransazioneType.SoggettoMittente createTransazioneTypeSoggettoMittente() {
        return new TransazioneType.SoggettoMittente();
    }

    /**
     * Create an instance of {@link TransazioneType.SoggettoDestinatario }
     * 
     */
    public TransazioneType.SoggettoDestinatario createTransazioneTypeSoggettoDestinatario() {
        return new TransazioneType.SoggettoDestinatario();
    }

    /**
     * Create an instance of {@link TransazioneType.Esito }
     * 
     */
    public TransazioneType.Esito createTransazioneTypeEsito() {
        return new TransazioneType.Esito();
    }

    /**
     * Create an instance of {@link TransazioneType.Contesto }
     * 
     */
    public TransazioneType.Contesto createTransazioneTypeContesto() {
        return new TransazioneType.Contesto();
    }

    /**
     * Create an instance of {@link TransazioneType.IdApplicativo }
     * 
     */
    public TransazioneType.IdApplicativo createTransazioneTypeIdApplicativo() {
        return new TransazioneType.IdApplicativo();
    }

    /**
     * Create an instance of {@link TransazioneType.TransazioniIdentificate }
     * 
     */
    public TransazioneType.TransazioniIdentificate createTransazioneTypeTransazioniIdentificate() {
        return new TransazioneType.TransazioniIdentificate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransazioneType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openspcoop2.org/web/monitor/transazioni/core/search", name = "transazione")
    public JAXBElement<TransazioneType> createTransazione(TransazioneType value) {
        return new JAXBElement<TransazioneType>(ObjectFactory._Transazione_QNAME, TransazioneType.class, null, value);
    }

}
