//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.08 at 10:03:41 AM CET 
//


package org.openspcoop2.web.monitor.transazioni.core.search;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipologia-transazioni_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tipologia-transazioni_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ProxyTrasparente/IntegrationManager"/>
 *     &lt;enumeration value="ProxyTrasparente"/>
 *     &lt;enumeration value="IntegrationManager"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tipologia-transazioni_type", namespace = "http://www.link.it/pdd/monitor/web/pddmonitor/transazioni/core/search")
@XmlEnum
public enum TipologiaTransazioniType {

    @XmlEnumValue("ProxyTrasparente/IntegrationManager")
    PROXY_TRASPARENTE_INTEGRATION_MANAGER("ProxyTrasparente/IntegrationManager"),
    @XmlEnumValue("ProxyTrasparente")
    PROXY_TRASPARENTE("ProxyTrasparente"),
    @XmlEnumValue("IntegrationManager")
    INTEGRATION_MANAGER("IntegrationManager");
    private final String value;

    TipologiaTransazioniType(String v) {
        this.value = v;
    }

    public String value() {
        return this.value;
    }

    public static TipologiaTransazioniType fromValue(String v) {
        for (TipologiaTransazioniType c: TipologiaTransazioniType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
