
package org.openspcoop2.core.tracciamento.ws.client.traccia.all;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-02-16T16:08:57.986+01:00
 * Generated source version: 2.7.4
 */

@WebFault(name = "tracciamento-not-found-exception", targetNamespace = "http://www.openspcoop2.org/core/tracciamento/management")
public class TracciamentoNotFoundException_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoNotFoundException tracciamentoNotFoundException;

    public TracciamentoNotFoundException_Exception() {
        super();
    }
    
    public TracciamentoNotFoundException_Exception(String message) {
        super(message);
    }
    
    public TracciamentoNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TracciamentoNotFoundException_Exception(String message, org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoNotFoundException tracciamentoNotFoundException) {
        super(message);
        this.tracciamentoNotFoundException = tracciamentoNotFoundException;
    }

    public TracciamentoNotFoundException_Exception(String message, org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoNotFoundException tracciamentoNotFoundException, Throwable cause) {
        super(message, cause);
        this.tracciamentoNotFoundException = tracciamentoNotFoundException;
    }

    public org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoNotFoundException getFaultInfo() {
        return this.tracciamentoNotFoundException;
    }
}
