
package org.openspcoop2.core.transazioni.ws.client.transazione.search;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-03-23T14:34:42.831+01:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "transazioni-not-found-exception", targetNamespace = "http://www.openspcoop2.org/core/transazioni/management")
public class TransazioniNotFoundException_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private org.openspcoop2.core.transazioni.ws.client.transazione.search.TransazioniNotFoundException transazioniNotFoundException;

    public TransazioniNotFoundException_Exception() {
        super();
    }
    
    public TransazioniNotFoundException_Exception(String message) {
        super(message);
    }
    
    public TransazioniNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TransazioniNotFoundException_Exception(String message, org.openspcoop2.core.transazioni.ws.client.transazione.search.TransazioniNotFoundException transazioniNotFoundException) {
        super(message);
        this.transazioniNotFoundException = transazioniNotFoundException;
    }

    public TransazioniNotFoundException_Exception(String message, org.openspcoop2.core.transazioni.ws.client.transazione.search.TransazioniNotFoundException transazioniNotFoundException, Throwable cause) {
        super(message, cause);
        this.transazioniNotFoundException = transazioniNotFoundException;
    }

    public org.openspcoop2.core.transazioni.ws.client.transazione.search.TransazioniNotFoundException getFaultInfo() {
        return this.transazioniNotFoundException;
    }
}
