-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_pa_azioni_1 ON pa_azioni ;
-- DROP INDEX index_pa_soggetti_1 ON pa_soggetti ;
-- DROP INDEX index_pa_scope_1 ON pa_scope ;
-- DROP INDEX index_pa_ruoli_1 ON pa_ruoli ;
-- DROP INDEX index_porte_applicative_1 ON porte_applicative ;
-- DROP INDEX INDEX_PA_SA_AUTH ON porte_applicative_sa_auth ;
-- DROP INDEX INDEX_PA_WSSRES ON pa_security_response ;
-- DROP INDEX INDEX_PA_WSSREQ ON pa_security_request ;
-- DROP INDEX INDEX_PA_MTOMTRES ON pa_mtom_response ;
-- DROP INDEX INDEX_PA_MTOMTREQ ON pa_mtom_request ;
-- DROP INDEX INDEX_PA_PROP ON pa_properties ;
-- DROP INDEX INDEX_PA_SA ON porte_applicative_sa ;
DROP TABLE pa_azioni;
DROP TABLE porte_applicative_sa_auth;
DROP TABLE pa_soggetti;
DROP TABLE pa_scope;
DROP TABLE pa_ruoli;
DROP TABLE pa_correlazione_risposta;
DROP TABLE pa_correlazione;
DROP TABLE pa_security_response;
DROP TABLE pa_security_request;
DROP TABLE pa_mtom_response;
DROP TABLE pa_mtom_request;
DROP TABLE pa_properties;
DROP TABLE porte_applicative_sa;
DROP TABLE porte_applicative;
