openapi: 3.0.3
components:
  schemas:
    ImportPet:
      allOf:
        - $ref: '#/components/schemas/ImportNewPet'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64

    ImportNewPet:
      type: object
      title: petTitle
      required:
        - name
        - photoUrls
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            type: string
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold

    ImportError:
      required:
        - code
        - message
      additionalProperties: false
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
