-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_generic_properties_1;
-- DROP INDEX index_pdd_sys_props_1;
-- DROP INDEX index_servizi_pdd_1;
-- DROP INDEX index_config_url_regole_1;
-- DROP INDEX index_generic_property_1;
DROP TABLE canali_nodi;
DROP TABLE canali_configurazione;
DROP TABLE generic_property;
DROP TABLE generic_properties;
DROP TABLE pdd_sys_props;
DROP TABLE servizi_pdd_filtri;
DROP TABLE servizi_pdd;
DROP TABLE tracce_ds_prop;
DROP TABLE tracce_ds;
DROP TABLE msgdiag_ds_prop;
DROP TABLE msgdiag_ds;
DROP TABLE dump_appender_prop;
DROP TABLE dump_appender;
DROP TABLE dump_config_regola;
DROP TABLE dump_config;
DROP TABLE tracce_appender_prop;
DROP TABLE tracce_appender;
DROP TABLE msgdiag_appender_prop;
DROP TABLE msgdiag_appender;
DROP TABLE config_url_regole;
DROP TABLE config_url_invocazione;
DROP TABLE configurazione;
DROP TABLE config_cache_regole;
DROP TABLE routing;
DROP TABLE registri;
