-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_pa_trasf_resp_2;
-- DROP INDEX idx_pa_trasf_resp_1;
-- DROP INDEX index_pa_transform_sa_1;
-- DROP INDEX index_pa_transform_soggetti_1;
-- DROP INDEX index_pa_transform_2;
-- DROP INDEX index_pa_transform_1;
-- DROP INDEX index_pa_azioni_1;
-- DROP INDEX index_pa_soggetti_1;
-- DROP INDEX index_pa_scope_1;
-- DROP INDEX index_pa_ruoli_1;
-- DROP INDEX index_porte_applicative_1;
-- DROP INDEX idx_pa_trasf_hdr_resp_1;
-- DROP INDEX idx_pa_trasf_url_1;
-- DROP INDEX idx_pa_trasf_hdr_1;
-- DROP INDEX INDEX_PA_CACHE;
-- DROP INDEX INDEX_PA_SA_AUTH;
-- DROP INDEX INDEX_PA_CORR_RES;
-- DROP INDEX INDEX_PA_CORR_REQ;
-- DROP INDEX INDEX_PA_WSSRES;
-- DROP INDEX INDEX_PA_WSSREQ;
-- DROP INDEX INDEX_PA_MTOMTRES;
-- DROP INDEX INDEX_PA_MTOMTREQ;
-- DROP INDEX INDEX_PA_PROP;
-- DROP INDEX INDEX_PA_AUTHZC_PROP;
-- DROP INDEX INDEX_PA_AUTHZ_PROP;
-- DROP INDEX INDEX_PA_AUTH_PROP;
-- DROP INDEX INDEX_PA_BEHAVIOUR_PROP;
-- DROP INDEX INDEX_PA_SA_PROP;
-- DROP INDEX INDEX_PA_SA_CODA_MAX;
-- DROP INDEX INDEX_PA_SA_CODA;
-- DROP INDEX INDEX_PA_SA;
-- DROP INDEX index_porte_applicative_3;
-- DROP INDEX index_porte_applicative_2;
DROP TABLE pa_transform_risp_hdr;
DROP TABLE pa_transform_risp;
DROP TABLE pa_transform_url;
DROP TABLE pa_transform_hdr;
DROP TABLE pa_transform_sa;
DROP TABLE pa_transform_soggetti;
DROP TABLE pa_transform;
DROP TABLE pa_cache_regole;
DROP TABLE pa_azioni;
DROP TABLE porte_applicative_sa_auth;
DROP TABLE pa_soggetti;
DROP TABLE pa_scope;
DROP TABLE pa_ruoli;
DROP TABLE pa_correlazione_risposta;
DROP TABLE pa_correlazione;
DROP TABLE pa_security_response;
DROP TABLE pa_security_request;
DROP TABLE pa_mtom_response;
DROP TABLE pa_mtom_request;
DROP TABLE pa_properties;
DROP TABLE pa_authzc_properties;
DROP TABLE pa_authz_properties;
DROP TABLE pa_auth_properties;
DROP TABLE pa_behaviour_props;
DROP TABLE pa_sa_properties;
DROP TABLE porte_applicative_sa;
DROP TABLE porte_applicative;
