-- Adeguamento al limite InnoDB sul record size: VARCHAR(255) -> VARCHAR(256)
--
-- InnoDB con pagine da 16K rifiuta record oltre 8126 byte. In latin1 una colonna
-- VARCHAR(255) vale 255 byte: resta appena sotto la soglia oltre la quale una
-- colonna variabile puo' essere memorizzata su pagina di overflow, quindi conta
-- 256 byte inline nel caso peggiore. Dichiarata VARCHAR(256) diventa candidabile
-- all'overflow e conta 20 byte. Nessun costo in spazio, nessun impatto applicativo:
-- il database accetta un carattere in piu' di quanto l'applicazione scriva.
--
-- Il controllo bloccante è emerso su MySQL 8.4.9
--
-- ATTENZIONE
--   * Il passaggio 255 -> 256 cambia i byte di lunghezza da 1 a 2, quindi non e'
--     eseguibile in-place: richiede ALGORITHM=COPY. La tabella viene ricostruita
--     e le scritture sono bloccate per tutta la durata (LOCK=NONE non e' ammesso:
--     "COPY algorithm requires a lock"). Prevedere una finestra di manutenzione.
--   * Senza questo adeguamento, su MySQL >= 8.4.9 queste tabelle non accettano
--     piu' alcuna ADD COLUMN ne' DROP COLUMN, di nessun tipo.


-- configurazione: 91 colonne
ALTER TABLE configurazione
	MODIFY cadenza_inoltro VARCHAR(256) NOT NULL,
	MODIFY validazione_stato VARCHAR(256),
	MODIFY validazione_controllo VARCHAR(256),
	MODIFY validazione_profilo VARCHAR(256),
	MODIFY validazione_manifest VARCHAR(256),
	MODIFY validazione_contenuti_stato VARCHAR(256),
	MODIFY validazione_contenuti_tipo VARCHAR(256),
	MODIFY validazione_contenuti_mtom VARCHAR(256),
	MODIFY msg_diag_severita VARCHAR(256) NOT NULL,
	MODIFY msg_diag_severita_log4j VARCHAR(256) NOT NULL,
	MODIFY tracciamento_buste VARCHAR(256),
	MODIFY tracciamento_esiti_pd VARCHAR(256),
	MODIFY tracciamento_esiti VARCHAR(256),
	MODIFY transazioni_tempi_pd VARCHAR(256),
	MODIFY transazioni_tempi VARCHAR(256),
	MODIFY transazioni_token_pd VARCHAR(256),
	MODIFY transazioni_token VARCHAR(256),
	MODIFY dump VARCHAR(256),
	MODIFY dump_bin_pd VARCHAR(256),
	MODIFY dump_bin_pa VARCHAR(256),
	MODIFY auth_integration_manager VARCHAR(256),
	MODIFY statocache VARCHAR(256),
	MODIFY dimensionecache VARCHAR(256),
	MODIFY algoritmocache VARCHAR(256),
	MODIFY idlecache VARCHAR(256),
	MODIFY lifecache VARCHAR(256),
	MODIFY config_statocache VARCHAR(256),
	MODIFY config_dimensionecache VARCHAR(256),
	MODIFY config_algoritmocache VARCHAR(256),
	MODIFY config_idlecache VARCHAR(256),
	MODIFY config_lifecache VARCHAR(256),
	MODIFY auth_statocache VARCHAR(256),
	MODIFY auth_dimensionecache VARCHAR(256),
	MODIFY auth_algoritmocache VARCHAR(256),
	MODIFY auth_idlecache VARCHAR(256),
	MODIFY auth_lifecache VARCHAR(256),
	MODIFY authn_statocache VARCHAR(256),
	MODIFY authn_dimensionecache VARCHAR(256),
	MODIFY authn_algoritmocache VARCHAR(256),
	MODIFY authn_idlecache VARCHAR(256),
	MODIFY authn_lifecache VARCHAR(256),
	MODIFY token_statocache VARCHAR(256),
	MODIFY token_dimensionecache VARCHAR(256),
	MODIFY token_algoritmocache VARCHAR(256),
	MODIFY token_idlecache VARCHAR(256),
	MODIFY token_lifecache VARCHAR(256),
	MODIFY aa_statocache VARCHAR(256),
	MODIFY aa_dimensionecache VARCHAR(256),
	MODIFY aa_algoritmocache VARCHAR(256),
	MODIFY aa_idlecache VARCHAR(256),
	MODIFY aa_lifecache VARCHAR(256),
	MODIFY keystore_statocache VARCHAR(256),
	MODIFY keystore_dimensionecache VARCHAR(256),
	MODIFY keystore_algoritmocache VARCHAR(256),
	MODIFY keystore_idlecache VARCHAR(256),
	MODIFY keystore_lifecache VARCHAR(256),
	MODIFY keystore_crl_lifecache VARCHAR(256),
	MODIFY mod_risposta VARCHAR(256),
	MODIFY indirizzo_telematico VARCHAR(256),
	MODIFY gestione_manifest VARCHAR(256),
	MODIFY routing_enabled VARCHAR(256) NOT NULL,
	MODIFY multitenant_stato VARCHAR(256),
	MODIFY multitenant_fruizioni VARCHAR(256),
	MODIFY multitenant_erogazioni VARCHAR(256),
	MODIFY cors_stato VARCHAR(256),
	MODIFY cors_tipo VARCHAR(256),
	MODIFY cors_all_allow_origins VARCHAR(256),
	MODIFY cors_all_allow_methods VARCHAR(256),
	MODIFY cors_all_allow_headers VARCHAR(256),
	MODIFY cors_allow_credentials VARCHAR(256),
	MODIFY response_cache_stato VARCHAR(256),
	MODIFY response_cache_hash_url VARCHAR(256),
	MODIFY response_cache_hash_query VARCHAR(256),
	MODIFY response_cache_hash_headers VARCHAR(256),
	MODIFY response_cache_hash_payload VARCHAR(256),
	MODIFY response_cache_statocache VARCHAR(256),
	MODIFY response_cache_dimensionecache VARCHAR(256),
	MODIFY response_cache_algoritmocache VARCHAR(256),
	MODIFY response_cache_idlecache VARCHAR(256),
	MODIFY response_cache_lifecache VARCHAR(256),
	MODIFY consegna_statocache VARCHAR(256),
	MODIFY consegna_dimensionecache VARCHAR(256),
	MODIFY consegna_algoritmocache VARCHAR(256),
	MODIFY consegna_idlecache VARCHAR(256),
	MODIFY consegna_lifecache VARCHAR(256),
	MODIFY canali_stato VARCHAR(256),
	MODIFY dati_richieste_statocache VARCHAR(256),
	MODIFY dati_richieste_dimensionecache VARCHAR(256),
	MODIFY dati_richieste_algoritmocache VARCHAR(256),
	MODIFY dati_richieste_idlecache VARCHAR(256),
	MODIFY dati_richieste_lifecache VARCHAR(256),
	ALGORITHM=COPY, LOCK=SHARED;


-- porte_delegate: 71 colonne
ALTER TABLE porte_delegate
	MODIFY tipo_soggetto_erogatore VARCHAR(256) NOT NULL,
	MODIFY nome_soggetto_erogatore VARCHAR(256) NOT NULL,
	MODIFY tipo_servizio VARCHAR(256) NOT NULL,
	MODIFY nome_servizio VARCHAR(256) NOT NULL,
	MODIFY nome_azione VARCHAR(256),
	MODIFY mode_azione VARCHAR(256),
	MODIFY pattern_azione VARCHAR(256),
	MODIFY nome_porta_delegante_azione VARCHAR(256),
	MODIFY force_interface_based_azione VARCHAR(256),
	MODIFY autenticazione VARCHAR(256),
	MODIFY autenticazione_opzionale VARCHAR(256),
	MODIFY token_policy VARCHAR(256),
	MODIFY token_opzionale VARCHAR(256),
	MODIFY token_validazione VARCHAR(256),
	MODIFY token_introspection VARCHAR(256),
	MODIFY token_user_info VARCHAR(256),
	MODIFY token_forward VARCHAR(256),
	MODIFY token_authn_issuer VARCHAR(256),
	MODIFY token_authn_client_id VARCHAR(256),
	MODIFY token_authn_subject VARCHAR(256),
	MODIFY token_authn_username VARCHAR(256),
	MODIFY token_authn_email VARCHAR(256),
	MODIFY autorizzazione VARCHAR(256),
	MODIFY autorizzazione_contenuto VARCHAR(256),
	MODIFY mtom_request_mode VARCHAR(256),
	MODIFY mtom_response_mode VARCHAR(256),
	MODIFY security VARCHAR(256),
	MODIFY security_mtom_req VARCHAR(256),
	MODIFY security_mtom_res VARCHAR(256),
	MODIFY security_request_mode VARCHAR(256),
	MODIFY security_response_mode VARCHAR(256),
	MODIFY ricevuta_asincrona_sim VARCHAR(256),
	MODIFY ricevuta_asincrona_asim VARCHAR(256),
	MODIFY validazione_contenuti_stato VARCHAR(256),
	MODIFY validazione_contenuti_tipo VARCHAR(256),
	MODIFY validazione_contenuti_mtom VARCHAR(256),
	MODIFY scadenza_correlazione_appl VARCHAR(256),
	MODIFY allega_body VARCHAR(256),
	MODIFY scarta_body VARCHAR(256),
	MODIFY gestione_manifest VARCHAR(256),
	MODIFY stateless VARCHAR(256),
	MODIFY local_forward VARCHAR(256),
	MODIFY local_forward_pa VARCHAR(256),
	MODIFY ruoli_match VARCHAR(256),
	MODIFY token_sa_stato VARCHAR(256),
	MODIFY token_ruoli_stato VARCHAR(256),
	MODIFY token_ruoli_match VARCHAR(256),
	MODIFY token_ruoli_tipologia VARCHAR(256),
	MODIFY scope_stato VARCHAR(256),
	MODIFY scope_match VARCHAR(256),
	MODIFY ricerca_porta_azione_delegata VARCHAR(256),
	MODIFY msg_diag_severita VARCHAR(256),
	MODIFY tracciamento_stato VARCHAR(256),
	MODIFY tracciamento_esiti VARCHAR(256),
	MODIFY transazioni_tempi VARCHAR(256),
	MODIFY transazioni_token VARCHAR(256),
	MODIFY cors_stato VARCHAR(256),
	MODIFY cors_tipo VARCHAR(256),
	MODIFY cors_all_allow_origins VARCHAR(256),
	MODIFY cors_all_allow_methods VARCHAR(256),
	MODIFY cors_all_allow_headers VARCHAR(256),
	MODIFY cors_allow_credentials VARCHAR(256),
	MODIFY response_cache_stato VARCHAR(256),
	MODIFY response_cache_hash_url VARCHAR(256),
	MODIFY response_cache_hash_query VARCHAR(256),
	MODIFY response_cache_hash_headers VARCHAR(256),
	MODIFY response_cache_hash_payload VARCHAR(256),
	MODIFY stato VARCHAR(256),
	MODIFY canale VARCHAR(256),
	MODIFY utente_richiedente VARCHAR(256),
	MODIFY utente_ultima_modifica VARCHAR(256),
	ALGORITHM=COPY, LOCK=SHARED;


-- porte_applicative: 70 colonne
ALTER TABLE porte_applicative
	MODIFY tipo_soggetto_virtuale VARCHAR(256),
	MODIFY nome_soggetto_virtuale VARCHAR(256),
	MODIFY tipo_servizio VARCHAR(256) NOT NULL,
	MODIFY servizio VARCHAR(256) NOT NULL,
	MODIFY azione VARCHAR(256),
	MODIFY mode_azione VARCHAR(256),
	MODIFY pattern_azione VARCHAR(256),
	MODIFY nome_porta_delegante_azione VARCHAR(256),
	MODIFY force_interface_based_azione VARCHAR(256),
	MODIFY mtom_request_mode VARCHAR(256),
	MODIFY mtom_response_mode VARCHAR(256),
	MODIFY security VARCHAR(256),
	MODIFY security_mtom_req VARCHAR(256),
	MODIFY security_mtom_res VARCHAR(256),
	MODIFY security_request_mode VARCHAR(256),
	MODIFY security_response_mode VARCHAR(256),
	MODIFY ricevuta_asincrona_sim VARCHAR(256),
	MODIFY ricevuta_asincrona_asim VARCHAR(256),
	MODIFY validazione_contenuti_stato VARCHAR(256),
	MODIFY validazione_contenuti_tipo VARCHAR(256),
	MODIFY validazione_contenuti_mtom VARCHAR(256),
	MODIFY scadenza_correlazione_appl VARCHAR(256),
	MODIFY allega_body VARCHAR(256),
	MODIFY scarta_body VARCHAR(256),
	MODIFY gestione_manifest VARCHAR(256),
	MODIFY stateless VARCHAR(256),
	MODIFY behaviour VARCHAR(256),
	MODIFY autenticazione VARCHAR(256),
	MODIFY autenticazione_opzionale VARCHAR(256),
	MODIFY token_policy VARCHAR(256),
	MODIFY token_opzionale VARCHAR(256),
	MODIFY token_validazione VARCHAR(256),
	MODIFY token_introspection VARCHAR(256),
	MODIFY token_user_info VARCHAR(256),
	MODIFY token_forward VARCHAR(256),
	MODIFY token_authn_issuer VARCHAR(256),
	MODIFY token_authn_client_id VARCHAR(256),
	MODIFY token_authn_subject VARCHAR(256),
	MODIFY token_authn_username VARCHAR(256),
	MODIFY token_authn_email VARCHAR(256),
	MODIFY autorizzazione VARCHAR(256),
	MODIFY autorizzazione_contenuto VARCHAR(256),
	MODIFY ruoli_match VARCHAR(256),
	MODIFY token_sa_stato VARCHAR(256),
	MODIFY token_ruoli_stato VARCHAR(256),
	MODIFY token_ruoli_match VARCHAR(256),
	MODIFY token_ruoli_tipologia VARCHAR(256),
	MODIFY scope_stato VARCHAR(256),
	MODIFY scope_match VARCHAR(256),
	MODIFY ricerca_porta_azione_delegata VARCHAR(256),
	MODIFY msg_diag_severita VARCHAR(256),
	MODIFY tracciamento_stato VARCHAR(256),
	MODIFY tracciamento_esiti VARCHAR(256),
	MODIFY transazioni_tempi VARCHAR(256),
	MODIFY transazioni_token VARCHAR(256),
	MODIFY cors_stato VARCHAR(256),
	MODIFY cors_tipo VARCHAR(256),
	MODIFY cors_all_allow_origins VARCHAR(256),
	MODIFY cors_all_allow_methods VARCHAR(256),
	MODIFY cors_all_allow_headers VARCHAR(256),
	MODIFY cors_allow_credentials VARCHAR(256),
	MODIFY response_cache_stato VARCHAR(256),
	MODIFY response_cache_hash_url VARCHAR(256),
	MODIFY response_cache_hash_query VARCHAR(256),
	MODIFY response_cache_hash_headers VARCHAR(256),
	MODIFY response_cache_hash_payload VARCHAR(256),
	MODIFY stato VARCHAR(256),
	MODIFY canale VARCHAR(256),
	MODIFY utente_richiedente VARCHAR(256),
	MODIFY utente_ultima_modifica VARCHAR(256),
	ALGORITHM=COPY, LOCK=SHARED;


-- servizi_applicativi: 27 colonne
ALTER TABLE servizi_applicativi
	MODIFY tipo VARCHAR(256),
	MODIFY getmsgrisp VARCHAR(256),
	MODIFY tipoauthrisp VARCHAR(256),
	MODIFY utenterisp VARCHAR(256),
	MODIFY passwordrisp VARCHAR(256),
	MODIFY invio_x_rif_risp VARCHAR(256),
	MODIFY risposta_x_rif_risp VARCHAR(256),
	MODIFY getmsginv VARCHAR(256),
	MODIFY tipoauthinv VARCHAR(256),
	MODIFY utenteinv VARCHAR(256),
	MODIFY passwordinv VARCHAR(256),
	MODIFY invio_x_rif_inv VARCHAR(256),
	MODIFY risposta_x_rif_inv VARCHAR(256),
	MODIFY fault VARCHAR(256),
	MODIFY fault_actor VARCHAR(256),
	MODIFY generic_fault_code VARCHAR(256),
	MODIFY prefix_fault_code VARCHAR(256),
	MODIFY tipoauth VARCHAR(256),
	MODIFY password VARCHAR(256),
	MODIFY cn_subject VARCHAR(256),
	MODIFY cn_issuer VARCHAR(256),
	MODIFY token_policy VARCHAR(256),
	MODIFY invio_x_rif VARCHAR(256),
	MODIFY tipologia_fruizione VARCHAR(256),
	MODIFY tipologia_erogazione VARCHAR(256),
	MODIFY utente_richiedente VARCHAR(256),
	MODIFY utente_ultima_modifica VARCHAR(256),
	ALGORITHM=COPY, LOCK=SHARED;
