<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://org.ecodex.backend/1_1/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" name="BackendService_1_1" targetNamespace="http://org.ecodex.backend/1_1/">
  <wsdl:types>


		<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/">
			<import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" schemaLocation="ebms-header-3_0-200704_subset-ecodex-backend.xsd"/>
		</schema>


		<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://org.ecodex.backend/1_1/">
			<import namespace="http://org.ecodex.backend/1_1/" schemaLocation="org-ecodex-backend-1_1.xsd"/>
		</schema>


		<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3.org/XML/1998/namespace">
			<import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
		</schema>


		<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3.org/2005/05/xmlmime">
			<import namespace="http://www.w3.org/2005/05/xmlmime" schemaLocation="xmlmime.xsd"/>
		</schema>

  </wsdl:types>
  <wsdl:message name="getStatusResponse">
    <wsdl:part element="tns:getStatusResponse" name="getStatusResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listPendingMessagesResponse">
    <wsdl:part element="tns:listPendingMessagesResponse" name="listPendingMessagesResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getMessageErrorsResponse">
    <wsdl:part element="tns:getMessageErrorsResponse" name="getMessageErrorsResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="submitMessageResponse">
    <wsdl:part element="tns:submitResponse" name="submitResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RetrieveMessageFault">
    <wsdl:part element="tns:FaultDetail" name="RetrieveMessageFault">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getMessageErrors">
    <wsdl:part element="tns:getErrorsRequest" name="getErrorsRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getStatus">
    <wsdl:part element="tns:statusRequest" name="statusRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listPendingMessages">
    <wsdl:part element="tns:listPendingMessagesRequest" name="listPendingMessagesRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SubmitMessageFault">
    <wsdl:part element="tns:FaultDetail" name="SubmitMessageFault">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="StatusFault">
    <wsdl:part element="tns:FaultDetail" name="StatusFault">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="submitMessage">
    <wsdl:part element="tns:submitRequest" name="submitRequest">
    </wsdl:part>
    <wsdl:part element="ns1:Messaging" name="ebMSHeaderInfo">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="retrieveMessage">
    <wsdl:part element="tns:retrieveMessageRequest" name="retrieveMessageRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="retrieveMessageResponse">
    <wsdl:part element="tns:retrieveMessageResponse" name="retrieveMessageResponse">
    </wsdl:part>
    <wsdl:part element="ns1:Messaging" name="ebMSHeaderInfo">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="BackendInterface">
    <wsdl:operation name="listPendingMessages">
      <wsdl:input message="tns:listPendingMessages" name="listPendingMessages">
    </wsdl:input>
      <wsdl:output message="tns:listPendingMessagesResponse" name="listPendingMessagesResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getMessageErrors">
      <wsdl:input message="tns:getMessageErrors" name="getMessageErrors">
    </wsdl:input>
      <wsdl:output message="tns:getMessageErrorsResponse" name="getMessageErrorsResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getStatus">
      <wsdl:input message="tns:getStatus" name="getStatus">
    </wsdl:input>
      <wsdl:output message="tns:getStatusResponse" name="getStatusResponse">
    </wsdl:output>
      <wsdl:fault message="tns:StatusFault" name="StatusFault">
    </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="submitMessage">
      <wsdl:input message="tns:submitMessage" name="submitMessage">
    </wsdl:input>
      <wsdl:output message="tns:submitMessageResponse" name="submitMessageResponse">
    </wsdl:output>
      <wsdl:fault message="tns:SubmitMessageFault" name="SubmitMessageFault">
    </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="retrieveMessage" parameterOrder="retrieveMessageRequest retrieveMessageResponse ebMSHeaderInfo">
      <wsdl:input message="tns:retrieveMessage" name="retrieveMessage">
    </wsdl:input>
      <wsdl:output message="tns:retrieveMessageResponse" name="retrieveMessageResponse">
    </wsdl:output>
      <wsdl:fault message="tns:RetrieveMessageFault" name="RetrieveMessageFault">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BackendService_1_1SoapBinding" type="tns:BackendInterface">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="listPendingMessages">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="listPendingMessages">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listPendingMessagesResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getMessageErrors">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="getMessageErrors">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getMessageErrorsResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getStatus">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="getStatus">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getStatusResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="StatusFault">
        <soap12:fault name="StatusFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="submitMessage">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="submitMessage">
        <soap12:header message="tns:submitMessage" part="ebMSHeaderInfo" use="literal">
        </soap12:header>
        <soap12:body parts="submitRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output name="submitMessageResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SubmitMessageFault">
        <soap12:fault name="SubmitMessageFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="retrieveMessage">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="retrieveMessage">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="retrieveMessageResponse">
        <soap12:header message="tns:retrieveMessageResponse" part="ebMSHeaderInfo" use="literal">
        </soap12:header>
        <soap12:body parts="retrieveMessageResponse" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="RetrieveMessageFault">
        <soap12:fault name="RetrieveMessageFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BackendService_1_1">
    <wsdl:port binding="tns:BackendService_1_1SoapBinding" name="BACKEND_PORT">
      <soap12:address location="http://localhost:8580/domibus-wildfly/services/backend"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
