-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_conf_filtri_1;
-- DROP INDEX index_plugins_conf_azioni_1;
-- DROP INDEX index_plugins_azioni_comp_1;
-- DROP INDEX index_plugins_2;
-- DROP INDEX index_plugins_1;
-- DROP INDEX idx_conf_servizi_1;
-- DROP INDEX idx_plug_filtro_com_1;
-- DROP INDEX idx_plug_ser_com_1;
DROP TABLE plugins_conf_filtri_init_seq;
DROP TABLE plugins_conf_filtri;
DROP TABLE plugins_conf_azioni_init_seq;
DROP TABLE plugins_conf_azioni;
DROP TABLE plugins_conf_servizi_init_seq;
DROP TABLE plugins_conf_servizi;
DROP TABLE plugins_filtro_comp_init_seq;
DROP TABLE plugins_filtro_comp;
DROP TABLE plugins_azioni_comp_init_seq;
DROP TABLE plugins_azioni_comp;
DROP TABLE plugins_servizi_comp_init_seq;
DROP TABLE plugins_servizi_comp;
DROP TABLE plugins_init_seq;
DROP TABLE plugins;
DROP TABLE plugin_info;
DROP SEQUENCE seq_plugins_conf_filtri;
DROP SEQUENCE seq_plugins_conf_azioni;
DROP SEQUENCE seq_plugins_conf_servizi;
DROP SEQUENCE seq_plugins_filtro_comp;
DROP SEQUENCE seq_plugins_azioni_comp;
DROP SEQUENCE seq_plugins_servizi_comp;
DROP SEQUENCE seq_plugins;
