-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX INDEX_AC_SC_SERV;
-- DROP INDEX INDEX_AC_SC_SC;
-- DROP INDEX INDEX_AC_SC;
-- DROP INDEX index_serv_fru_azioni_1;
-- DROP INDEX INDEX_SERV_FRU_SOG;
-- DROP INDEX index_servizi_azioni_1;
-- DROP INDEX INDEX_SERV_SOG;
-- DROP INDEX INDEX_SERV_ACC;
-- DROP INDEX INDEX_AC_SOG;
-- DROP INDEX INDEX_AC_COOP_PAR;
-- DROP INDEX INDEX_OP_MESSAGES;
-- DROP INDEX index_accordi_1;
-- DROP INDEX INDEX_DOC_SEARCH;
DROP TABLE acc_serv_componenti_init_seq;
DROP TABLE acc_serv_componenti;
DROP TABLE acc_serv_composti_init_seq;
DROP TABLE acc_serv_composti;
DROP TABLE servizi_fruitori_azione_init_seq;
DROP TABLE servizi_fruitori_azione;
DROP TABLE servizi_fruitori_azioni_init_seq;
DROP TABLE servizi_fruitori_azioni;
DROP TABLE servizi_fruitori_init_seq;
DROP TABLE servizi_fruitori;
DROP TABLE servizi_azione_init_seq;
DROP TABLE servizi_azione;
DROP TABLE servizi_azioni_init_seq;
DROP TABLE servizi_azioni;
DROP TABLE servizi_init_seq;
DROP TABLE servizi;
DROP TABLE accordi_coop_partecipanti_init_seq;
DROP TABLE accordi_coop_partecipanti;
DROP TABLE accordi_cooperazione_init_seq;
DROP TABLE accordi_cooperazione;
DROP TABLE accordi_gruppi_init_seq;
DROP TABLE accordi_gruppi;
DROP TABLE api_resources_parameter_init_seq;
DROP TABLE api_resources_parameter;
DROP TABLE api_resources_media_init_seq;
DROP TABLE api_resources_media;
DROP TABLE api_resources_response_init_seq;
DROP TABLE api_resources_response;
DROP TABLE api_resources_init_seq;
DROP TABLE api_resources;
DROP TABLE operation_messages_init_seq;
DROP TABLE operation_messages;
DROP TABLE port_type_azioni_init_seq;
DROP TABLE port_type_azioni;
DROP TABLE port_type_init_seq;
DROP TABLE port_type;
DROP TABLE accordi_azioni_init_seq;
DROP TABLE accordi_azioni;
DROP TABLE accordi_init_seq;
DROP TABLE accordi;
DROP TABLE documenti_init_seq;
DROP TABLE documenti;
DROP SEQUENCE seq_acc_serv_componenti;
DROP SEQUENCE seq_acc_serv_composti;
DROP SEQUENCE seq_servizi_fruitori_azione;
DROP SEQUENCE seq_servizi_fruitori_azioni;
DROP SEQUENCE seq_servizi_fruitori;
DROP SEQUENCE seq_servizi_azione;
DROP SEQUENCE seq_servizi_azioni;
DROP SEQUENCE seq_servizi;
DROP SEQUENCE seq_accordi_coop_partecipanti;
DROP SEQUENCE seq_accordi_cooperazione;
DROP SEQUENCE seq_accordi_gruppi;
DROP SEQUENCE seq_api_resources_parameter;
DROP SEQUENCE seq_api_resources_media;
DROP SEQUENCE seq_api_resources_response;
DROP SEQUENCE seq_api_resources;
DROP SEQUENCE seq_operation_messages;
DROP SEQUENCE seq_port_type_azioni;
DROP SEQUENCE seq_port_type;
DROP SEQUENCE seq_accordi_azioni;
DROP SEQUENCE seq_accordi;
DROP SEQUENCE seq_documenti;
