-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX INDEX_AC_SC_SC;
-- DROP INDEX INDEX_AC_SC;
-- DROP INDEX index_acc_serv_composti_1;
-- DROP INDEX index_servizi_azioni_1;
-- DROP INDEX index_servizi_fruitori_1;
-- DROP INDEX INDEX_APS;
-- DROP INDEX index_servizi_1;
-- DROP INDEX INDEX_AC_COOP_PAR;
-- DROP INDEX index_accordi_cooperazione_1;
-- DROP INDEX INDEX_OP_MESSAGES;
-- DROP INDEX index_port_type_azioni_1;
-- DROP INDEX index_port_type_1;
-- DROP INDEX index_accordi_azioni_1;
-- DROP INDEX index_accordi_1;
-- DROP INDEX INDEX_DOC_SEARCH;
-- DROP INDEX index_documenti_1;
DROP TABLE acc_serv_componenti_init_seq;
DROP TABLE acc_serv_componenti;
DROP TABLE acc_serv_composti_init_seq;
DROP TABLE acc_serv_composti;
DROP TABLE servizi_azioni_init_seq;
DROP TABLE servizi_azioni;
DROP TABLE servizi_fruitori_init_seq;
DROP TABLE servizi_fruitori;
DROP TABLE servizi_init_seq;
DROP TABLE servizi;
DROP TABLE accordi_coop_partecipanti_init_seq;
DROP TABLE accordi_coop_partecipanti;
DROP TABLE accordi_cooperazione_init_seq;
DROP TABLE accordi_cooperazione;
DROP TABLE operation_messages_init_seq;
DROP TABLE operation_messages;
DROP TABLE port_type_azioni_init_seq;
DROP TABLE port_type_azioni;
DROP TABLE port_type_init_seq;
DROP TABLE port_type;
DROP TABLE accordi_azioni_init_seq;
DROP TABLE accordi_azioni;
DROP TABLE accordi_init_seq;
DROP TABLE accordi;
DROP TABLE documenti_init_seq;
DROP TABLE documenti;
DROP SEQUENCE seq_acc_serv_componenti;
DROP SEQUENCE seq_acc_serv_composti;
DROP SEQUENCE seq_servizi_azioni;
DROP SEQUENCE seq_servizi_fruitori;
DROP SEQUENCE seq_servizi;
DROP SEQUENCE seq_accordi_coop_partecipanti;
DROP SEQUENCE seq_accordi_cooperazione;
DROP SEQUENCE seq_operation_messages;
DROP SEQUENCE seq_port_type_azioni;
DROP SEQUENCE seq_port_type;
DROP SEQUENCE seq_accordi_azioni;
DROP SEQUENCE seq_accordi;
DROP SEQUENCE seq_documenti;
