DROP INDEX INDEX_TRSA_IN_QUEUE ON transazioni_sa;
DROP INDEX INDEX_TRSA_SEND ON transazioni_sa;
ALTER TABLE transazioni_sa DROP CONSTRAINT unique_transazioni_sa_1;
ALTER TABLE transazioni_sa ALTER COLUMN servizio_applicativo_erogatore VARCHAR(1024) NOT NULL;
ALTER TABLE transazioni_sa ADD CONSTRAINT unique_transazioni_sa_1 UNIQUE (id_transazione,servizio_applicativo_erogatore);
CREATE INDEX INDEX_TRSA_IN_QUEUE ON transazioni_sa (data_registrazione DESC,servizio_applicativo_erogatore,connettore_nome,consegna_terminata,dettaglio_esito,consegna_trasparente,consegna_im,numero_tentativi,codice_risposta,data_uscita_richiesta,data_ingresso_risposta,numero_prelievi_im,data_eliminazione_im);
CREATE INDEX INDEX_TRSA_SEND ON transazioni_sa (data_uscita_richiesta DESC,servizio_applicativo_erogatore,connettore_nome,data_ingresso_risposta,consegna_terminata,dettaglio_esito,consegna_trasparente,consegna_im,numero_tentativi,codice_risposta,data_registrazione);
